// i18n - 다국어 지원
const LANG = {
  en: {
    nav_home:'HOME',nav_shop:'SHOP',nav_custom:'CUSTOM',nav_used:'USED MARKET',nav_forum:'FORUM',nav_events:'EVENTS',nav_factory:'FACTORY',nav_settings:'SETTINGS',
    pt_home:'Home',pt_shop:'Shop',pt_custom:'Custom Abutment',pt_used:'Used Market',pt_forum:'Forum',pt_events:'Events',pt_factory:'Factory',pt_settings:'Settings',
    login_subtitle:'DOCTOR LOGIN',login_ph:'License Number',login_btn:'LOGIN',login_cancel:'Cancel',login_error:'Please enter your license number.',login_verifying:'Verifying...',login_not_found:'License not found or inactive. Please contact admin.',login_network_error:'Network error. Please try again.',login_register_link:'Request Access →',
    reg_title:'Request Access',reg_subtitle:'Fill in your details. Admin will approve within 24 hours.',reg_license_ph:'License Number (required)',reg_name_ph:'Doctor Name (required)',reg_clinic_ph:'Clinic Name (required)',reg_contact_ph:'Phone or Line ID (required)',reg_submit:'Submit Request',reg_submitting:'Submitting...',reg_success:'Request submitted!\nWe will contact you within 24 hours after approval.',reg_error:'Please fill in all required fields.',reg_duplicate:'This license number is already registered.',reg_network_error:'Network error. Please try again.',
    session_title:'Session Expiring',session_desc1:'Login expires in',session_desc2:'',session_q:'Would you like to extend?',session_extend:'Extend 30 min',session_later:'Later',session_expired:'Session expired. Please log in again.',
    side_remain:'Remaining:',side_login_btn:'Doctor Login',side_logged_label:'Logged In',side_logout:'Logout',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'Digital Implant Parts',home_title2:'Ordering System',home_desc:'Providing premium BIOTEM implant components directly to dental clinics across Thailand.',home_goto_shop:'Go to Shop',home_about:'About Us',home_biotem_desc:'Korea-based dental implant manufacturer. Expert of Implant with cutting-edge digital workflow solutions.',home_bioplant_desc:'Premium dental fixture manufacturing center in Bangkok. Supplying clinics across Southeast Asia.',home_categories:'Product Categories',home_contact:'Contact & Address',home_address:'Bangkok, Thailand',home_hours:'Mon-Fri 09:00-18:00',home_line_label:'Line Official',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    shop_hint:'Select a category to order',shop_select:'SELECT ›',shop_each:'each',
    order_add_cart:'Add to Cart',order_qty_error:'Please enter at least 1 quantity.',
    cart_title:'My Cart',cart_total:'TOTAL',cart_checkout:'CHECKOUT',cart_close:'Close',cart_empty:'Cart is empty!',
    addr_title:'Delivery Info',addr_clinic_ph:'Clinic Name',addr_phone_ph:'Phone Number',addr_addr_ph:'Full Address',addr_qr_btn:'GENERATE QR',addr_back:'← Back',addr_fill_error:'Please fill in all delivery info.',
    qr_label:'Scan to Pay',qr_summary_title:'Order Summary',qr_total:'TOTAL',qr_complete:'PAYMENT COMPLETE',
    used_contact_title:'Contact Seller',used_contact_close:'Close',
    custom_tab_new:'New Order',custom_tab_list:'My Orders',custom_form_title:'Custom Abutment Order',custom_delivery_title:'Delivery Info',custom_clinic_ph:'Clinic / Lab Name',custom_addr_ph:'Delivery Address',custom_phone_ph:'Contact Number',custom_line_ph:'Line ID (for notifications)',custom_submit:'Submit Order',custom_submit_note:'Order confirmation will be sent via Line',custom_empty:'No orders yet',
    case_label:'Case #',case_remove:'✕ Remove',case_patient_ph:'Patient ID (anonymous ok, e.g. P001)',case_tooth_hint:'Select teeth · Tap to toggle',upper_jaw:'Upper Jaw',lower_jaw:'Lower Jaw',jaw_border:'Arch Boundary',selected_teeth:'Selected Teeth —',sel_count_suffix:'',brand_ph:'Select implant brand',size_ph:'Size (e.g. Ø4.0 / L10)',color_ph:'Tooth color (VITA)',case_add:'+ Add Case',stl_label:'Upload STL File',stl_hint:'Tap to select .stl file',memo_ph:'Special requests (optional)',anon_patient:'Anonymous',
    err_fill_delivery:'Please enter clinic name, address, and phone number.',err_select_tooth:'Case #%: Please select at least 1 tooth.',err_fill_tooth:'Case #% Tooth #%: Please enter implant brand and size.',err_add_case:'Please add at least 1 case.',
    order_success_msg:'✅ Order submitted!\nOrder #: %\nCases: % / Teeth: %',order_success_line:'\nConfirmation sent via Line.',
    status_label:'Progress',case_detail:'Case Details',teeth_count:' teeth',cases_unit:' cases',teeth_total_prefix:'',patient_label:'Patient: ',no_tooth_info:'(no tooth data)',case_nr:'Case #',
    used_sell_title:'Sell Used Parts',used_name_ph:'Part Name',used_code_ph:'Product Code',used_price_ph:'Price (THB)',cond_new:'Like New',cond_good:'Good',cond_fair:'Fair',used_desc_ph:'Condition details...',used_contact_ph:'Contact (Line ID / Phone)',used_post_btn:'POST FOR SALE',used_list_title:'Available Used Parts',used_contact_btn:'Contact',used_delete_btn:'Delete',used_empty:'No used parts listed yet',used_fill_error:'Please enter part name, price, and contact.',
    forum_new_post:'New Post',forum_title_ph:'Title',forum_body_ph:'Write your message...',forum_post_btn:'POST',
    settings_lang:'Language',settings_account:'Account',settings_license:'License:',settings_save_btn:'Save Language',settings_saved_msg:'Language saved!',settings_pending:'Select a language then press Save.',
    pe_title:'✏️ Edit My Info',pe_subtitle:'Editable Fields',pe_email:'Email',pe_phone:'Phone Number',pe_address:'Address',pe_clinic:'Clinic Name',pe_save:'Save',pe_cancel:'Cancel',pe_email_ph:'Email address',pe_phone_ph:'Phone number',pe_address_ph:'Address',pe_clinic_ph:'Clinic name',
    profile_title:'👤 My Info',profile_edit_btn:'Edit',profile_login_msg:'Please log in to view.',profile_saved_msg:'✅ Saved!',profile_no_change:'(cannot change)',prof_nickname:'Nickname',prof_doctor:'Doctor Name',login_required:'Login required.',
    factory_subtitle:'Premium fixture manufacturing center in Bangkok',
    tooth_11:'Central Incisor',tooth_12:'Lateral Incisor',tooth_13:'Canine',tooth_14:'1st Premolar',tooth_15:'2nd Premolar',tooth_16:'1st Molar',tooth_17:'2nd Molar',
    upper:'Upper',lower:'Lower',
    stage_received:'Order Received',stage_stl:'STL Review',stage_design:'Designing',stage_cnc:'CNC Production',stage_qc:'Quality Check',stage_shipping:'Shipping',stage_done:'Delivered',
  },
  ko: {
    nav_home:'HOME',nav_shop:'SHOP',nav_custom:'CUSTOM',nav_used:'중고마켓',nav_forum:'FORUM',nav_events:'이벤트',nav_factory:'공장',nav_settings:'설정',
    pt_home:'Home',pt_shop:'Shop',pt_custom:'Custom Abutment',pt_used:'중고마켓',pt_forum:'Forum',pt_events:'Events',pt_factory:'Factory',pt_settings:'설정',
    login_subtitle:'의사 로그인',login_ph:'면허 번호',login_btn:'로그인',login_cancel:'취소',login_error:'면허 번호를 입력해주세요.',login_verifying:'확인 중...',login_not_found:'등록되지 않았거나 비활성화된 면허번호입니다. 관리자에게 문의해주세요.',login_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',login_register_link:'사용 신청하기 →',
    reg_title:'사용 신청',reg_subtitle:'정보를 입력하시면 24시간 내에 검토 후 승인해 드립니다.',reg_license_ph:'면허 번호 (필수)',reg_name_ph:'의사 이름 (필수)',reg_clinic_ph:'치과명 (필수)',reg_contact_ph:'전화번호 또는 Line ID (필수)',reg_submit:'신청하기',reg_submitting:'신청 중...',reg_success:'신청이 접수되었습니다!\n관리자 승인 후 24시간 내에 연락드리겠습니다.',reg_error:'필수 항목을 모두 입력해주세요.',reg_duplicate:'이미 등록된 면허번호입니다.',reg_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',
    session_title:'세션 만료 임박',session_desc1:'로그인이',session_desc2:'후 만료됩니다.',session_q:'지금 연장하시겠어요?',session_extend:'30분 연장하기',session_later:'나중에',session_expired:'세션이 만료되었습니다. 다시 로그인해주세요.',
    side_remain:'남은 시간:',side_login_btn:'의사 로그인',side_logged_label:'로그인 중',side_logout:'로그아웃',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'디지털 임플란트 부품',home_title2:'주문 시스템',home_desc:'태국 전역 치과에 프리미엄 BIOTEM 임플란트 부품을 직접 공급합니다.',home_goto_shop:'쇼핑몰로 이동',home_about:'회사 소개',home_biotem_desc:'한국 기반 치과 임플란트 제조사. 최첨단 디지털 워크플로우 솔루션 전문.',home_bioplant_desc:'방콕의 프리미엄 임플란트 제조 센터. 동남아시아 전역 치과에 공급.',home_categories:'제품 카테고리',home_contact:'연락처 및 주소',home_address:'태국 방콕',home_hours:'월-금 09:00-18:00',home_line_label:'Line 공식 계정',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    shop_hint:'카테고리를 선택하여 주문하세요',shop_select:'선택 ›',shop_each:'개당',
    order_add_cart:'장바구니 추가',order_qty_error:'수량을 1개 이상 입력해주세요.',
    cart_title:'장바구니',cart_total:'합계',cart_checkout:'결제하기',cart_close:'닫기',cart_empty:'장바구니가 비어 있습니다!',
    addr_title:'배송 정보',addr_clinic_ph:'치과명',addr_phone_ph:'전화번호',addr_addr_ph:'상세 주소',addr_qr_btn:'QR 생성',addr_back:'← 뒤로',addr_fill_error:'배송 정보를 모두 입력해주세요.',
    qr_label:'QR로 결제',qr_summary_title:'주문 요약',qr_total:'합계',qr_complete:'결제 완료',
    used_contact_title:'판매자 연락처',used_contact_close:'닫기',
    custom_tab_new:'새 주문',custom_tab_list:'내 주문 현황',custom_form_title:'커스텀 어버트먼트 주문',custom_delivery_title:'납품 정보',custom_clinic_ph:'치과명 / 기공소명',custom_addr_ph:'납품 주소',custom_phone_ph:'연락처',custom_line_ph:'Line ID (알림 수신용)',custom_submit:'주문 제출하기',custom_submit_note:'주문 접수 시 Line으로 확인 메시지가 발송됩니다',custom_empty:'아직 주문 내역이 없어요',
    case_label:'케이스 #',case_remove:'✕ 삭제',case_patient_ph:'환자 ID (익명 가능, 예: P001)',case_tooth_hint:'치아 선택 · 탭하여 선택/해제',upper_jaw:'상악 (Upper Jaw)',lower_jaw:'하악 (Lower Jaw)',jaw_border:'치열 경계',selected_teeth:'선택된 치아 —',sel_count_suffix:'개',brand_ph:'임플란트 종류 선택',size_ph:'사이즈 (예: Ø4.0 / L10)',color_ph:'치아 색상 (VITA)',case_add:'+ 케이스 추가',stl_label:'STL 파일 업로드',stl_hint:'.stl 파일을 탭하여 선택',memo_ph:'특별 요청사항 (선택)',anon_patient:'익명',
    err_fill_delivery:'치과명, 납품 주소, 연락처를 입력해주세요.',err_select_tooth:'케이스 #%: 치아를 최소 1개 선택해주세요.',err_fill_tooth:'케이스 #% 치아 #%: 임플란트 종류와 사이즈를 입력해주세요.',err_add_case:'케이스를 최소 1개 추가해주세요.',
    order_success_msg:'✅ 주문이 접수되었습니다!\n주문번호: %\n케이스: %개 / 치아: %개',order_success_line:'\nLine으로 확인 메시지를 보내드렸습니다.',
    status_label:'진행 상황',case_detail:'케이스 상세',teeth_count:'개 치아',cases_unit:'개',teeth_total_prefix:'총 ',patient_label:'환자: ',no_tooth_info:'치아 정보 없음',case_nr:'케이스 #',
    used_sell_title:'중고 부품 판매',used_name_ph:'부품명',used_code_ph:'제품 코드',used_price_ph:'가격 (THB)',cond_new:'거의 새것',cond_good:'양호',cond_fair:'보통',used_desc_ph:'상태 설명...',used_contact_ph:'연락처 (Line ID / 전화번호)',used_post_btn:'판매 등록',used_list_title:'판매 중인 중고 부품',used_contact_btn:'연락하기',used_delete_btn:'삭제',used_empty:'아직 등록된 중고 물품이 없어요',used_fill_error:'부품명, 가격, 연락처를 입력해주세요.',
    forum_new_post:'새 글 작성',forum_title_ph:'제목',forum_body_ph:'내용을 작성해주세요...',forum_post_btn:'게시',
    settings_lang:'언어 설정',settings_account:'계정',settings_license:'면허번호:',settings_save_btn:'언어 저장',settings_saved_msg:'언어가 저장되었습니다!',settings_pending:'언어를 선택하고 저장 버튼을 눌러주세요.',
    pe_title:'✏️ 내 정보 수정',pe_subtitle:'수정 가능 항목',pe_email:'이메일',pe_phone:'전화번호',pe_address:'주소',pe_clinic:'치과이름',pe_save:'저장',pe_cancel:'취소',pe_email_ph:'이메일 주소',pe_phone_ph:'전화번호',pe_address_ph:'주소',pe_clinic_ph:'치과이름',
    profile_title:'👤 내 정보',profile_edit_btn:'수정',profile_login_msg:'로그인 후 확인 가능합니다.',profile_saved_msg:'✅ 저장되었습니다!',profile_no_change:'(변경불가)',prof_nickname:'닉네임',prof_doctor:'의사이름',login_required:'로그인이 필요합니다.',
    factory_subtitle:'방콕의 프리미엄 임플란트 제조 센터',
    tooth_11:'중절치',tooth_12:'측절치',tooth_13:'견치',tooth_14:'제1소구치',tooth_15:'제2소구치',tooth_16:'제1대구치',tooth_17:'제2대구치',
    upper:'상악',lower:'하악',
    stage_received:'주문 접수',stage_stl:'STL 검토',stage_design:'디자인 중',stage_cnc:'CNC 생산',stage_qc:'품질 검사',stage_shipping:'배송 중',stage_done:'납품 완료',
  },
  zh: {
    nav_home:'主页',nav_shop:'商城',nav_custom:'定制',nav_used:'二手市场',nav_forum:'论坛',nav_events:'活动',nav_factory:'工厂',nav_settings:'设置',
    pt_home:'主页',pt_shop:'商城',pt_custom:'定制基台',pt_used:'二手市场',pt_forum:'论坛',pt_events:'活动',pt_factory:'工厂',pt_settings:'设置',
    login_subtitle:'医生登录',login_ph:'执照号码',login_btn:'登录',login_cancel:'取消',login_error:'请输入执照号码。',login_verifying:'验证中...',login_not_found:'执照号码未注册或已停用，请联系管理员。',login_network_error:'网络错误，请重试。',login_register_link:'申请使用 →',
    reg_title:'申请使用',reg_subtitle:'填写信息后，管理员将在24小时内审核并联系您。',reg_license_ph:'执照号码（必填）',reg_name_ph:'医生姓名（必填）',reg_clinic_ph:'诊所名称（必填）',reg_contact_ph:'电话或 Line ID（必填）',reg_submit:'提交申请',reg_submitting:'提交中...',reg_success:'申请已提交！\n审核通过后将在24小时内与您联系。',reg_error:'请填写所有必填项。',reg_duplicate:'该执照号码已被注册。',reg_network_error:'网络错误，请重试。',
    session_title:'会话即将过期',session_desc1:'登录将在',session_desc2:'后过期。',session_q:'是否现在延长？',session_extend:'延长30分钟',session_later:'稍后',session_expired:'会话已过期，请重新登录。',
    side_remain:'剩余时间：',side_login_btn:'医生登录',side_logged_label:'已登录',side_logout:'退出登录',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'数字种植体零件',home_title2:'订购系统',home_desc:'将优质BIOTEM种植体配件直接提供给泰国各地牙科诊所。',home_goto_shop:'前往商城',home_about:'关于我们',home_biotem_desc:'韩国牙科种植体制造商，专注于尖端数字化工作流解决方案。',home_bioplant_desc:'曼谷高端牙科配件制造中心，服务东南亚各地诊所。',home_categories:'产品类别',home_contact:'联系方式与地址',home_address:'泰国曼谷',home_hours:'周一至周五 09:00-18:00',home_line_label:'Line 官方账号',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    shop_hint:'请选择类别进行订购',shop_select:'选择 ›',shop_each:'件',
    order_add_cart:'加入购物车',order_qty_error:'请输入至少1件数量。',
    cart_title:'购物车',cart_total:'合计',cart_checkout:'结账',cart_close:'关闭',cart_empty:'购物车为空！',
    addr_title:'配送信息',addr_clinic_ph:'诊所名称',addr_phone_ph:'电话号码',addr_addr_ph:'详细地址',addr_qr_btn:'生成二维码',addr_back:'← 返回',addr_fill_error:'请填写所有配送信息。',
    qr_label:'扫码支付',qr_summary_title:'订单摘要',qr_total:'合计',qr_complete:'支付完成',
    used_contact_title:'联系卖家',used_contact_close:'关闭',
    custom_tab_new:'新订单',custom_tab_list:'我的订单',custom_form_title:'定制基台订单',custom_delivery_title:'配送信息',custom_clinic_ph:'诊所/技工所名称',custom_addr_ph:'配送地址',custom_phone_ph:'联系电话',custom_line_ph:'Line ID（接收通知）',custom_submit:'提交订单',custom_submit_note:'订单提交后将通过Line发送确认消息',custom_empty:'暂无订单记录',
    case_label:'病例 #',case_remove:'✕ 删除',case_patient_ph:'患者ID（可匿名，如：P001）',case_tooth_hint:'选择牙齿 · 点击切换',upper_jaw:'上颌 (Upper Jaw)',lower_jaw:'下颌 (Lower Jaw)',jaw_border:'牙弓分界',selected_teeth:'已选牙齿 —',sel_count_suffix:'颗',brand_ph:'选择种植体品牌',size_ph:'尺寸（如：Ø4.0 / L10）',color_ph:'牙色（VITA）',case_add:'+ 添加病例',stl_label:'上传STL文件',stl_hint:'点击选择.stl文件',memo_ph:'特殊要求（选填）',anon_patient:'匿名',
    err_fill_delivery:'请填写诊所名称、地址和联系电话。',err_select_tooth:'病例#%：请至少选择1颗牙齿。',err_fill_tooth:'病例#% 牙齿#%：请填写种植体品牌和尺寸。',err_add_case:'请至少添加1个病例。',
    order_success_msg:'✅ 订单已提交！\n订单号：%\n病例：%个 / 牙齿：%颗',order_success_line:'\n确认消息已通过Line发送。',
    status_label:'进度',case_detail:'病例详情',teeth_count:'颗牙',cases_unit:'个',teeth_total_prefix:'共',patient_label:'患者：',no_tooth_info:'（无牙齿信息）',case_nr:'病例 #',
    used_sell_title:'出售二手零件',used_name_ph:'零件名称',used_code_ph:'产品编码',used_price_ph:'价格（泰铢）',cond_new:'近全新',cond_good:'良好',cond_fair:'一般',used_desc_ph:'状况描述...',used_contact_ph:'联系方式（Line ID / 电话）',used_post_btn:'发布出售',used_list_title:'可购二手零件',used_contact_btn:'联系',used_delete_btn:'删除',used_empty:'暂无二手零件',used_fill_error:'请填写零件名称、价格和联系方式。',
    forum_new_post:'发布新帖',forum_title_ph:'标题',forum_body_ph:'写下您的内容...',forum_post_btn:'发布',
    settings_lang:'语言设置',settings_account:'账户',settings_license:'执照号：',settings_save_btn:'保存语言',settings_saved_msg:'语言已保存！',settings_pending:'请选择语言后点击保存。',
    pe_title:'✏️ 编辑我的信息',pe_subtitle:'可修改项目',pe_email:'电子邮件',pe_phone:'电话号码',pe_address:'地址',pe_clinic:'诊所名称',pe_save:'保存',pe_cancel:'取消',pe_email_ph:'电子邮件地址',pe_phone_ph:'电话号码',pe_address_ph:'地址',pe_clinic_ph:'诊所名称',
    profile_title:'👤 我的信息',profile_edit_btn:'编辑',profile_login_msg:'请登录后查看。',profile_saved_msg:'✅ 已保存！',profile_no_change:'(不可更改)',prof_nickname:'昵称',prof_doctor:'医生姓名',login_required:'需要登录。',
    factory_subtitle:'曼谷高端种植体制造中心',
    tooth_11:'中切牙',tooth_12:'侧切牙',tooth_13:'尖牙',tooth_14:'第一前磨牙',tooth_15:'第二前磨牙',tooth_16:'第一磨牙',tooth_17:'第二磨牙',
    upper:'上颌',lower:'下颌',
    stage_received:'已接收订单',stage_stl:'STL审核',stage_design:'设计中',stage_cnc:'CNC生产',stage_qc:'质量检验',stage_shipping:'配送中',stage_done:'已交付',
  },
  th: {
    nav_home:'หน้าแรก',nav_shop:'ร้านค้า',nav_custom:'กำหนดเอง',nav_used:'ตลาดมือสอง',nav_forum:'ฟอรัม',nav_events:'กิจกรรม',nav_factory:'โรงงาน',nav_settings:'ตั้งค่า',
    pt_home:'หน้าแรก',pt_shop:'ร้านค้า',pt_custom:'Custom Abutment',pt_used:'ตลาดมือสอง',pt_forum:'ฟอรัม',pt_events:'กิจกรรม',pt_factory:'โรงงาน',pt_settings:'ตั้งค่า',
    login_subtitle:'เข้าสู่ระบบทันตแพทย์',login_ph:'หมายเลขใบอนุญาต',login_btn:'เข้าสู่ระบบ',login_cancel:'ยกเลิก',login_error:'กรุณาใส่หมายเลขใบอนุญาต',login_verifying:'กำลังตรวจสอบ...',login_not_found:'ไม่พบหมายเลขใบอนุญาต หรือถูกระงับการใช้งาน กรุณาติดต่อผู้ดูแล',login_network_error:'เกิดข้อผิดพลาดเครือข่าย กรุณาลองใหม่อีกครั้ง',login_register_link:'ขอสิทธิ์เข้าใช้งาน →',
    reg_title:'ขอสิทธิ์เข้าใช้งาน',reg_subtitle:'กรอกข้อมูลแล้วผู้ดูแลจะตรวจสอบและติดต่อกลับภายใน 24 ชั่วโมง',reg_license_ph:'หมายเลขใบอนุญาต (จำเป็น)',reg_name_ph:'ชื่อทันตแพทย์ (จำเป็น)',reg_clinic_ph:'ชื่อคลินิก (จำเป็น)',reg_contact_ph:'โทรศัพท์ หรือ Line ID (จำเป็น)',reg_submit:'ส่งคำขอ',reg_submitting:'กำลังส่ง...',reg_success:'ส่งคำขอเรียบร้อย!\nเราจะติดต่อกลับภายใน 24 ชั่วโมงหลังการอนุมัติ',reg_error:'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน',reg_duplicate:'หมายเลขใบอนุญาตนี้ถูกลงทะเบียนแล้ว',reg_network_error:'เกิดข้อผิดพลาดเครือข่าย กรุณาลองใหม่อีกครั้ง',
    session_title:'เซสชันใกล้หมดอายุ',session_desc1:'การเข้าสู่ระบบจะหมดอายุใน',session_desc2:'',session_q:'ต้องการต่ออายุเซสชันหรือไม่?',session_extend:'ต่ออายุ 30 นาที',session_later:'ภายหลัง',session_expired:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
    side_remain:'เวลาที่เหลือ:',side_login_btn:'เข้าสู่ระบบทันตแพทย์',side_logged_label:'เข้าสู่ระบบแล้ว',side_logout:'ออกจากระบบ',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'ชิ้นส่วน Implant ดิจิทัล',home_title2:'ระบบสั่งซื้อ',home_desc:'จัดหาชิ้นส่วน BIOTEM Implant คุณภาพสูงโดยตรงให้กับคลินิกทันตกรรมทั่วประเทศไทย',home_goto_shop:'ไปที่ร้านค้า',home_about:'เกี่ยวกับเรา',home_biotem_desc:'ผู้ผลิต Implant ทันตกรรมจากเกาหลี ผู้เชี่ยวชาญด้าน Implant ด้วยโซลูชันดิจิทัลล้ำสมัย',home_bioplant_desc:'ศูนย์ผลิต Fixture ทันตกรรมระดับพรีเมียมในกรุงเทพฯ จัดหาให้กับคลินิกทั่วเอเชียตะวันออกเฉียงใต้',home_categories:'หมวดหมู่สินค้า',home_contact:'ติดต่อและที่อยู่',home_address:'กรุงเทพมหานคร ประเทศไทย',home_hours:'จันทร์-ศุกร์ 09:00-18:00',home_line_label:'Line Official',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    shop_hint:'เลือกหมวดหมู่เพื่อสั่งซื้อ',shop_select:'เลือก ›',shop_each:'ชิ้น',
    order_add_cart:'เพิ่มในรถเข็น',order_qty_error:'กรุณาระบุจำนวนอย่างน้อย 1 ชิ้น',
    cart_title:'รถเข็น',cart_total:'ยอดรวม',cart_checkout:'ชำระเงิน',cart_close:'ปิด',cart_empty:'รถเข็นว่างเปล่า!',
    addr_title:'ข้อมูลจัดส่ง',addr_clinic_ph:'ชื่อคลินิก',addr_phone_ph:'หมายเลขโทรศัพท์',addr_addr_ph:'ที่อยู่',addr_qr_btn:'สร้าง QR Code',addr_back:'← กลับ',addr_fill_error:'กรุณากรอกข้อมูลจัดส่งให้ครบถ้วน',
    qr_label:'สแกนเพื่อชำระเงิน',qr_summary_title:'สรุปคำสั่งซื้อ',qr_total:'ยอดรวม',qr_complete:'ชำระเงินเรียบร้อย',
    used_contact_title:'ติดต่อผู้ขาย',used_contact_close:'ปิด',
    custom_tab_new:'สั่งใหม่',custom_tab_list:'คำสั่งซื้อของฉัน',custom_form_title:'สั่งซื้อ Custom Abutment',custom_delivery_title:'ข้อมูลจัดส่ง',custom_clinic_ph:'ชื่อคลินิก / ห้องแล็บ',custom_addr_ph:'ที่อยู่จัดส่ง',custom_phone_ph:'เบอร์ติดต่อ',custom_line_ph:'Line ID (สำหรับรับการแจ้งเตือน)',custom_submit:'ส่งคำสั่งซื้อ',custom_submit_note:'เมื่อได้รับคำสั่งซื้อจะส่งข้อความยืนยันทาง Line',custom_empty:'ยังไม่มีคำสั่งซื้อ',
    case_label:'เคส #',case_remove:'✕ ลบ',case_patient_ph:'ID ผู้ป่วย (ไม่ระบุชื่อได้ เช่น P001)',case_tooth_hint:'เลือกฟัน · แตะเพื่อเลือก/ยกเลิก',upper_jaw:'ขากรรไกรบน (Upper Jaw)',lower_jaw:'ขากรรไกรล่าง (Lower Jaw)',jaw_border:'แนวขอบ',selected_teeth:'ฟันที่เลือก —',sel_count_suffix:' ซี่',brand_ph:'เลือกยี่ห้อ Implant',size_ph:'ขนาด (เช่น Ø4.0 / L10)',color_ph:'สีฟัน (VITA)',case_add:'+ เพิ่มเคส',stl_label:'อัปโหลดไฟล์ STL',stl_hint:'แตะเพื่อเลือกไฟล์ .stl',memo_ph:'คำขอพิเศษ (ไม่บังคับ)',anon_patient:'ไม่ระบุ',
    err_fill_delivery:'กรุณากรอกชื่อคลินิก ที่อยู่ และเบอร์ติดต่อ',err_select_tooth:'เคส #%: กรุณาเลือกอย่างน้อย 1 ซี่ฟัน',err_fill_tooth:'เคส #% ฟัน #%: กรุณากรอกยี่ห้อและขนาด Implant',err_add_case:'กรุณาเพิ่มอย่างน้อย 1 เคส',
    order_success_msg:'✅ ส่งคำสั่งซื้อเรียบร้อย!\nหมายเลขคำสั่งซื้อ: %\nเคส: % / ฟัน: % ซี่',order_success_line:'\nส่งข้อความยืนยันทาง Line แล้ว',
    status_label:'สถานะ',case_detail:'รายละเอียดเคส',teeth_count:' ซี่ฟัน',cases_unit:' เคส',teeth_total_prefix:'รวม ',patient_label:'ผู้ป่วย: ',no_tooth_info:'(ไม่มีข้อมูลฟัน)',case_nr:'เคส #',
    used_sell_title:'ขายอะไหล่มือสอง',used_name_ph:'ชื่อชิ้นส่วน',used_code_ph:'รหัสสินค้า',used_price_ph:'ราคา (บาท)',cond_new:'เหมือนใหม่',cond_good:'ดี',cond_fair:'พอใช้',used_desc_ph:'รายละเอียดสภาพ...',used_contact_ph:'ช่องทางติดต่อ (Line ID / โทรศัพท์)',used_post_btn:'ลงประกาศขาย',used_list_title:'อะไหล่มือสองที่มีจำหน่าย',used_contact_btn:'ติดต่อ',used_delete_btn:'ลบ',used_empty:'ยังไม่มีอะไหล่มือสอง',used_fill_error:'กรุณากรอกชื่อชิ้นส่วน ราคา และช่องทางติดต่อ',
    forum_new_post:'โพสต์ใหม่',forum_title_ph:'หัวข้อ',forum_body_ph:'เขียนข้อความ...',forum_post_btn:'โพสต์',
    settings_lang:'ภาษา',settings_account:'บัญชี',settings_license:'ใบอนุญาต:',settings_save_btn:'บันทึกภาษา',settings_saved_msg:'บันทึกภาษาแล้ว!',settings_pending:'เลือกภาษาแล้วกด บันทึก',
    pe_title:'✏️ แก้ไขข้อมูลของฉัน',pe_subtitle:'รายการที่แก้ไขได้',pe_email:'อีเมล',pe_phone:'หมายเลขโทรศัพท์',pe_address:'ที่อยู่',pe_clinic:'ชื่อคลินิก',pe_save:'บันทึก',pe_cancel:'ยกเลิก',pe_email_ph:'ที่อยู่อีเมล',pe_phone_ph:'หมายเลขโทรศัพท์',pe_address_ph:'ที่อยู่',pe_clinic_ph:'ชื่อคลินิก',
    profile_title:'👤 ข้อมูลของฉัน',profile_edit_btn:'แก้ไข',profile_login_msg:'กรุณาเข้าสู่ระบบเพื่อดูข้อมูล',profile_saved_msg:'✅ บันทึกแล้ว!',profile_no_change:'(เปลี่ยนไม่ได้)',prof_nickname:'ชื่อเล่น',prof_doctor:'ชื่อแพทย์',login_required:'กรุณาเข้าสู่ระบบ',
    factory_subtitle:'ศูนย์ผลิต Fixture ระดับพรีเมียมในกรุงเทพฯ',
    tooth_11:'ฟันตัดกลาง',tooth_12:'ฟันตัดข้าง',tooth_13:'ฟันเขี้ยว',tooth_14:'ฟันกรามน้อยซี่ที่ 1',tooth_15:'ฟันกรามน้อยซี่ที่ 2',tooth_16:'ฟันกรามซี่ที่ 1',tooth_17:'ฟันกรามซี่ที่ 2',
    upper:'ขากรรไกรบน',lower:'ขากรรไกรล่าง',
    stage_received:'รับคำสั่งซื้อแล้ว',stage_stl:'ตรวจสอบ STL',stage_design:'กำลังออกแบบ',stage_cnc:'ผลิต CNC',stage_qc:'ตรวจสอบคุณภาพ',stage_shipping:'กำลังจัดส่ง',stage_done:'จัดส่งแล้ว',
  },
};

function t(key) { return (LANG[currentLang] || LANG.en)[key] || key; }
function tf(key) {
  var s = t(key);
  for (var i = 1; i < arguments.length; i++) s = s.replace('%', String(arguments[i]));
  return s;
}
