// Dentalk i18n - Chinese
window.LANG = window.LANG || {};
LANG.zh = {
    nav_home:'主页',nav_shop:'商城',nav_custom:'CNC Custom Abut',nav_used:'二手市场',nav_forum:'临床讨论',nav_events:'活动',nav_factory:'工厂',nav_settings:'设置',nav_login:'登录',privacy_btn:'隐私政策',
    hdr_search:'搜索',hdr_notif:'通知',hdr_install:'安装',hdr_cart:'购物车',hdr_login:'登录',hdr_logout:'退出',
    loading_text:'加载中...',settings_darkmode:'深色模式',settings_darkmode_desc:'切换到深色主题',
    footer_links:'快速链接',footer_connect:'联系我们',footer_copyright:'© 2026 Dentalk · BIOTEM × BIOPLANT. 版权所有。',footer_address:'曼谷，泰国',
    pt_home:'主页',pt_shop:'商城',pt_custom:'定制基台',pt_used:'二手市场',pt_forum:'临床讨论',pt_events:'活动',pt_factory:'工厂',pt_settings:'设置',
    login_subtitle:'医生登录',login_ph:'昵称',login_password_ph:'密码',login_btn:'登录',login_cancel:'取消',login_error:'请输入昵称和密码。',login_verifying:'验证中...',login_not_found:'昵称不存在或密码错误。',login_network_error:'网络错误，请重试。',login_register_link:'申请使用 →',find_id:'找回ID',find_pw:'重置密码',find_id_ph:'手机号或昵称',find_pw_ph:'您的邮箱',find_id_btn:'查找ID',find_pw_btn:'发送重置请求',find_id_result:'您的邮箱是：',find_pw_sent:'密码重置请求已发送。管理员将联系您。',find_not_found:'未找到账户。',find_back:'← 返回登录',
    reg_title:'申请使用',reg_subtitle:'填写信息后，管理员将在24小时内审核并联系您。',reg_license_ph:'执照号码（必填）',reg_name_ph:'医生姓名（必填）',reg_clinic_ph:'诊所名称（必填）',reg_contact_ph:'电话或 Line ID（必填）',reg_tax_id:'税号',reg_tax_id_ph:'税号 / 营业执照号 (选填)',reg_password_ph:'密码（必填）',reg_password_confirm_ph:'确认密码（必填）',reg_submit:'提交申请',reg_submitting:'提交中...',reg_success:'申请已提交！\n审核通过后将在24小时内与您联系。',reg_error:'请填写所有必填项。',reg_pwd_mismatch:'两次密码不一致。',reg_duplicate:'该昵称已被注册。',reg_network_error:'网络错误，请重试。',
    session_title:'会话即将过期',session_desc1:'登录将在',session_desc2:'后过期。',session_q:'是否现在延长？',session_extend:'延长30分钟',session_later:'稍后',session_expired:'会话已过期，请重新登录。',
    side_remain:'剩余时间：',side_login_btn:'医生登录',side_logged_label:'已登录',side_logout:'退出登录',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'数字种植体零件',home_title2:'订购系统',home_desc:'将优质BIOTEM种植体配件直接提供给泰国各地牙科诊所。',home_goto_shop:'前往商城',home_line_add:'添加LINE好友',
    home_vision_label:'我们的愿景',home_vision:'重新定义东南亚种植精准标准',home_stat1:'已认证',home_stat2:'原产地',home_stat3:'覆盖范围',home_biotem_short:'种植专家 · 韩国',home_bioplant_short:'制造中心 · 曼谷',home_mission_label:'使命',home_mission:'将韩国制造的优质牙科种植配件以快速可靠的服务输送至泰国及东南亚各地诊所。',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    home_about:'关于我们',home_biotem_desc:'韩国牙科种植体制造商，专注于尖端数字化工作流解决方案。',home_bioplant_desc:'曼谷高端牙科配件制造中心，服务东南亚各地诊所。',home_categories:'产品类别',home_contact:'联系方式与地址',home_address:'泰国曼谷',home_hours:'周一至周五 09:00–18:00',home_line_label:'Line 官方账号',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'优质牙科种植体配件',hero_bioplant_desc:'韩国ISO认证制造，快速配送至您的诊所',hero_bioplant_cta:'立即购买',
    hero_cnc_tag:'CNC定制基台',hero_cnc_title:'精密定制解决方案',hero_cnc_desc:'从扫描体到最终修复，按您规格制造',hero_cnc_cta:'定制订购',hero_feat1_title:'患者定制',hero_feat1_desc:'使用CAD/CAM个性化设计理想牙形',hero_feat2_title:'可调边缘',hero_feat2_desc:'精确控制粘接线以实现最佳生物学宽度',hero_feat3_title:'完美贴合',hero_feat3_desc:'CNC铣削精密贴合解剖轮廓',hero_feat4_title:'性价比高',hero_feat4_desc:'信用系统以有竞争力的价格提供高品质结果',
    sec_categories:'产品类别',sec_see_more:'查看全部 ›',cat_scan_body_desc:'口内 & 模型型',cat_q_base_desc:'氧化锦基台 H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'铣切兼容 · N & R',cat_multi_unit_desc:'All-on-X · MUA · 扫描体',cat_3d_analog_desc:'石膏 & 3D打印模型',
    sec_forum_preview:'临床讨论',sec_forum_more:'查看全部 ›',home_forum_empty:'暂无帖子，快来发帖吧！',
    sec_events_preview:'近期活动',sec_events_more:'查看全部 ›',home_events_empty:'暂无近期活动',
    sec_webzine:'网络杂志',sec_webzine_sub:'临床案例 & 产品更新',sec_webzine_coming:'即将推出，敬请期待',ad_label:'广告',
    admin_tab_ads:'广告管理',admin_ads_summary_active:'活跃横幅',admin_ads_summary_clicks:'今日点击',admin_ads_summary_impressions:'今日展示',admin_ads_summary_ctr:'平均CTR',
    admin_ads_form_title:'注册横幅',admin_ads_advertiser:'广告主',admin_ads_advertiser_ph:'广告主名称',admin_ads_image:'图片',admin_ads_image_upload:'点击上传图片',admin_ads_link:'链接URL',admin_ads_link_ph:'https://',admin_ads_position:'位置',admin_ads_start:'开始日期',admin_ads_end:'结束日期',admin_ads_submit:'注册',admin_ads_fill_alert:'请填写广告主、图片和位置。',
    admin_ads_list_title:'横幅列表',admin_ads_col_advertiser:'广告主',admin_ads_col_position:'位置',admin_ads_col_period:'期间',admin_ads_col_clicks:'点击数',admin_ads_col_impressions:'展示数',admin_ads_col_ctr:'CTR',admin_ads_col_status:'状态',admin_ads_col_actions:'操作',admin_ads_active:'活跃',admin_ads_inactive:'停用',admin_ads_edit:'编辑',admin_ads_delete:'删除',admin_ads_delete_confirm:'确定删除此横幅？',admin_ads_empty:'暂无横幅。',admin_ads_save:'保存',admin_ads_cancel:'取消',admin_ads_editing:'编辑横幅',admin_ads_update_success:'横幅已更新。',admin_ads_image_change:'更换图片',
    nav_webzine:'杂志',wz_cat_all:'全部',wz_cat_implant:'种植案例',wz_cat_prosthetic:'修复案例',wz_cat_review:'产品评测',wz_cat_news:'行业新闻',wz_cat_education:'教育内容',
    wz_empty:'暂无文章。',wz_home_empty:'文章即将推出',wz_write_btn:'撰写文章',wz_form_title:'新文章',wz_title_ph:'文章标题',wz_thumb_ph:'点击上传封面图',wz_body_ph:'撰写文章内容（支持Markdown）',wz_submit_btn:'发布',wz_fill_alert:'请填写标题和正文。',wz_delete_confirm:'确定要删除这篇文章吗？',
    nav_jobs:'招聘',job_type_all:'全部',job_type_dentist:'牙医招聘',job_type_staff:'员工招聘',job_type_equipment:'设备转让',
    job_empty:'暂无招聘信息。',job_write_btn:'发布招聘',job_form_title:'新招聘帖',job_title_ph:'标题',job_desc_ph:'详细描述',job_salary_ph:'薪资范围',job_req_ph:'要求（可选）',job_contact_ph:'联系方式（电话、邮箱、LINE）',job_province_ph:'选择省份',job_submit_btn:'发布',job_fill_alert:'请填写标题和描述。',job_delete_confirm:'确定删除此招聘信息？',job_delete_btn:'删除',
    job_salary:'薪资',job_desc:'描述',job_requirements:'要求',job_contact:'联系方式',
    shop_hint:'请选择类别进行订购',shop_catalog_title:'📋 产品目录',shop_catalog_download:'下载 PDF',shop_select:'选择 ›',shop_each:'件',
    order_add_cart:'加入购物车',order_qty_error:'请输入至少1件数量。',
    cart_title:'购物车',cart_total:'合计',cart_checkout:'结账',cart_close:'关闭',cart_empty:'购物车为空！',
    shop_specs:'规格及数量',shop_in_stock:'有货',shop_out_of_stock:'缺货',shop_my_orders:'我的订单',shop_product_count:'款产品',cart_bar_tap:'点击查看购物车',cart_bar_items:'件',cart_added:'已加入购物车!',
    addr_title:'配送信息',addr_clinic_ph:'诊所名称',addr_phone_ph:'电话号码',addr_addr_ph:'详细地址',addr_qr_btn:'生成二维码',addr_back:'← 返回',addr_fill_error:'请填写所有配送信息。',
    qr_label:'扫码支付',qr_summary_title:'订单摘要',qr_total:'合计',qr_complete:'支付完成',
    used_contact_title:'联系卖家',used_contact_close:'关闭',
    custom_tab_new:'新订单',custom_form_title:'定制基台订单',custom_delivery_title:'配送信息',custom_clinic_ph:'诊所/技工所名称',custom_addr_ph:'配送地址',custom_phone_ph:'联系电话',custom_line_ph:'Line ID（接收通知）',custom_submit:'提交订单',custom_submit_note:'订单提交后将通过Line发送确认消息',custom_empty:'暂无订单记录',
    case_label:'病例 #',case_remove:'✕ 删除',case_patient_ph:'患者ID（可匿名，如：P001）',case_tooth_hint:'选择牙齿 · 点击切换',upper_jaw:'上颌 (Upper Jaw)',lower_jaw:'下颌 (Lower Jaw)',jaw_border:'牙弓分界',selected_teeth:'已选牙齿 —',sel_count_suffix:'颗',brand_ph:'选择种植体品牌',size_ph:'尺寸（如：Ø4.0 / L10）',color_ph:'牙色（VITA）',case_add:'+ 添加病例',stl_label:'上传STL文件（最多10个）',stl_hint:'可同时选择多个.stl文件',memo_ph:'特殊要求（选填）',anon_patient:'匿名',case_deadline_label:'交货期限',cnc_date_ph:'年-月-日',
    err_fill_delivery:'请填写诊所名称、地址和联系电话。',err_select_tooth:'病例#%：请至少选择1颗牙齿。',err_fill_tooth:'病例#% 牙齿#%：请填写种植体品牌和尺寸。',err_add_case:'请至少添加1个病例。',
    order_success_msg:'✅ 订单已提交！\n订单号：%\n病例：%个 / 牙齿：%颗',order_success_line:'\n确认消息已通过Line发送。',
    status_label:'进度',case_detail:'病例详情',teeth_count:'颗牙',cases_unit:'个',teeth_total_prefix:'共',patient_label:'患者：',no_tooth_info:'（无牙齿信息）',case_nr:'病例 #',
    used_sell_title:'出售二手零件',used_name_ph:'零件名称',used_code_ph:'产品编码',used_price_ph:'价格（泰铢）',cond_new:'近全新',cond_good:'良好',cond_fair:'一般',used_desc_ph:'状况描述...',used_contact_ph:'联系方式（Line ID / 电话）',used_post_btn:'发布出售',used_list_title:'可购二手零件',used_contact_btn:'联系',used_delete_btn:'删除',used_empty:'暂无二手零件',used_fill_error:'请填写零件名称、价格和联系方式。',used_no_photo:'无照片',
    forum_new_post:'发布新帖',forum_title_ph:'标题',forum_body_ph:'写下您的内容...',forum_post_btn:'发布',
    settings_lang:'语言设置',settings_account:'账户',settings_license:'执照号：',settings_save_btn:'保存语言',settings_saved_msg:'语言已保存！',settings_pending:'请选择语言后点击保存。',
    pe_title:'✏️ 编辑我的信息',pe_subtitle:'可修改项目',pe_email:'电子邮件',pe_phone:'电话号码',pe_address:'地址',pe_clinic:'诊所名称',pe_save:'保存',pe_cancel:'取消',pe_email_ph:'电子邮件地址',pe_phone_ph:'电话号码',pe_address_ph:'地址',pe_clinic_ph:'诊所名称',
    profile_title:'👤 我的信息',profile_edit_btn:'编辑',profile_login_msg:'请登录后查看。',profile_saved_msg:'✅ 已保存！',profile_no_change:'(不可更改)',prof_nickname:'昵称',prof_doctor:'医生姓名',login_required:'需要登录。',
    factory_subtitle:'曼谷高端种植体制造中心',
    tooth_11:'中切牙',tooth_12:'侧切牙',tooth_13:'尖牙',tooth_14:'第一前磨牙',tooth_15:'第二前磨牙',tooth_16:'第一磨牙',tooth_17:'第二磨牙',
    upper:'上颌',lower:'下颌',
    stage_received:'已接收订单',stage_stl:'STL审核',stage_design:'设计中',stage_cnc:'CNC生产',stage_qc:'质量检验',stage_shipping:'配送中',stage_done:'已交付',stage_submitted:'待确认',stage_confirmed:'已确认',stage_design_ready:'设计审核',stage_design_revision:'设计修改中',stage_approved:'已批准',stage_milling:'CNC加工中',stage_shipped:'已发货',
    line_deadline:'期限',line_memo:'备注',line_total_cases:'共 %个病例 / %颗牙',
    reg_privacy_agree_prefix:'我已阅读并同意',reg_privacy_link:'隐私政策',reg_privacy_agree_suffix:'（泰国PDPA）。',reg_privacy_error:'请阅读并同意隐私政策后继续。',
    privacy_title:'隐私政策',privacy_close:'关闭',
    used_photo_add:'添加照片',shop_items:'件',
    forum_cat_implant:'🦷 种植',forum_cat_prosthetic:'💎 修复',forum_cat_conservative:'🪥 牙体牙髓',forum_cat_orthodontics:'🦷 正畸',forum_cat_oral_surgery:'✂️ 口腔外科',forum_cat_periodontics:'🌿 牙周',forum_cat_pediatric:'👶 儿童口腔',forum_cat_radiology:'📷 口腔影像',forum_cat_oral_medicine:'💊 口腔内科',forum_cat_preventive:'🛡 预防',forum_cat_general:'🏥 综合诊疗',forum_photo_add:'📷 添加照片（最多5张）',forum_empty:'暂无帖子。',
    forum_write_btn:'✍️ 发帖',forum_close_form:'✕ 关闭',forum_cat_label:'分类',
    forum_region_label:'地区',forum_province_label:'府',
    forum_region_all:'🌏 全部',forum_region_north:'🏔 北部',forum_region_northeast:'🌾 东北部',forum_region_east:'🌊 东部',forum_region_south:'🏝 南部',forum_region_central:'🏙 中部',
    forum_comment_title:'💬 评论',forum_comment_ph:'写评论...',forum_comment_submit:'提交',forum_no_comments:'暂无评论。',forum_writing_as:'以...发布',
    custom_tab_list:'进行中',custom_tab_done:'已完成',
    install_ios:'📱 <b>iPhone / Safari 安装方法</b><br><br>① 点击底部分享按钮 <b>□↑</b><br>② 选择 <b>"添加到主屏幕"</b><br>③ 点击 <b>"添加"</b>',
    install_android:'💻 <b>PC / Android 安装方法</b><br><br>① 点击浏览器地址栏右侧的<br>&nbsp;&nbsp;&nbsp;<b>安装图标 ⊕</b><br>② 点击 <b>"安装"</b><br><br>※ 若无图标，打开浏览器菜单<br>&nbsp;&nbsp;&nbsp;→ "安装为应用"',
    design_waiting:'⏳ 等待设计文件上传...',shipped_msg:'🚚 您的订单已发货。收到后请按下方按钮。',receive_btn:'📦 确认收货',
    edit_order_btn:'✏️ 编辑',delete_order_btn:'🗑 删除',review_history_label:'审核历史（%次）',
    done_orders_empty:'暂无已完成订单。',done_status_label:'已完成',done_cases_teeth_fmt:'%个病例 · %颗牙',
    reg_nick_ph:'昵称（必填）— 用于所有活动',reg_email_ph:'电子邮件地址（必填）',
    compose_title:'✉️ 发送消息',compose_to_ph:'收件人（昵称）',compose_subj_ph:'主题',compose_body_ph:'写下您的内容...',compose_send:'发送',
    ship_carrier_custom_opt:'手动输入',ship_carrier_ph:'快递公司名称',ship_tracking_label:'快递单号',ship_tracking_ph:'输入快递单号',ship_process_btn:'🚚 处理发货 → 发送LINE',
    leader_badge:'区域负责人',leader_assign:'指定',leader_remove:'撤销负责人',leader_select_region:'选择区域...',leader_select_level:'选择级别...',leader_select_province:'选择府...',leader_select_title:'选择职位...',leader_level_all:'泰国（全国）',leader_level_region:'区域负责人',leader_level_province:'府负责人',leader_title_occupied:'该职位已被分配。',title_president:'会长',title_vice_president:'副会长',title_secretary:'秘书长',title_director:'理事',title_auditor:'监事',title_representative:'代表',
    forum_pinned:'已置顶',forum_pin:'置顶',forum_unpin:'取消置顶',forum_delete:'删除',forum_delete_confirm:'确定要删除此帖子吗？',event_delete_confirm:'确定要删除此活动吗？',
    admin_new_event_title:'添加新活动',admin_event_name_ph:'活动名称',admin_event_loc_ph:'地点',admin_event_add_btn:'+ 添加',admin_event_fill_alert:'请填写所有项目。',
    meetup_create_btn:'创建聚会',meetup_badge:'聚会',event_badge:'活动',meetup_form_title:'创建新聚会',meetup_title_ph:'聚会标题',meetup_loc_ph:'地点',meetup_desc_ph:'描述（可选）',meetup_submit_btn:'创建聚会',meetup_fill_alert:'请填写标题、日期和地点。',meetup_created_by:'创建者',
    rsvp_title:'参加确认',rsvp_attend:'✅ 参加',rsvp_not_attend:'❌ 不参加',rsvp_attendees:'人参加',rsvp_attendee_list:'参加者名单',rsvp_no_attendees:'暂无参加者。',rsvp_login_required:'请登录后确认参加。',rsvp_error:'参加确认失败，请重试。',
    admin_orders_new:'新订单',admin_orders_active:'进行中',admin_orders_done:'已完成',admin_orders_empty:'暂无订单。',
    shipped_status:'已发货',carrier_label:'快递公司',tracking_label:'快递单',received_status:'已收货',teeth_colon_label:'牙齿:',
    wiz_step1:'患者与牙位',wiz_step2:'品牌',wiz_step3:'色号与备注',wiz_step4:'STL文件',wiz_step5:'确认提交',wiz_next:'下一步 →',wiz_prev:'← 上一步',wiz_patient_label:'患者ID',wiz_no_tooth_err:'请至少选择1颗牙位。',wiz_no_brand_err:'请选择种植体品牌。',wiz_brand_all_hint:'适用于所有已选牙位',wiz_size_for_tooth:'尺寸（例：Ø4.0 / L10）',wiz_shade_label:'牙齿色号（VITA）',wiz_stl_main_label:'STL / 3D文件',wiz_stl_main_hint:'拖拽或点击选择 · 最多10个文件',wiz_confirm_title:'订单确认',wiz_delivery_label:'配送信息',wiz_teeth_selected:'颗牙位已选',wiz_start_over:'新建订单',wiz_size_table_title:'各牙位尺寸',
    used_post_toggle:'📸 发布二手物品',used_close_form:'✕ 关闭',settings_my_orders:'📦 我的订单',settings_no_orders:'暂无订单记录',
    admin_panel_title:'管理员面板',admin_total_members:'总会员数',admin_pending_orders:'待处理订单',admin_today_signups:'今日新注册',
    admin_tab_orders:'订单管理',admin_tab_users:'会员管理',admin_tab_custom:'定制订单',
    admin_order_date:'日期',admin_order_customer:'客户名',admin_order_total:'总额',admin_order_status:'状态',admin_change_status:'更改状态',
    admin_user_approve:'✅ 批准',admin_user_reject:'❌ 拒绝',admin_user_block:'🔒 封禁',admin_user_unblock:'✅ 解封',
    admin_user_pending_badge:'待审核',admin_user_active_badge:'活跃',admin_user_blocked_badge:'已封禁',
    admin_custom_change_stage:'更改阶段',admin_pending_users_title:'⏳ 待审核会员',admin_all_users_title:'👥 全部会员',
    admin_no_pending_users:'没有待审核的会员。',admin_loading:'加载中...',admin_load_fail:'加载失败',admin_no_users:'没有会员。',admin_error:'发生错误。',
    search_ph:'搜索...',search_hint:'输入关键词搜索',search_searching:'搜索中...',search_no_results:'未找到结果。',search_error:'搜索失败，请重试。',
    notif_title:'通知',notif_empty:'暂无通知',notif_mark_all:'全部已读',notif_login_required:'请登录查看通知。',notif_error:'加载通知失败。',
    load_more_loading:'加载更多...',
    pay_ref:'参考编号',pay_bank_title:'银行转账',pay_bank_name:'银行',pay_bank_acct:'账号',pay_bank_holder:'户名',pay_bank_amount:'金额',
    pay_complete_title:'下单成功！',pay_complete_sub:'等待付款确认',pay_complete_note:'管理员确认付款后将通过Line通知您。',pay_continue_shop:'继续购物',
    pay_stage_payment_pending:'待付款',pay_stage_payment_confirmed:'已确认付款',
    review_title:'评价',review_your_rating:'您的评分：',review_comment_ph:'写评价...',review_submit:'提交评价',review_empty:'暂无评价。',review_purchase_required:'购买此产品后才能写评价。',review_rating_required:'请选择评分。',review_submit_error:'提交评价失败。',review_delete_confirm:'确认删除此评价？',review_load_error:'加载评价失败。',
    admin_tab_stats:'统计',stats_monthly_revenue:'本月销售额',stats_total_members:'总会员数',stats_weekly_signups:'本周新注册',stats_monthly_orders:'本月订单',stats_top_products:'热门产品 Top 5',stats_monthly_trend:'月度订单趋势（6个月）',stats_no_data:'暂无数据。',
    err_network:'网络错误，请检查连接。',err_auth:'认证失败，请重新登录。',err_session_expired:'会话已过期，请重新登录。',err_generic:'发生错误，请重试。',
    line_add_friend:'添加LINE好友',line_add_desc:'获取订单通知和客服支持',
    nav_myactivity:'我的活动',ma_tab_msg:'消息',ma_tab_posts:'我的帖子',ma_tab_orders:'我的订单',ma_tab_used:'我的二手',ma_compose:'发送新消息',ma_inbox:'收件箱',ma_sent:'已发送',ma_to:'收件人：',ma_reply:'回复',ma_no_inbox:'没有收到消息。',ma_no_sent:'没有发送消息。',ma_no_posts:'还没有帖子。',ma_no_orders:'还没有订单。',ma_no_used:'还没有二手物品。',
    pwa_back:'返回',pwa_refresh:'刷新',
    sb_popular_products:'热门产品',sb_upcoming_events:'即将举行的活动',sb_latest_posts:'最新帖子',sb_no_data:'暂无数据',
    install_title:'添加到主屏幕',install_cancel:'取消',install_back:'← 返回',install_ok:'确定',
    install_android_title:'Android — 添加到主屏幕',install_android_steps:'① 点击右上角 <b>⋮ 菜单</b><br>② 选择 <b>"添加到主屏幕"</b><br>③ 点击 <b>"添加"</b>',
    install_ios_title:'iPhone / iPad — 添加到主屏幕',install_ios_steps:'① 点击底部 <b>分享按钮 □↑</b><br>② 选择 <b>"添加到主屏幕"</b><br>③ 点击 <b>"添加"</b><br><br>※ 仅限 Safari 浏览器',
    install_win_title:'Windows — 创建快捷方式',install_win_steps:'① 点击右上角 <b>⋮ 菜单</b><br>② 选择 <b>"更多工具"</b> → <b>"创建快捷方式"</b><br>③ 点击 <b>"创建"</b>',
    install_mac_title:'Mac — 添加到 Dock',install_mac_steps:'① 点击右上角 <b>⋮ 菜单</b><br>② 选择 <b>"更多工具"</b> → <b>"创建快捷方式"</b><br><br>※ Safari：<b>文件菜单</b> → <b>"添加到 Dock"</b>',
    settings_my_posts:'✍️ 我的帖子',settings_my_used:'♻️ 我的二手物品',settings_edit_profile:'👤 编辑资料',edit_order_title:'修改订单',shop_ship_title:'🚚 商城配送信息',shop_total_label:'合计',shop_count_suffix:'单',shop_no_orders_msg:'没有订单记录。',shop_no_stage_orders:'该阶段没有订单。',shop_stage_submitted:'已下单',shop_stage_payment_pending:'待付款',shop_stage_payment_confirmed:'已确认付款',shop_stage_preparing:'准备中',shop_stage_shipped:'配送中',shop_stage_delivered:'已送达',admin_tab_products:'🛍 商品',admin_tab_used:'♻️ 二手',admin_tab_forum:'💬 论坛',admin_tab_jobs:'💼 招聘',admin_tab_webzine:'📰 网刊',admin_tab_events:'📅 活动',wiz_stl_all_formats:'支持所有文件格式',wiz_stl_formats_hint:'STL · 图片 · PDF · 其他 · 最多10个',stl_viewer_3d:'🧊 3D预览',stl_viewer_image:'🖼 图片',stl_viewer_pdf:'📄 PDF',stl_viewer_file:'📎 文件',stl_viewer_hint:'拖拽: 旋转 · 滚轮: 缩放',stl_loading:'加载中...',stl_load_error:'无法加载文件。',stl_parse_error:'解析错误',stl_unsupported:'不支持预览此文件格式',stl_download:'📥 下载',line_id_optional_ph:'Line ID（可选 · 用于订单通知）',ma_activity_title:'我的活动',custom_carrier_direct:'手动输入',
    ma_compose_btn:'✉️ 发新消息',ma_inbox_label:'收件箱',ma_sent_label:'已发送',ma_reply_btn:'← 回复',ma_type_used:'二手市场',ma_type_forum:'临床讨论',ma_cat_implant:'🦷 种植',ma_cat_prosthetic:'💎 修复',ma_no_activity:'暂无帖子。',compose_fill_error:'请填写收件人、主题和内容。',compose_sent_msg:'消息已发送！',shop_receipt_order_no:'订单号',shop_receipt_clinic:'诊所',shop_receipt_date:'日期',shop_receipt_contact:'联系方式',shop_receipt_address:'地址',shop_carrier_select_err:'请选择快递公司。',shop_tracking_input_err:'请输入运单号。',
    used_seller:'卖家',used_comment_title:'💬 评论',used_comment_ph:'写评论...',used_comment_submit:'回复',used_comment_empty:'暂无评论',used_comment_writing_as:'评论者',used_send_msg:'✉️ 发送消息',
    empty_forum:'暂无帖子',empty_forum_sub:'成为第一个发起讨论的人！',empty_jobs:'暂无招聘信息',empty_jobs_sub:'发布第一个招聘岗位！',empty_webzine:'暂无文章',empty_webzine_sub:'新文章即将发布！',empty_events:'暂无活动',empty_events_sub:'请期待新活动！',empty_used:'暂无二手配件',empty_used_sub:'发布您的第一个二手商品！',
    leaders_title:'地区负责人',leaders_view_btn:'⭐ 查看地区负责人',leaders_select_region:'选择地区',leaders_select_province:'选择省份',leaders_all_provinces:'所有省份',leaders_clear:'✕ 清除',leaders_none:'暂无负责人',leaders_all_list:'所有地区负责人',pt_leaders:'地区负责人',
    feedback_send_btn:'发送反馈',feedback_send_desc:'Bug报告、功能建议、投诉、表扬',feedback_title:'发送反馈',feedback_category:'类别',feedback_title_label:'标题',feedback_title_ph:'输入标题',feedback_content_label:'内容',feedback_content_ph:'请详细描述您的反馈...',feedback_rating_label:'评分',feedback_submit:'提交反馈',feedback_cat_bug:'Bug',feedback_cat_feature:'功能建议',feedback_cat_complaint:'投诉',feedback_cat_praise:'表扬',feedback_cat_other:'其他',feedback_title_required:'请输入标题',feedback_content_required:'请输入内容',feedback_submit_success:'反馈已提交，谢谢！',feedback_submit_error:'提交反馈失败',feedback_admin_empty:'暂无反馈',feedback_status_unread:'未读',feedback_status_read:'已读',feedback_status_replied:'已回复',feedback_mark_read:'标记已读',feedback_mark_replied:'标记已回复',admin_tab_feedback:'💬 反馈',
    help_btn:'指南',help_close:'关闭',
    help_first_visit_title:'初次使用Dentalk？',help_first_visit_desc:'查看使用指南',help_first_visit_btn:'查看',
    help_title_home:'Dentalk使用指南',help_home_1:'🏠 Dentalk是一个B2B平台，用于订购优质牙科种植体配件。',help_home_2:'🛒 商店 — 浏览7个产品类别，使用QR支付下单。',help_home_3:'🦷 CNC定制 — 通过5步向导订制定制基台。',help_home_4:'💬 论坛 — 按地区和专业参与临床讨论。',help_home_5:'♻️ 二手市场 — 买卖二手牙科配件。',help_home_6:'💼 招聘 — 查找或发布牙科工作。',help_home_7:'📰 杂志 — 阅读牙科行业文章。',help_home_8:'📅 活动 — 发现活动和聚会，报名参加。',help_home_9:'⚙️ 设置 — 更改语言、切换暗黑模式、编辑资料。',
    help_title_shop:'商店指南',help_shop_1:'🗂 选择产品类别（Scan Body、Q-Base、Ready Made等）。',help_shop_2:'📋 浏览类别中的产品，点击查看详情。',help_shop_3:'📐 选择规格 — 种植体品牌、尺寸、牙齿色号。',help_shop_4:'🔢 为每个规格输入数量。',help_shop_5:'🛒 点击"加入购物车"。在底部查看购物车。',help_shop_6:'📝 填写诊所名称、地址、电话、LINE ID。',help_shop_7:'💳 确认订单并通过QR码（银行转账）付款。',help_shop_8:'📦 在类别下方的"我的订单"中跟踪订单状态。',
    help_title_custom:'CNC定制基台指南',help_custom_1:'🦷 第1步 — 在图表上选择牙齿。输入患者信息。',help_custom_2:'🔧 第2步 — 选择种植体品牌和平台（BIOTEM、Osstem等）。',help_custom_3:'🎨 第3步 — 从14种VITA色号中选择牙齿颜色。',help_custom_4:'📁 第4步 — 上传STL文件、图片或PDF（最多10个）。',help_custom_5:'✅ 第5步 — 审查所有病例并确认订单。',help_custom_6:'📋 在"进行中"和"已完成"标签中跟踪进度。',help_custom_7:'💬 管理员将发送设计版本供您审批。',
    help_title_forum:'论坛指南',help_forum_1:'🌏 选择地区标签筛选帖子（全部、北部、南部等）。',help_forum_2:'🏙 选择省份进行更具体的筛选。',help_forum_3:'✍️ 点击"发帖"开始新的讨论。',help_forum_4:'📂 选择类别（种植、修复、正畸等）。',help_forum_5:'📷 附加图片（可选）。',help_forum_6:'💬 点击帖子阅读并发表评论。',help_forum_7:'⭐ 查看地区负责人。',
    help_title_used:'二手市场指南',help_used_1:'📸 点击"发布二手物品"出售您的牙科配件。',help_used_2:'📝 填写名称、编号、价格、状况和描述。',help_used_3:'🖼 上传物品照片。',help_used_4:'👀 浏览列表 — 点击查看详情和评论。',help_used_5:'💬 在列表上留下评论或提问。',help_used_6:'✉️ 向卖家发送私信。',help_used_7:'✅ 卖家可以标记为"已售出"。',
    help_title_jobs:'招聘指南',help_jobs_1:'📋 浏览招聘列表 — 按类型筛选（招聘、求职、转职）。',help_jobs_2:'🌏 按地区筛选查找当地工作。',help_jobs_3:'✏️ 登录后点击"发布职位"创建列表。',help_jobs_4:'📝 填写标题、描述、薪资范围和联系方式。',help_jobs_5:'👀 点击列表查看完整详情。',
    help_title_webzine:'杂志指南',help_webzine_1:'📰 浏览牙科行业文章和新闻。',help_webzine_2:'🗂 按类别筛选（新闻、技术、临床等）。',help_webzine_3:'👀 点击文章阅读全文。',
    help_title_events:'活动指南',help_events_1:'📅 浏览即将举行的牙科活动、研讨会和聚会。',help_events_2:'👀 点击活动查看详情（日期、地点、描述）。',help_events_3:'✅ 报名参加 — 点击"参加"按钮。',help_events_4:'📝 地区负责人可以创建新活动和聚会。',
    help_title_settings:'设置指南',help_settings_1:'👤 编辑资料 — 诊所名称、邮箱、电话、地址。',help_settings_2:'🌐 更改显示语言（支持6+种语言）。',help_settings_3:'🌙 切换暗黑模式。',help_settings_4:'📦 查看最近订单和发帖记录。',help_settings_5:'💬 发送反馈 — 报告错误、建议功能或表扬。',help_settings_6:'💚 添加LINE好友获取订单通知和支持。',
    help_title_myactivity:'我的活动指南',help_myactivity_1:'✉️ 消息 — 查看收到和发送的消息。撰写新消息。',help_myactivity_2:'✍️ 我的帖子 — 查看您的所有论坛帖子。',help_myactivity_3:'📦 我的订单 — 跟踪商店和定制订单。',help_myactivity_4:'♻️ 我的二手 — 管理您的二手市场列表。',
    credit_unit:'积分',credit_charge_btn:'充值积分',credit_charge_title:'充值积分',credit_target_user:'用户',credit_current:'当前',credit_charged_msg:'已为 % 充值 % 积分。',credit_charge_error:'充值失败。',credit_line_charged:'积分充值: +% · 余额: %',credit_adjust_btn:'修改',credit_adjust_title:'调整积分',credit_adjust_save:'保存',credit_new_amount:'新数量',credit_balance:'积分余额',credit_no_history:'暂无积分记录。',credit_history_title:'积分记录',credit_type_charge:'充值',credit_type_use:'使用',credit_used:'使用积分',credit_remaining:'剩余',credit_insufficient_msg:'积分不足。需要 %，拥有 %。请联系管理员充值。',credit_check_error:'检查积分失败。',ma_tab_credits:'💰 积分',credit_load_error:'加载积分记录失败。',
    ma_tab_invoices:'🧾 发票',inv_select_title:'税务发票 / 收据',inv_select_desc:'选择要开具的文件类型',inv_tax_label:'税务发票 (VAT 7%)',inv_rec_label:'收据',inv_none_label:'不需要',inv_buyer_taxid:'买方税号',inv_issue_btn:'开具文件',inv_skip:'跳过',doc_tax_invoice:'税务发票',doc_receipt:'收据',inv_taxid_hint:'仅税务发票需要',tax_id_required:'需要税号',tax_id_prompt:'请输入税号以开具税务发票。',tax_id_placeholder:'税号 / 营业执照号',tax_id_confirm:'确认',tax_id_cancel:'取消',inv_select_one:'请至少选择一种文件类型。',inv_issued_ok:'文件开具成功！',inv_issue_error:'文件开具失败。',inv_no_invoices:'暂无发票。',inv_print:'打印',inv_download:'下载',inv_view:'查看发票',inv_expires:'过期倒计时',inv_days:'天',inv_subtotal:'小计',inv_load_error:'加载发票失败。',
add_more:'添加',files_selected_fmt:'已选择 % 个文件 · %KB',drag_more_files:'拖拽或点击此处添加更多文件',design_review_title:'设计确认 (ver.%)',design_satisfied:'满意',design_not_satisfied:'不满意',design_reject_ph:'请输入修改要求...',design_reject_submit:'提交不满意',design_revision_pending:'设计修改请求中',confirm_delete_order:'确定删除此未提交订单吗？',files_unit:'个',cnc_deadline:'交付期限',
};
