// Dentalk i18n - Korean
LANG.ko = {
    nav_home:'HOME',nav_shop:'SHOP',nav_custom:'CNC Custom Abut',nav_used:'중고마켓',nav_forum:'임상토론방',nav_events:'이벤트',nav_factory:'공장',nav_settings:'설정',nav_login:'로그인',privacy_btn:'개인정보 처리방침',
    hdr_search:'검색',hdr_notif:'알림',hdr_install:'설치',hdr_cart:'장바구니',hdr_login:'로그인',hdr_logout:'로그아웃',
    loading_text:'로딩 중...',settings_darkmode:'다크 모드',settings_darkmode_desc:'어두운 테마로 전환',
    footer_links:'바로가기',footer_connect:'연결',footer_copyright:'© 2026 Dentalk · BIOTEM × BIOPLANT. All rights reserved.',footer_address:'방콕, 태국',
    pt_home:'Home',pt_shop:'Shop',pt_custom:'Custom Abutment',pt_used:'중고마켓',pt_forum:'임상토론방',pt_events:'Events',pt_factory:'Factory',pt_settings:'설정',
    login_subtitle:'의사 로그인',login_ph:'닉네임',login_password_ph:'비밀번호',login_btn:'로그인',login_cancel:'취소',login_error:'닉네임과 비밀번호를 입력해주세요.',login_verifying:'확인 중...',login_not_found:'닉네임이 없거나 비밀번호가 틀렸습니다.',login_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',login_register_link:'사용 신청하기 →',
    reg_title:'사용 신청',reg_subtitle:'정보를 입력하시면 24시간 내에 검토 후 승인해 드립니다.',reg_license_ph:'면허 번호 (필수)',reg_name_ph:'의사 이름 (필수)',reg_clinic_ph:'치과명 (필수)',reg_contact_ph:'전화번호 또는 Line ID (필수)',reg_password_ph:'비밀번호 (필수)',reg_password_confirm_ph:'비밀번호 확인 (필수)',reg_submit:'신청하기',reg_submitting:'신청 중...',reg_success:'신청이 접수되었습니다!\n관리자 승인 후 24시간 내에 연락드리겠습니다.',reg_error:'필수 항목을 모두 입력해주세요.',reg_pwd_mismatch:'비밀번호가 일치하지 않습니다.',reg_duplicate:'이미 등록된 닉네임입니다.',reg_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',
    session_title:'세션 만료 임박',session_desc1:'로그인이',session_desc2:'후 만료됩니다.',session_q:'지금 연장하시겠어요?',session_extend:'30분 연장하기',session_later:'나중에',session_expired:'세션이 만료되었습니다. 다시 로그인해주세요.',
    side_remain:'남은 시간:',side_login_btn:'의사 로그인',side_logged_label:'로그인 중',side_logout:'로그아웃',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'디지털 임플란트 부품',home_title2:'주문 시스템',home_desc:'태국 전역 치과에 프리미엄 BIOTEM 임플란트 부품을 직접 공급합니다.',home_goto_shop:'쇼핑몰로 이동',home_line_add:'LINE 친구 추가',
    home_about:'회사 소개',home_biotem_desc:'한국 치과 임플란트 제조사. 첨단 디지털 워크플로우 솔루션을 갖춘 임플란트 전문 기업.',home_bioplant_desc:'방콕의 프리미엄 치과 부품 제조 센터. 동남아시아 전역 치과에 공급.',home_categories:'제품 카테고리',home_contact:'연락처 및 주소',home_address:'태국 방콕',home_hours:'월–금 09:00–18:00',home_line_label:'Line 공식 계정',
    home_vision_label:'비전',home_vision:'동남아시아 임플란트 정밀도의 새 기준을 제시합니다',home_stat1:'인증',home_stat2:'원산지',home_stat3:'공급 범위',home_biotem_short:'임플란트 전문 · 한국',home_bioplant_short:'생산 센터 · 방콕',home_mission_label:'미션',home_mission:'한국 제조 프리미엄 치과 임플란트 부품을 태국 및 동남아시아 전역 치과에 신속하고 신뢰할 수 있는 서비스로 공급합니다.',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'프리미엄 치과 임플란트 부품',hero_bioplant_desc:'한국 ISO 인증 제조, 클리닉 빠른 배송',hero_bioplant_cta:'쇼핑몰로',
    hero_cnc_tag:'CNC 커스텀 어버트먼트',hero_cnc_title:'정밀 맞춤 제작',hero_cnc_desc:'스캔바디부터 최종 보철까지 사양에 맞게 제작',hero_cnc_cta:'주문하기',
    sec_categories:'제품 카테고리',sec_see_more:'전체 보기 ›',cat_scan_body_desc:'구강 내 · 모델용',cat_q_base_desc:'지르코니아 어버트먼트 H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'밀링 호환 · N · R 타입',cat_multi_unit_desc:'All-on-X · MUA · 스캔바디',cat_3d_analog_desc:'GeoMedi 스톤 & 3D 모델',
    sec_forum_preview:'임상 토론방',sec_forum_more:'전체 보기 ›',home_forum_empty:'아직 게시물이 없습니다.',
    sec_events_preview:'예정 이벤트',sec_events_more:'전체 보기 ›',home_events_empty:'예정된 이벤트가 없습니다.',
    sec_webzine:'웹진',sec_webzine_sub:'임상 케이스 & 제품 업데이트',sec_webzine_coming:'준비 중 — 곧 공개됩니다',ad_label:'광고',
    admin_tab_ads:'광고 관리',admin_ads_summary_active:'활성 배너',admin_ads_summary_clicks:'오늘 클릭수',admin_ads_summary_impressions:'오늘 노출수',admin_ads_summary_ctr:'평균 CTR',
    admin_ads_form_title:'배너 등록',admin_ads_advertiser:'광고주',admin_ads_advertiser_ph:'광고주명',admin_ads_image:'이미지',admin_ads_image_upload:'클릭하여 이미지 업로드',admin_ads_link:'링크 URL',admin_ads_link_ph:'https://',admin_ads_position:'위치',admin_ads_start:'시작일',admin_ads_end:'종료일',admin_ads_submit:'등록',admin_ads_fill_alert:'광고주, 이미지, 위치를 입력해주세요.',
    admin_ads_list_title:'배너 목록',admin_ads_col_advertiser:'광고주',admin_ads_col_position:'위치',admin_ads_col_period:'기간',admin_ads_col_clicks:'클릭수',admin_ads_col_impressions:'노출수',admin_ads_col_ctr:'CTR',admin_ads_col_status:'상태',admin_ads_col_actions:'관리',admin_ads_active:'활성',admin_ads_inactive:'비활성',admin_ads_edit:'수정',admin_ads_delete:'삭제',admin_ads_delete_confirm:'이 배너를 삭제하시겠습니까?',admin_ads_empty:'등록된 배너가 없습니다.',admin_ads_save:'저장',admin_ads_cancel:'취소',admin_ads_editing:'배너 수정',admin_ads_update_success:'배너가 수정되었습니다.',admin_ads_image_change:'이미지 변경',
    nav_webzine:'웹진',wz_cat_all:'전체',wz_cat_implant:'임플란트 케이스',wz_cat_prosthetic:'보철 케이스',wz_cat_review:'제품 리뷰',wz_cat_news:'업계 뉴스',wz_cat_education:'교육 콘텐츠',
    wz_empty:'아직 기사가 없습니다.',wz_home_empty:'기사가 곧 공개됩니다',wz_write_btn:'기사 작성',wz_form_title:'새 기사',wz_title_ph:'기사 제목',wz_thumb_ph:'클릭하여 썸네일 업로드',wz_body_ph:'기사 본문 작성 (마크다운 지원)',wz_submit_btn:'발행',wz_fill_alert:'제목과 본문을 입력해주세요.',wz_delete_confirm:'이 기사를 삭제하시겠습니까?',
    nav_jobs:'구인구직',job_type_all:'전체',job_type_dentist:'치과의사 구인',job_type_staff:'직원 구인',job_type_equipment:'장비 양도',
    job_empty:'아직 구인 글이 없습니다.',job_write_btn:'글쓰기',job_form_title:'새 구인 글',job_title_ph:'제목',job_desc_ph:'상세 설명',job_salary_ph:'급여 범위 (예: 30,000-50,000 THB)',job_req_ph:'요구사항 (선택)',job_contact_ph:'연락처 (전화, 이메일, LINE)',job_province_ph:'주(Province) 선택',job_submit_btn:'등록',job_fill_alert:'제목과 설명을 입력해주세요.',job_delete_confirm:'이 구인 글을 삭제하시겠습니까?',job_delete_btn:'삭제',
    job_salary:'급여',job_desc:'설명',job_requirements:'요구사항',job_contact:'연락처',
    shop_hint:'카테고리를 선택하여 주문하세요',shop_select:'선택 ›',shop_each:'개당',
    order_add_cart:'장바구니 추가',order_qty_error:'수량을 1개 이상 입력해주세요.',
    cart_title:'장바구니',cart_total:'합계',cart_checkout:'결제하기',cart_close:'닫기',cart_empty:'장바구니가 비어 있습니다!',
    shop_specs:'규격 및 수량',shop_in_stock:'재고 있음',shop_out_of_stock:'품절',shop_my_orders:'내 주문 현황',shop_product_count:'개 제품',cart_bar_tap:'탭하여 보기',cart_bar_items:'개',cart_added:'장바구니에 추가됨!',
    addr_title:'배송 정보',addr_clinic_ph:'치과명',addr_phone_ph:'전화번호',addr_addr_ph:'상세 주소',addr_qr_btn:'QR 생성',addr_back:'← 뒤로',addr_fill_error:'배송 정보를 모두 입력해주세요.',
    qr_label:'QR로 결제',qr_summary_title:'주문 요약',qr_total:'합계',qr_complete:'결제 완료',
    used_contact_title:'판매자 연락처',used_contact_close:'닫기',
    custom_tab_new:'새 주문',custom_form_title:'커스텀 어버트먼트 주문',custom_delivery_title:'납품 정보',custom_clinic_ph:'치과명 / 기공소명',custom_addr_ph:'납품 주소',custom_phone_ph:'연락처',custom_line_ph:'Line ID (알림 수신용)',custom_submit:'주문 제출하기',custom_submit_note:'주문 접수 시 Line으로 확인 메시지가 발송됩니다',custom_empty:'아직 주문 내역이 없어요',
    case_label:'케이스 #',case_remove:'✕ 삭제',case_patient_ph:'환자 ID (익명 가능, 예: P001)',case_tooth_hint:'치아 선택 · 탭하여 선택/해제',upper_jaw:'상악 (Upper Jaw)',lower_jaw:'하악 (Lower Jaw)',jaw_border:'치열 경계',selected_teeth:'선택된 치아 —',sel_count_suffix:'개',brand_ph:'임플란트 종류 선택',size_ph:'사이즈 (예: Ø4.0 / L10)',color_ph:'치아 색상 (VITA)',case_add:'+ 케이스 추가',stl_label:'STL 파일 업로드 (최대 10개)',stl_hint:'드래그하거나 탭하여 .stl 파일 선택',memo_ph:'특별 요청사항 (선택)',anon_patient:'익명',case_deadline_label:'납품 기한',
    err_fill_delivery:'치과명, 납품 주소, 연락처를 입력해주세요.',err_select_tooth:'케이스 #%: 치아를 최소 1개 선택해주세요.',err_fill_tooth:'케이스 #% 치아 #%: 임플란트 종류와 사이즈를 입력해주세요.',err_add_case:'케이스를 최소 1개 추가해주세요.',
    order_success_msg:'✅ 주문이 접수되었습니다!\n주문번호: %\n케이스: %개 / 치아: %개',order_success_line:'\nLine으로 확인 메시지를 보내드렸습니다.',
    status_label:'진행 상황',case_detail:'케이스 상세',teeth_count:'개 치아',cases_unit:'개',teeth_total_prefix:'총 ',patient_label:'환자: ',no_tooth_info:'치아 정보 없음',case_nr:'케이스 #',
    used_sell_title:'중고 부품 판매',used_name_ph:'부품명',used_code_ph:'제품 코드',used_price_ph:'가격 (THB)',cond_new:'거의 새것',cond_good:'양호',cond_fair:'보통',used_desc_ph:'상태 설명...',used_contact_ph:'연락처 (Line ID / 전화번호)',used_post_btn:'판매 등록',used_list_title:'판매 중인 중고 부품',used_contact_btn:'연락하기',used_delete_btn:'삭제',used_empty:'아직 등록된 중고 물품이 없어요',used_fill_error:'부품명, 가격, 연락처를 입력해주세요.',used_no_photo:'사진 없음',
    forum_new_post:'새 글 작성',forum_title_ph:'제목',forum_body_ph:'내용을 작성해주세요...',forum_post_btn:'게시',
    settings_lang:'언어 설정',settings_account:'계정',settings_license:'면허번호:',settings_save_btn:'언어 저장',settings_saved_msg:'언어가 저장되었습니다!',settings_pending:'언어를 선택하고 저장 버튼을 눌러주세요.',
    pe_title:'✏️ 내 정보 수정',pe_subtitle:'수정 가능 항목',pe_email:'이메일',pe_phone:'전화번호',pe_address:'주소',pe_clinic:'치과이름',pe_save:'저장',pe_cancel:'취소',pe_email_ph:'이메일 주소',pe_phone_ph:'전화번호',pe_address_ph:'주소',pe_clinic_ph:'치과이름',
    profile_title:'👤 내 정보',profile_edit_btn:'수정',profile_login_msg:'로그인 후 확인 가능합니다.',profile_saved_msg:'✅ 저장되었습니다!',profile_no_change:'(변경불가)',prof_nickname:'닉네임',prof_doctor:'의사이름',login_required:'로그인이 필요합니다.',
    factory_subtitle:'방콕의 프리미엄 임플란트 제조 센터',
    tooth_11:'중절치',tooth_12:'측절치',tooth_13:'견치',tooth_14:'제1소구치',tooth_15:'제2소구치',tooth_16:'제1대구치',tooth_17:'제2대구치',
    upper:'상악',lower:'하악',
    stage_received:'주문 접수',stage_stl:'STL 검토',stage_design:'디자인 중',stage_cnc:'CNC 생산',stage_qc:'품질 검사',stage_shipping:'배송 중',stage_done:'납품 완료',stage_submitted:'접수 대기',stage_confirmed:'접수 확인',stage_design_ready:'디자인 검토',stage_design_revision:'디자인 수정 중',stage_approved:'제작 승인',stage_milling:'CNC 밀링 중',stage_shipped:'배송 중',
    line_deadline:'납기',line_memo:'메모',line_total_cases:'총 %케이스 / %치아',
    reg_privacy_agree_prefix:'다음 약관에 동의합니다:',reg_privacy_link:'개인정보 처리방침',reg_privacy_agree_suffix:'(태국 PDPA)',reg_privacy_error:'개인정보 처리방침에 동의 후 계속할 수 있습니다.',
    privacy_title:'개인정보 처리방침',privacy_close:'닫기',
    used_photo_add:'사진 추가',shop_items:'개',
    forum_cat_implant:'🦷 임플란트',forum_cat_prosthetic:'💎 보철',forum_cat_conservative:'🪥 보존',forum_cat_orthodontics:'🦷 교정',forum_cat_oral_surgery:'✂️ 구강외과',forum_cat_periodontics:'🌿 치주',forum_cat_pediatric:'👶 소아치과',forum_cat_radiology:'📷 영상치의학',forum_cat_oral_medicine:'💊 구강내과',forum_cat_preventive:'🛡 예방치과',forum_cat_general:'🏥 통합진료',forum_photo_add:'📷 사진 추가 (최대 5장)',forum_empty:'게시물이 없습니다.',
    forum_write_btn:'✍️ 글쓰기',forum_close_form:'✕ 닫기',forum_cat_label:'카테고리',
    forum_region_label:'지역',forum_province_label:'주(Province)',
    forum_region_all:'🌏 전체',forum_region_north:'🏔 북부',forum_region_northeast:'🌾 동북부',forum_region_east:'🌊 동부',forum_region_south:'🏝 남부',forum_region_central:'🏙 중부',
    forum_comment_title:'💬 댓글',forum_comment_ph:'댓글을 입력하세요...',forum_comment_submit:'등록',forum_no_comments:'아직 댓글이 없습니다.',forum_writing_as:'작성자',
    custom_tab_list:'진행중',custom_tab_done:'완료',
    install_ios:'📱 <b>iPhone / Safari 설치 방법</b><br><br>① 하단 공유 버튼 <b>□↑</b> 탭<br>② <b>"홈 화면에 추가"</b> 선택<br>③ <b>"추가"</b> 탭',
    install_android:'💻 <b>PC / Android 설치 방법</b><br><br>① 브라우저 주소창 우측의<br>&nbsp;&nbsp;&nbsp;<b>설치 아이콘 ⊕</b> 클릭<br>② <b>"설치"</b> 클릭<br><br>※ 아이콘이 없으면 브라우저 메뉴<br>&nbsp;&nbsp;&nbsp;→ "앱으로 설치"',
    design_waiting:'⏳ 디자인 업로드 대기 중...',shipped_msg:'🚚 배송이 출발했습니다. 제품 수령 후 아래 버튼을 눌러주세요.',receive_btn:'📦 수령 완료',
    edit_order_btn:'✏️ 수정',delete_order_btn:'🗑 삭제',review_history_label:'검토 이력 (%회)',
    done_orders_empty:'완료된 주문이 없습니다.',done_status_label:'완료',done_cases_teeth_fmt:'%케이스 · %치아',
    reg_nick_ph:'닉네임 (필수) — 모든 활동에 사용됩니다',reg_email_ph:'이메일주소 (필수)',
    compose_title:'✉️ 쪽지 보내기',compose_to_ph:'받는 사람 (닉네임)',compose_subj_ph:'제목',compose_body_ph:'내용을 입력하세요...',compose_send:'보내기',
    ship_carrier_custom_opt:'직접 입력',ship_carrier_ph:'배송사 이름 입력',ship_tracking_label:'송장번호',ship_tracking_ph:'송장번호 입력',ship_process_btn:'🚚 배송 처리 → LINE 발송',
    leader_badge:'지역 리더',leader_assign:'리더 지정',leader_remove:'리더 해임',leader_select_region:'지역 선택...',leader_select_level:'레벨 선택...',leader_select_province:'주(도) 선택...',leader_select_title:'직책 선택...',leader_level_all:'태국 전지역',leader_level_region:'지역 리더',leader_level_province:'주(도) 리더',leader_title_occupied:'이미 배정된 직책입니다.',title_president:'회장',title_vice_president:'부회장',title_secretary:'총무',title_director:'이사',title_auditor:'감사',title_representative:'대표',
    forum_pinned:'고정됨',forum_pin:'고정',forum_unpin:'고정 해제',forum_delete:'삭제',forum_delete_confirm:'이 게시물을 삭제하시겠습니까?',event_delete_confirm:'이 이벤트를 삭제하시겠습니까?',
    admin_new_event_title:'새 이벤트 추가',admin_event_name_ph:'이벤트명',admin_event_loc_ph:'장소',admin_event_add_btn:'+ 추가',admin_event_fill_alert:'모든 항목을 입력해주세요.',
    meetup_create_btn:'모임 만들기',meetup_badge:'모임',event_badge:'이벤트',meetup_form_title:'새 모임 만들기',meetup_title_ph:'모임 제목',meetup_loc_ph:'장소',meetup_desc_ph:'설명 (선택)',meetup_submit_btn:'모임 생성',meetup_fill_alert:'제목, 날짜, 장소를 모두 입력해주세요.',meetup_created_by:'만든 사람',
    rsvp_title:'참석 여부',rsvp_attend:'✅ 참석',rsvp_not_attend:'❌ 불참',rsvp_attendees:'명 참석',rsvp_attendee_list:'참석자 목록',rsvp_no_attendees:'아직 참석자가 없습니다.',rsvp_login_required:'참석하려면 로그인해주세요.',rsvp_error:'참석 처리에 실패했습니다. 다시 시도해주세요.',
    admin_orders_new:'새 주문',admin_orders_active:'진행중',admin_orders_done:'완료',admin_orders_empty:'주문이 없습니다.',
    shipped_status:'배송 완료',carrier_label:'배송사',tracking_label:'송장',received_status:'수령 완료',teeth_colon_label:'치아:',
    wiz_step1:'환자 & 치아',wiz_step2:'브랜드',wiz_step3:'쉐이드 & 메모',wiz_step4:'STL',wiz_step5:'확인 & 제출',wiz_next:'다음 →',wiz_prev:'← 이전',wiz_patient_label:'환자 ID',wiz_no_tooth_err:'치아를 최소 1개 선택해주세요.',wiz_no_brand_err:'임플란트 브랜드를 선택해주세요.',wiz_brand_all_hint:'선택한 모든 치아에 적용',wiz_size_for_tooth:'사이즈 (예: Ø4.0 / L10)',wiz_shade_label:'치아 색상 (VITA)',wiz_stl_main_label:'STL / 3D 파일',wiz_stl_main_hint:'드래그하거나 탭하여 선택 · 최대 10개',wiz_confirm_title:'주문 확인',wiz_delivery_label:'납품 정보',wiz_teeth_selected:'개 치아 선택',wiz_start_over:'새 주문 시작',wiz_size_table_title:'치아별 사이즈',
    used_post_toggle:'📸 중고 물품 등록',used_close_form:'✕ 닫기',settings_my_orders:'📦 나의 주문',settings_no_orders:'주문 내역이 없습니다.',
    admin_panel_title:'관리자 패널',admin_total_members:'총 회원수',admin_pending_orders:'대기중 주문',admin_today_signups:'오늘 신규가입',
    admin_tab_orders:'주문관리',admin_tab_users:'회원관리',admin_tab_custom:'커스텀주문',
    admin_order_date:'날짜',admin_order_customer:'고객명',admin_order_total:'총액',admin_order_status:'상태',admin_change_status:'상태 변경',
    admin_user_approve:'✅ 승인',admin_user_reject:'❌ 거절',admin_user_block:'🔒 차단',admin_user_unblock:'✅ 차단해제',
    admin_user_pending_badge:'승인대기',admin_user_active_badge:'활성',admin_user_blocked_badge:'차단됨',
    admin_custom_change_stage:'단계 변경',admin_pending_users_title:'⏳ 승인 대기 회원',admin_all_users_title:'👥 전체 회원',
    admin_no_pending_users:'승인 대기 회원이 없습니다.',admin_loading:'로딩 중...',admin_load_fail:'로드 실패',admin_no_users:'회원이 없습니다.',admin_error:'오류가 발생했습니다.',
    search_ph:'검색...',search_hint:'검색어를 입력하세요',search_searching:'검색 중...',search_no_results:'검색 결과가 없습니다.',search_error:'검색에 실패했습니다. 다시 시도해주세요.',
    notif_title:'알림',notif_empty:'알림이 없습니다',notif_mark_all:'모두 읽음',notif_login_required:'알림을 보려면 로그인하세요.',notif_error:'알림을 불러오지 못했습니다.',
    load_more_loading:'더 불러오는 중...',
    pay_ref:'주문 참조번호',pay_bank_title:'계좌이체 안내',pay_bank_name:'은행',pay_bank_acct:'계좌번호',pay_bank_holder:'예금주',pay_bank_amount:'금액',
    pay_complete_title:'주문 완료!',pay_complete_sub:'결제 확인 대기 중',pay_complete_note:'관리자가 입금을 확인합니다. Line으로 알림드립니다.',pay_continue_shop:'쇼핑 계속하기',
    pay_stage_payment_pending:'입금 대기',pay_stage_payment_confirmed:'입금 확인',
    review_title:'리뷰',review_your_rating:'평점:',review_comment_ph:'리뷰를 작성하세요...',review_submit:'리뷰 등록',review_empty:'아직 리뷰가 없습니다.',review_purchase_required:'이 제품을 구매한 후 리뷰를 작성할 수 있습니다.',review_rating_required:'평점을 선택해주세요.',review_submit_error:'리뷰 등록에 실패했습니다.',review_delete_confirm:'이 리뷰를 삭제하시겠습니까?',review_load_error:'리뷰를 불러오지 못했습니다.',
    admin_tab_stats:'통계',stats_monthly_revenue:'이번 달 매출',stats_total_members:'총 회원수',stats_weekly_signups:'이번 주 신규가입',stats_monthly_orders:'이번 달 주문',stats_top_products:'인기 제품 Top 5',stats_monthly_trend:'월별 주문 추이 (6개월)',stats_no_data:'데이터가 없습니다.',
    err_network:'네트워크 오류입니다. 연결을 확인해주세요.',err_auth:'인증에 실패했습니다. 다시 로그인해주세요.',err_session_expired:'세션이 만료되었습니다. 다시 로그인해주세요.',err_generic:'오류가 발생했습니다. 다시 시도해주세요.',
    line_add_friend:'LINE 친구 추가',line_add_desc:'주문 알림 및 고객 지원',
    nav_myactivity:'내 활동',ma_tab_msg:'쪽지',ma_tab_posts:'내 게시물',ma_tab_orders:'내 주문',ma_tab_used:'내 중고',ma_compose:'새 쪽지 보내기',ma_inbox:'받은 쪽지',ma_sent:'보낸 쪽지',ma_to:'받는 사람:',ma_reply:'답장',ma_no_inbox:'받은 쪽지가 없습니다.',ma_no_sent:'보낸 쪽지가 없습니다.',ma_no_posts:'작성한 게시물이 없습니다.',ma_no_orders:'주문 내역이 없습니다.',ma_no_used:'등록한 중고물품이 없습니다.',
    pwa_back:'뒤로',pwa_refresh:'새로고침',
    sb_popular_products:'인기 제품',sb_upcoming_events:'다가오는 이벤트',sb_latest_posts:'최신 게시물',sb_no_data:'데이터 없음',
    install_title:'홈 화면에 추가',install_cancel:'취소',install_back:'← 뒤로',install_ok:'확인',
    install_android_title:'Android — 홈 화면에 추가',install_android_steps:'① 상단 우측 <b>⋮ 메뉴</b> 탭<br>② <b>"홈 화면에 추가"</b> 선택<br>③ <b>"추가"</b> 탭',
    install_ios_title:'iPhone / iPad — 홈 화면에 추가',install_ios_steps:'① Safari 하단 <b>공유 버튼 □↑</b> 탭<br>② <b>"홈 화면에 추가"</b> 선택<br>③ <b>"추가"</b> 탭<br><br>※ Safari 브라우저에서만 가능',
    install_win_title:'Windows — 바로가기 만들기',install_win_steps:'① 상단 우측 <b>⋮ 메뉴</b> 클릭<br>② <b>"도구 더보기"</b> → <b>"바로가기 만들기"</b> 선택<br>③ <b>"만들기"</b> 클릭',
    install_mac_title:'Mac — Dock에 추가',install_mac_steps:'① 상단 우측 <b>⋮ 메뉴</b> 클릭<br>② <b>"도구 더보기"</b> → <b>"바로가기 만들기"</b> 선택<br><br>※ Safari: <b>파일 메뉴</b> → <b>"Dock에 추가"</b>',
    settings_my_posts:'✍️ 내가 쓴 게시물',settings_my_used:'♻️ 내 중고물품',settings_edit_profile:'👤 내 정보 수정',edit_order_title:'주문 수정',shop_ship_title:'🚚 쇼핑몰 배송 정보 입력',shop_total_label:'합계',shop_count_suffix:'건',shop_no_orders_msg:'주문 내역이 없습니다.',shop_no_stage_orders:'해당 단계의 주문이 없습니다.',shop_stage_submitted:'주문접수',shop_stage_payment_pending:'입금대기',shop_stage_payment_confirmed:'입금확인',shop_stage_preparing:'제품준비중',shop_stage_shipped:'배송중',shop_stage_delivered:'배송완료',admin_tab_products:'🛍 상품',admin_tab_used:'♻️ 중고',admin_tab_forum:'💬 포럼',admin_tab_jobs:'💼 구인구직',admin_tab_webzine:'📰 웹진',admin_tab_events:'📅 이벤트',wiz_stl_all_formats:'모든 파일 형식 지원',wiz_stl_formats_hint:'STL · 이미지 · PDF · 기타 · 최대 10개',stl_viewer_3d:'🧊 3D 미리보기',stl_viewer_image:'🖼 이미지',stl_viewer_pdf:'📄 PDF',stl_viewer_file:'📎 파일',stl_viewer_hint:'드래그: 회전 · 스크롤: 줌',stl_loading:'불러오는 중...',stl_load_error:'파일을 불러올 수 없습니다.',stl_parse_error:'파싱 오류',stl_unsupported:'미리보기를 지원하지 않는 파일 형식입니다',stl_download:'📥 다운로드',line_id_optional_ph:'Line ID (선택 · 주문 알림용)',ma_activity_title:'내 활동',custom_carrier_direct:'직접 입력',
    ma_compose_btn:'✉️ 새 쪽지 보내기',ma_inbox_label:'받은 쪽지',ma_sent_label:'보낸 쪽지',ma_reply_btn:'← 답장',ma_type_used:'중고마켓',ma_type_forum:'임상토론방',ma_cat_implant:'🦷 임플란트',ma_cat_prosthetic:'💎 보철',ma_no_activity:'게시물이 없습니다.',compose_fill_error:'받는 사람, 제목, 내용을 모두 입력해주세요.',compose_sent_msg:'쪽지를 보냈습니다!',shop_receipt_order_no:'주문번호',shop_receipt_clinic:'클리닉',shop_receipt_date:'날짜',shop_receipt_contact:'연락처',shop_receipt_address:'주소',shop_carrier_select_err:'배송사를 선택해주세요.',shop_tracking_input_err:'송장번호를 입력해주세요.',
    used_seller:'판매자',used_comment_title:'💬 댓글',used_comment_ph:'댓글을 입력하세요...',used_comment_submit:'작성',used_comment_empty:'아직 댓글이 없습니다.',used_comment_writing_as:'작성자',used_send_msg:'✉️ 쪽지 보내기',
};
