// i18n - 다국어 지원
const LANG = {
  en: {
    nav_home:'HOME',nav_shop:'SHOP',nav_custom:'CNC Custom Abut',nav_used:'USED MARKET',nav_forum:'DISCUSSION',nav_events:'EVENTS',nav_factory:'FACTORY',nav_settings:'SETTINGS',
    pt_home:'Home',pt_shop:'Shop',pt_custom:'Custom Abutment',pt_used:'Used Market',pt_forum:'Clinical Discussion',pt_events:'Events',pt_factory:'Factory',pt_settings:'Settings',
    login_subtitle:'DOCTOR LOGIN',login_ph:'Nickname',login_password_ph:'Password',login_btn:'LOGIN',login_cancel:'Cancel',login_error:'Please enter nickname and password.',login_verifying:'Verifying...',login_not_found:'Nickname not found or incorrect password.',login_network_error:'Network error. Please try again.',login_register_link:'Request Access →',
    reg_title:'Request Access',reg_subtitle:'Fill in your details. Admin will approve within 24 hours.',reg_license_ph:'License Number (required)',reg_name_ph:'Doctor Name (required)',reg_clinic_ph:'Clinic Name (required)',reg_contact_ph:'Phone or Line ID (required)',reg_password_ph:'Password (required)',reg_password_confirm_ph:'Confirm Password (required)',reg_submit:'Submit Request',reg_submitting:'Submitting...',reg_success:'Request submitted!\nWe will contact you within 24 hours after approval.',reg_error:'Please fill in all required fields.',reg_pwd_mismatch:'Passwords do not match.',reg_duplicate:'This nickname is already registered.',reg_network_error:'Network error. Please try again.',
    session_title:'Session Expiring',session_desc1:'Login expires in',session_desc2:'',session_q:'Would you like to extend?',session_extend:'Extend 30 min',session_later:'Later',session_expired:'Session expired. Please log in again.',
    side_remain:'Remaining:',side_login_btn:'Doctor Login',side_logged_label:'Logged In',side_logout:'Logout',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'Digital Implant Parts',home_title2:'Ordering System',home_desc:'Providing premium BIOTEM implant components directly to dental clinics across Thailand.',home_goto_shop:'Go to Shop',home_line_add:'Add LINE Friend',
    home_about:'About Us',home_biotem_desc:'Korean dental implant manufacturer. Expert in Implants with cutting-edge digital workflow solutions.',home_bioplant_desc:'Premium dental fixture manufacturing center in Bangkok. Supplying clinics across Southeast Asia.',home_categories:'Product Categories',home_contact:'Contact & Address',home_address:'Bangkok, Thailand',home_hours:'Mon–Fri 09:00–18:00',home_line_label:'Line Official',
    home_vision_label:'Our Vision',home_vision:'Redefining Implant Precision for Southeast Asia',home_stat1:'Certified',home_stat2:'Origin',home_stat3:'Coverage',home_biotem_short:'Expert of Implant · Korea',home_bioplant_short:'Manufacturing · Bangkok',home_mission_label:'Mission',home_mission:'Delivering premium Korean-manufactured dental implant components with fast, reliable service to clinics across Thailand and Southeast Asia.',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'Premium Dental Implant Parts',hero_bioplant_desc:'ISO-certified Korean manufacturing, delivered fast to your clinic.',hero_bioplant_cta:'Shop Now',
    hero_cnc_tag:'CNC Custom Abutment',hero_cnc_title:'Precision-Crafted Custom Solutions',hero_cnc_desc:'Made to your exact specs — from scan body to final restoration.',hero_cnc_cta:'Order Custom',
    sec_categories:'Product Categories',sec_see_more:'See All ›',cat_scan_body_desc:'Intra-Oral & Model types',cat_q_base_desc:'Zirconia abutment · H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'Milling compatible · N & R',cat_multi_unit_desc:'All-on-X · MUA · Scan Body',cat_3d_analog_desc:'GeoMedi Stone & 3D Model',
    sec_forum_preview:'Clinical Discussion',sec_forum_more:'View All ›',home_forum_empty:'No posts yet. Start a discussion!',
    sec_events_preview:'Upcoming Events',sec_events_more:'View All ›',home_events_empty:'No upcoming events',
    sec_webzine:'Webzine',sec_webzine_sub:'Clinical cases & product updates',sec_webzine_coming:'Coming Soon — Stay tuned',
    nav_webzine:'WEBZINE',wz_cat_all:'All',wz_cat_implant:'Implant Cases',wz_cat_prosthetic:'Prosthetic Cases',wz_cat_review:'Product Reviews',wz_cat_news:'Industry News',wz_cat_education:'Education',
    wz_empty:'No articles yet.',wz_write_btn:'Write Article',wz_form_title:'New Article',wz_title_ph:'Article title',wz_thumb_ph:'Click to upload thumbnail',wz_body_ph:'Write article body (Markdown supported)',wz_submit_btn:'Publish',wz_fill_alert:'Please fill in title and body.',wz_delete_confirm:'Delete this article?',
    shop_hint:'Select a category to order',shop_select:'SELECT ›',shop_each:'each',
    order_add_cart:'Add to Cart',order_qty_error:'Please enter at least 1 quantity.',
    cart_title:'My Cart',cart_total:'TOTAL',cart_checkout:'CHECKOUT',cart_close:'Close',cart_empty:'Cart is empty!',
    shop_specs:'Specifications & Qty',shop_in_stock:'In Stock',shop_out_of_stock:'Out of Stock',shop_my_orders:'My Orders',shop_product_count:'products',cart_bar_tap:'Tap to view cart',cart_bar_items:'items',cart_added:'Added to cart!',
    addr_title:'Delivery Info',addr_clinic_ph:'Clinic Name',addr_phone_ph:'Phone Number',addr_addr_ph:'Full Address',addr_qr_btn:'GENERATE QR',addr_back:'← Back',addr_fill_error:'Please fill in all delivery info.',
    qr_label:'Scan to Pay',qr_summary_title:'Order Summary',qr_total:'TOTAL',qr_complete:'PAYMENT COMPLETE',
    used_contact_title:'Contact Seller',used_contact_close:'Close',
    custom_tab_new:'New Order',custom_tab_list:'My Orders',custom_form_title:'Custom Abutment Order',custom_delivery_title:'Delivery Info',custom_clinic_ph:'Clinic / Lab Name',custom_addr_ph:'Delivery Address',custom_phone_ph:'Contact Number',custom_line_ph:'Line ID (for notifications)',custom_submit:'Submit Order',custom_submit_note:'Order confirmation will be sent via Line',custom_empty:'No orders yet',
    case_label:'Case #',case_remove:'✕ Remove',case_patient_ph:'Patient ID (anonymous ok, e.g. P001)',case_tooth_hint:'Select teeth · Tap to toggle',upper_jaw:'Upper Jaw',lower_jaw:'Lower Jaw',jaw_border:'Arch Boundary',selected_teeth:'Selected Teeth —',sel_count_suffix:'',brand_ph:'Select implant brand',size_ph:'Size (e.g. Ø4.0 / L10)',color_ph:'Tooth color (VITA)',case_add:'+ Add Case',stl_label:'Upload STL Files (up to 10)',stl_hint:'Drag & drop or tap to select .stl files',memo_ph:'Special requests (optional)',anon_patient:'Anonymous',case_deadline_label:'Delivery Deadline',
    err_fill_delivery:'Please enter clinic name, address, and phone number.',err_select_tooth:'Case #%: Please select at least 1 tooth.',err_fill_tooth:'Case #% Tooth #%: Please enter implant brand and size.',err_add_case:'Please add at least 1 case.',
    order_success_msg:'✅ Order submitted!\nOrder #: %\nCases: % / Teeth: %',order_success_line:'\nConfirmation sent via Line.',
    status_label:'Progress',case_detail:'Case Details',teeth_count:' teeth',cases_unit:' cases',teeth_total_prefix:'',patient_label:'Patient: ',no_tooth_info:'(no tooth data)',case_nr:'Case #',
    used_sell_title:'Sell Used Parts',used_name_ph:'Part Name',used_code_ph:'Product Code',used_price_ph:'Price (THB)',cond_new:'Like New',cond_good:'Good',cond_fair:'Fair',used_desc_ph:'Condition details...',used_contact_ph:'Contact (Line ID / Phone)',used_post_btn:'POST FOR SALE',used_list_title:'Available Used Parts',used_contact_btn:'Contact',used_delete_btn:'Delete',used_empty:'No used parts listed yet',used_fill_error:'Please enter part name, price, and contact.',
    forum_new_post:'New Post',forum_title_ph:'Title',forum_body_ph:'Write your message...',forum_post_btn:'POST',
    settings_lang:'Language',settings_account:'Account',settings_license:'License:',settings_save_btn:'Save Language',settings_saved_msg:'Language saved!',settings_pending:'Select a language then press Save.',
    pe_title:'✏️ Edit My Info',pe_subtitle:'Editable Fields',pe_email:'Email',pe_phone:'Phone Number',pe_address:'Address',pe_clinic:'Clinic Name',pe_save:'Save',pe_cancel:'Cancel',pe_email_ph:'Email address',pe_phone_ph:'Phone number',pe_address_ph:'Address',pe_clinic_ph:'Clinic name',
    profile_title:'👤 My Info',profile_edit_btn:'Edit',profile_login_msg:'Please log in to view.',profile_saved_msg:'✅ Saved!',profile_no_change:'(cannot change)',prof_nickname:'Nickname',prof_doctor:'Doctor Name',login_required:'Login required.',
    factory_subtitle:'Premium fixture manufacturing center in Bangkok',
    tooth_11:'Central Incisor',tooth_12:'Lateral Incisor',tooth_13:'Canine',tooth_14:'1st Premolar',tooth_15:'2nd Premolar',tooth_16:'1st Molar',tooth_17:'2nd Molar',
    upper:'Upper',lower:'Lower',
    stage_received:'Order Received',stage_stl:'STL Review',stage_design:'Designing',stage_cnc:'CNC Production',stage_qc:'Quality Check',stage_shipping:'Shipping',stage_done:'Delivered',stage_submitted:'Submitted',stage_confirmed:'Confirmed',stage_design_ready:'Design Review',stage_design_revision:'Design Revision',stage_approved:'Design Approved',stage_milling:'CNC Milling',stage_shipped:'Shipped',
    line_deadline:'Deadline',line_memo:'Memo',line_total_cases:'Total % cases / % teeth',
    reg_privacy_agree_prefix:'I have read and agree to the',reg_privacy_link:'Privacy Policy',reg_privacy_agree_suffix:'(Thailand PDPA).',reg_privacy_error:'Please read and agree to the Privacy Policy to continue.',
    privacy_title:'Privacy Policy',privacy_close:'Close',
    used_photo_add:'Add Photo',shop_items:'items',
    forum_cat_implant:'🦷 Implant',forum_cat_prosthetic:'💎 Prosthetic',forum_cat_conservative:'🪥 Conservative',forum_cat_orthodontics:'🦷 Orthodontics',forum_cat_oral_surgery:'✂️ Oral Surgery',forum_cat_periodontics:'🌿 Periodontics',forum_cat_pediatric:'👶 Pediatric',forum_cat_radiology:'📷 Radiology',forum_cat_oral_medicine:'💊 Oral Medicine',forum_cat_preventive:'🛡 Preventive',forum_cat_general:'🏥 General',forum_photo_add:'📷 Add photos (max 5)',forum_empty:'No posts yet.',
    forum_write_btn:'✍️ Write Post',forum_close_form:'✕ Close',forum_cat_label:'Category',
    forum_region_label:'Region',forum_province_label:'Province',
    forum_region_all:'🌏 All',forum_region_north:'🏔 North',forum_region_northeast:'🌾 Northeast',forum_region_east:'🌊 East',forum_region_south:'🏝 South',forum_region_central:'🏙 Central',
    forum_comment_title:'💬 Comments',forum_comment_ph:'Write a comment...',forum_comment_submit:'Reply',forum_no_comments:'No comments yet.',forum_writing_as:'Writing as',
    custom_tab_list:'In Progress',custom_tab_done:'Completed',
    install_ios:'📱 <b>iPhone / Safari Install</b><br><br>① Tap the Share button <b>□↑</b> at the bottom<br>② Select <b>"Add to Home Screen"</b><br>③ Tap <b>"Add"</b>',
    install_android:'💻 <b>PC / Android Install</b><br><br>① Click the <b>install icon ⊕</b><br>&nbsp;&nbsp;&nbsp;in the browser address bar<br>② Click <b>"Install"</b><br><br>※ If no icon, open browser menu<br>&nbsp;&nbsp;&nbsp;→ "Install as App"',
    install_ok:'OK',
    design_waiting:'⏳ Waiting for design upload...',shipped_msg:'🚚 Your order has been shipped. Press the button below when received.',receive_btn:'📦 Mark as Received',
    edit_order_btn:'✏️ Edit',delete_order_btn:'🗑 Delete',review_history_label:'Review History (%)',
    done_orders_empty:'No completed orders.',done_status_label:'Done',done_cases_teeth_fmt:'% cases · % teeth',
    reg_nick_ph:'Nickname (required) — used for all activities',reg_email_ph:'Email address (required)',
    compose_title:'✉️ Send Message',compose_to_ph:'Recipient (nickname)',compose_subj_ph:'Subject',compose_body_ph:'Write your message...',compose_send:'Send',
    ship_carrier_custom_opt:'Enter manually',ship_carrier_ph:'Carrier name',ship_tracking_label:'Tracking Number',ship_tracking_ph:'Enter tracking number',ship_process_btn:'🚚 Process Shipping → Send LINE',
    leader_badge:'Region Leader',leader_assign:'Assign',leader_remove:'Remove Leader',leader_select_region:'Select region...',
    forum_pinned:'Pinned',forum_pin:'Pin',forum_unpin:'Unpin',forum_delete:'Delete',forum_delete_confirm:'Are you sure you want to delete this post?',event_delete_confirm:'Are you sure you want to delete this event?',
    admin_new_event_title:'Add New Event',admin_event_name_ph:'Event name',admin_event_loc_ph:'Location',admin_event_add_btn:'+ Add',admin_event_fill_alert:'Please fill in all fields.',
    meetup_create_btn:'Create Meetup',meetup_badge:'Meetup',event_badge:'Event',meetup_form_title:'Create a New Meetup',meetup_title_ph:'Meetup title',meetup_loc_ph:'Location',meetup_desc_ph:'Description (optional)',meetup_submit_btn:'Create Meetup',meetup_fill_alert:'Please fill in title, date, and location.',meetup_created_by:'Created by',
    rsvp_title:'RSVP',rsvp_attend:'✅ Attend',rsvp_not_attend:'❌ Not Attending',rsvp_attendees:'attendees',rsvp_attendee_list:'Attendee List',rsvp_no_attendees:'No attendees yet.',rsvp_login_required:'Please log in to RSVP.',rsvp_error:'RSVP failed. Please try again.',
    admin_orders_new:'New Orders',admin_orders_active:'In Progress',admin_orders_done:'Done',admin_orders_empty:'No orders.',
    shipped_status:'Shipped',carrier_label:'Carrier',tracking_label:'Tracking',received_status:'Received',teeth_colon_label:'Teeth:',
    wiz_step1:'Patient & Teeth',wiz_step2:'Brand',wiz_step3:'Shade & Note',wiz_step4:'STL',wiz_step5:'Confirm',wiz_next:'Next →',wiz_prev:'← Back',wiz_patient_label:'Patient ID',wiz_no_tooth_err:'Please select at least 1 tooth.',wiz_no_brand_err:'Please select an implant brand.',wiz_brand_all_hint:'Applies to all selected teeth',wiz_size_for_tooth:'Size (e.g. Ø4.0 / L10)',wiz_shade_label:'Tooth Shade (VITA)',wiz_stl_main_label:'STL / 3D Files',wiz_stl_main_hint:'Drag & drop or tap · Up to 10 files',wiz_confirm_title:'Order Summary',wiz_delivery_label:'Delivery Info',wiz_teeth_selected:'teeth selected',wiz_start_over:'Start New Order',wiz_size_table_title:'Size per tooth',
    used_post_toggle:'📸 List Used Item',used_close_form:'✕ Close',settings_my_orders:'📦 My Orders',settings_no_orders:'No orders yet',
    admin_panel_title:'Admin Panel',admin_total_members:'Total Members',admin_pending_orders:'Pending Orders',admin_today_signups:'New Today',
    admin_tab_orders:'Orders',admin_tab_users:'Members',admin_tab_custom:'Custom Orders',
    admin_order_date:'Date',admin_order_customer:'Customer',admin_order_total:'Total',admin_order_status:'Status',admin_change_status:'Change Status',
    admin_user_approve:'✅ Approve',admin_user_reject:'❌ Reject',admin_user_block:'🔒 Block',admin_user_unblock:'✅ Unblock',
    admin_user_pending_badge:'Pending',admin_user_active_badge:'Active',admin_user_blocked_badge:'Blocked',
    admin_custom_change_stage:'Change Stage',admin_pending_users_title:'⏳ Pending Approval',admin_all_users_title:'👥 All Members',
    admin_no_pending_users:'No pending approvals.',admin_loading:'Loading...',admin_load_fail:'Load failed',admin_no_users:'No members.',admin_error:'An error occurred.',
  },
  ko: {
    nav_home:'HOME',nav_shop:'SHOP',nav_custom:'CNC Custom Abut',nav_used:'중고마켓',nav_forum:'임상토론방',nav_events:'이벤트',nav_factory:'공장',nav_settings:'설정',
    pt_home:'Home',pt_shop:'Shop',pt_custom:'Custom Abutment',pt_used:'중고마켓',pt_forum:'임상토론방',pt_events:'Events',pt_factory:'Factory',pt_settings:'설정',
    login_subtitle:'의사 로그인',login_ph:'닉네임',login_password_ph:'비밀번호',login_btn:'로그인',login_cancel:'취소',login_error:'닉네임과 비밀번호를 입력해주세요.',login_verifying:'확인 중...',login_not_found:'닉네임이 없거나 비밀번호가 틀렸습니다.',login_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',login_register_link:'사용 신청하기 →',
    reg_title:'사용 신청',reg_subtitle:'정보를 입력하시면 24시간 내에 검토 후 승인해 드립니다.',reg_license_ph:'면허 번호 (필수)',reg_name_ph:'의사 이름 (필수)',reg_clinic_ph:'치과명 (필수)',reg_contact_ph:'전화번호 또는 Line ID (필수)',reg_password_ph:'비밀번호 (필수)',reg_password_confirm_ph:'비밀번호 확인 (필수)',reg_submit:'신청하기',reg_submitting:'신청 중...',reg_success:'신청이 접수되었습니다!\n관리자 승인 후 24시간 내에 연락드리겠습니다.',reg_error:'필수 항목을 모두 입력해주세요.',reg_pwd_mismatch:'비밀번호가 일치하지 않습니다.',reg_duplicate:'이미 등록된 닉네임입니다.',reg_network_error:'네트워크 오류가 발생했습니다. 다시 시도해주세요.',
    session_title:'세션 만료 임박',session_desc1:'로그인이',session_desc2:'후 만료됩니다.',session_q:'지금 연장하시겠어요?',session_extend:'30분 연장하기',session_later:'나중에',session_expired:'세션이 만료되었습니다. 다시 로그인해주세요.',
    side_remain:'남은 시간:',side_login_btn:'의사 로그인',side_logged_label:'로그인 중',side_logout:'로그아웃',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'디지털 임플란트 부품',home_title2:'주문 시스템',home_desc:'태국 전역 치과에 프리미엄 BIOTEM 임플란트 부품을 직접 공급합니다.',home_goto_shop:'쇼핑몰로 이동',home_line_add:'LINE 친구 추가',
    home_about:'회사 소개',home_biotem_desc:'한국 치과 임플란트 제조사. 첨단 디지털 워크플로우 솔루션을 갖춘 임플란트 전문 기업.',home_bioplant_desc:'방콕의 프리미엄 치과 부품 제조 센터. 동남아시아 전역 치과에 공급.',home_categories:'제품 카테고리',home_contact:'연락처 및 주소',home_address:'태국 방콕',home_hours:'월–금 09:00–18:00',home_line_label:'Line 공식 계정',
    home_vision_label:'비전',home_vision:'동남아시아 임플란트 정밀도의 새 기준을 제시합니다',home_stat1:'인증',home_stat2:'원산지',home_stat3:'공급 범위',home_biotem_short:'임플란트 전문 · 한국',home_bioplant_short:'생산 센터 · 방콕',home_mission_label:'미션',home_mission:'한국 제조 프리미엄 치과 임플란트 부품을 태국 및 동남아시아 전역 치과에 신속하고 신뢰할 수 있는 서비스로 공급합니다.',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'프리미엄 치과 임플란트 부품',hero_bioplant_desc:'한국 ISO 인증 제조, 클리닉 빠른 배송',hero_bioplant_cta:'쇼핑몰로',
    hero_cnc_tag:'CNC 커스텀 어버트먼트',hero_cnc_title:'정밀 맞춤 제작',hero_cnc_desc:'스캔바디부터 최종 보철까지 사양에 맞게 제작',hero_cnc_cta:'주문하기',
    sec_categories:'제품 카테고리',sec_see_more:'전체 보기 ›',cat_scan_body_desc:'구강 내 · 모델용',cat_q_base_desc:'지르코니아 어버트먼트 H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'밀링 호환 · N · R 타입',cat_multi_unit_desc:'All-on-X · MUA · 스캔바디',cat_3d_analog_desc:'GeoMedi 스톤 & 3D 모델',
    sec_forum_preview:'임상 토론방',sec_forum_more:'전체 보기 ›',home_forum_empty:'아직 게시물이 없습니다.',
    sec_events_preview:'예정 이벤트',sec_events_more:'전체 보기 ›',home_events_empty:'예정된 이벤트가 없습니다.',
    sec_webzine:'웹진',sec_webzine_sub:'임상 케이스 & 제품 업데이트',sec_webzine_coming:'준비 중 — 곧 공개됩니다',
    nav_webzine:'웹진',wz_cat_all:'전체',wz_cat_implant:'임플란트 케이스',wz_cat_prosthetic:'보철 케이스',wz_cat_review:'제품 리뷰',wz_cat_news:'업계 뉴스',wz_cat_education:'교육 콘텐츠',
    wz_empty:'아직 기사가 없습니다.',wz_write_btn:'기사 작성',wz_form_title:'새 기사',wz_title_ph:'기사 제목',wz_thumb_ph:'클릭하여 썸네일 업로드',wz_body_ph:'기사 본문 작성 (마크다운 지원)',wz_submit_btn:'발행',wz_fill_alert:'제목과 본문을 입력해주세요.',wz_delete_confirm:'이 기사를 삭제하시겠습니까?',
    shop_hint:'카테고리를 선택하여 주문하세요',shop_select:'선택 ›',shop_each:'개당',
    order_add_cart:'장바구니 추가',order_qty_error:'수량을 1개 이상 입력해주세요.',
    cart_title:'장바구니',cart_total:'합계',cart_checkout:'결제하기',cart_close:'닫기',cart_empty:'장바구니가 비어 있습니다!',
    shop_specs:'규격 및 수량',shop_in_stock:'재고 있음',shop_out_of_stock:'품절',shop_my_orders:'내 주문 현황',shop_product_count:'개 제품',cart_bar_tap:'탭하여 보기',cart_bar_items:'개',cart_added:'장바구니에 추가됨!',
    addr_title:'배송 정보',addr_clinic_ph:'치과명',addr_phone_ph:'전화번호',addr_addr_ph:'상세 주소',addr_qr_btn:'QR 생성',addr_back:'← 뒤로',addr_fill_error:'배송 정보를 모두 입력해주세요.',
    qr_label:'QR로 결제',qr_summary_title:'주문 요약',qr_total:'합계',qr_complete:'결제 완료',
    used_contact_title:'판매자 연락처',used_contact_close:'닫기',
    custom_tab_new:'새 주문',custom_tab_list:'내 주문 현황',custom_form_title:'커스텀 어버트먼트 주문',custom_delivery_title:'납품 정보',custom_clinic_ph:'치과명 / 기공소명',custom_addr_ph:'납품 주소',custom_phone_ph:'연락처',custom_line_ph:'Line ID (알림 수신용)',custom_submit:'주문 제출하기',custom_submit_note:'주문 접수 시 Line으로 확인 메시지가 발송됩니다',custom_empty:'아직 주문 내역이 없어요',
    case_label:'케이스 #',case_remove:'✕ 삭제',case_patient_ph:'환자 ID (익명 가능, 예: P001)',case_tooth_hint:'치아 선택 · 탭하여 선택/해제',upper_jaw:'상악 (Upper Jaw)',lower_jaw:'하악 (Lower Jaw)',jaw_border:'치열 경계',selected_teeth:'선택된 치아 —',sel_count_suffix:'개',brand_ph:'임플란트 종류 선택',size_ph:'사이즈 (예: Ø4.0 / L10)',color_ph:'치아 색상 (VITA)',case_add:'+ 케이스 추가',stl_label:'STL 파일 업로드 (최대 10개)',stl_hint:'드래그하거나 탭하여 .stl 파일 선택',memo_ph:'특별 요청사항 (선택)',anon_patient:'익명',case_deadline_label:'납품 기한',
    err_fill_delivery:'치과명, 납품 주소, 연락처를 입력해주세요.',err_select_tooth:'케이스 #%: 치아를 최소 1개 선택해주세요.',err_fill_tooth:'케이스 #% 치아 #%: 임플란트 종류와 사이즈를 입력해주세요.',err_add_case:'케이스를 최소 1개 추가해주세요.',
    order_success_msg:'✅ 주문이 접수되었습니다!\n주문번호: %\n케이스: %개 / 치아: %개',order_success_line:'\nLine으로 확인 메시지를 보내드렸습니다.',
    status_label:'진행 상황',case_detail:'케이스 상세',teeth_count:'개 치아',cases_unit:'개',teeth_total_prefix:'총 ',patient_label:'환자: ',no_tooth_info:'치아 정보 없음',case_nr:'케이스 #',
    used_sell_title:'중고 부품 판매',used_name_ph:'부품명',used_code_ph:'제품 코드',used_price_ph:'가격 (THB)',cond_new:'거의 새것',cond_good:'양호',cond_fair:'보통',used_desc_ph:'상태 설명...',used_contact_ph:'연락처 (Line ID / 전화번호)',used_post_btn:'판매 등록',used_list_title:'판매 중인 중고 부품',used_contact_btn:'연락하기',used_delete_btn:'삭제',used_empty:'아직 등록된 중고 물품이 없어요',used_fill_error:'부품명, 가격, 연락처를 입력해주세요.',
    forum_new_post:'새 글 작성',forum_title_ph:'제목',forum_body_ph:'내용을 작성해주세요...',forum_post_btn:'게시',
    settings_lang:'언어 설정',settings_account:'계정',settings_license:'면허번호:',settings_save_btn:'언어 저장',settings_saved_msg:'언어가 저장되었습니다!',settings_pending:'언어를 선택하고 저장 버튼을 눌러주세요.',
    pe_title:'✏️ 내 정보 수정',pe_subtitle:'수정 가능 항목',pe_email:'이메일',pe_phone:'전화번호',pe_address:'주소',pe_clinic:'치과이름',pe_save:'저장',pe_cancel:'취소',pe_email_ph:'이메일 주소',pe_phone_ph:'전화번호',pe_address_ph:'주소',pe_clinic_ph:'치과이름',
    profile_title:'👤 내 정보',profile_edit_btn:'수정',profile_login_msg:'로그인 후 확인 가능합니다.',profile_saved_msg:'✅ 저장되었습니다!',profile_no_change:'(변경불가)',prof_nickname:'닉네임',prof_doctor:'의사이름',login_required:'로그인이 필요합니다.',
    factory_subtitle:'방콕의 프리미엄 임플란트 제조 센터',
    tooth_11:'중절치',tooth_12:'측절치',tooth_13:'견치',tooth_14:'제1소구치',tooth_15:'제2소구치',tooth_16:'제1대구치',tooth_17:'제2대구치',
    upper:'상악',lower:'하악',
    stage_received:'주문 접수',stage_stl:'STL 검토',stage_design:'디자인 중',stage_cnc:'CNC 생산',stage_qc:'품질 검사',stage_shipping:'배송 중',stage_done:'납품 완료',stage_submitted:'접수 대기',stage_confirmed:'접수 확인',stage_design_ready:'디자인 검토',stage_design_revision:'디자인 수정 중',stage_approved:'제작 승인',stage_milling:'CNC 밀링 중',stage_shipped:'배송 중',
    line_deadline:'납기',line_memo:'메모',line_total_cases:'총 %케이스 / %치아',
    reg_privacy_agree_prefix:'다음 약관에 동의합니다:',reg_privacy_link:'개인정보 처리방침',reg_privacy_agree_suffix:'(태국 PDPA)',reg_privacy_error:'개인정보 처리방침에 동의 후 계속할 수 있습니다.',
    privacy_title:'개인정보 처리방침',privacy_close:'닫기',
    used_photo_add:'사진 추가',shop_items:'개',
    forum_cat_implant:'🦷 임플란트',forum_cat_prosthetic:'💎 보철',forum_cat_conservative:'🪥 보존',forum_cat_orthodontics:'🦷 교정',forum_cat_oral_surgery:'✂️ 구강외과',forum_cat_periodontics:'🌿 치주',forum_cat_pediatric:'👶 소아치과',forum_cat_radiology:'📷 영상치의학',forum_cat_oral_medicine:'💊 구강내과',forum_cat_preventive:'🛡 예방치과',forum_cat_general:'🏥 통합진료',forum_photo_add:'📷 사진 추가 (최대 5장)',forum_empty:'게시물이 없습니다.',
    forum_write_btn:'✍️ 글쓰기',forum_close_form:'✕ 닫기',forum_cat_label:'카테고리',
    forum_region_label:'지역',forum_province_label:'주(Province)',
    forum_region_all:'🌏 전체',forum_region_north:'🏔 북부',forum_region_northeast:'🌾 동북부',forum_region_east:'🌊 동부',forum_region_south:'🏝 남부',forum_region_central:'🏙 중부',
    forum_comment_title:'💬 댓글',forum_comment_ph:'댓글을 입력하세요...',forum_comment_submit:'등록',forum_no_comments:'아직 댓글이 없습니다.',forum_writing_as:'작성자',
    custom_tab_list:'진행중',custom_tab_done:'완료',
    install_ios:'📱 <b>iPhone / Safari 설치 방법</b><br><br>① 하단 공유 버튼 <b>□↑</b> 탭<br>② <b>"홈 화면에 추가"</b> 선택<br>③ <b>"추가"</b> 탭',
    install_android:'💻 <b>PC / Android 설치 방법</b><br><br>① 브라우저 주소창 우측의<br>&nbsp;&nbsp;&nbsp;<b>설치 아이콘 ⊕</b> 클릭<br>② <b>"설치"</b> 클릭<br><br>※ 아이콘이 없으면 브라우저 메뉴<br>&nbsp;&nbsp;&nbsp;→ "앱으로 설치"',
    install_ok:'확인',
    design_waiting:'⏳ 디자인 업로드 대기 중...',shipped_msg:'🚚 배송이 출발했습니다. 제품 수령 후 아래 버튼을 눌러주세요.',receive_btn:'📦 수령 완료',
    edit_order_btn:'✏️ 수정',delete_order_btn:'🗑 삭제',review_history_label:'검토 이력 (%회)',
    done_orders_empty:'완료된 주문이 없습니다.',done_status_label:'완료',done_cases_teeth_fmt:'%케이스 · %치아',
    reg_nick_ph:'닉네임 (필수) — 모든 활동에 사용됩니다',reg_email_ph:'이메일주소 (필수)',
    compose_title:'✉️ 쪽지 보내기',compose_to_ph:'받는 사람 (닉네임)',compose_subj_ph:'제목',compose_body_ph:'내용을 입력하세요...',compose_send:'보내기',
    ship_carrier_custom_opt:'직접 입력',ship_carrier_ph:'배송사 이름 입력',ship_tracking_label:'송장번호',ship_tracking_ph:'송장번호 입력',ship_process_btn:'🚚 배송 처리 → LINE 발송',
    leader_badge:'지역 리더',leader_assign:'리더 지정',leader_remove:'리더 해임',leader_select_region:'지역 선택...',
    forum_pinned:'고정됨',forum_pin:'고정',forum_unpin:'고정 해제',forum_delete:'삭제',forum_delete_confirm:'이 게시물을 삭제하시겠습니까?',event_delete_confirm:'이 이벤트를 삭제하시겠습니까?',
    admin_new_event_title:'새 이벤트 추가',admin_event_name_ph:'이벤트명',admin_event_loc_ph:'장소',admin_event_add_btn:'+ 추가',admin_event_fill_alert:'모든 항목을 입력해주세요.',
    meetup_create_btn:'모임 만들기',meetup_badge:'모임',event_badge:'이벤트',meetup_form_title:'새 모임 만들기',meetup_title_ph:'모임 제목',meetup_loc_ph:'장소',meetup_desc_ph:'설명 (선택)',meetup_submit_btn:'모임 생성',meetup_fill_alert:'제목, 날짜, 장소를 모두 입력해주세요.',meetup_created_by:'만든 사람',
    rsvp_title:'참석 여부',rsvp_attend:'✅ 참석',rsvp_not_attend:'❌ 불참',rsvp_attendees:'명 참석',rsvp_attendee_list:'참석자 목록',rsvp_no_attendees:'아직 참석자가 없습니다.',rsvp_login_required:'참석하려면 로그인해주세요.',rsvp_error:'참석 처리에 실패했습니다. 다시 시도해주세요.',
    admin_orders_new:'새 주문',admin_orders_active:'진행중',admin_orders_done:'완료',admin_orders_empty:'주문이 없습니다.',
    shipped_status:'배송 완료',carrier_label:'배송사',tracking_label:'송장',received_status:'수령 완료',teeth_colon_label:'치아:',
    wiz_step1:'환자 & 치아',wiz_step2:'브랜드',wiz_step3:'쉐이드 & 메모',wiz_step4:'STL',wiz_step5:'확인 & 제출',wiz_next:'다음 →',wiz_prev:'← 이전',wiz_patient_label:'환자 ID',wiz_no_tooth_err:'치아를 최소 1개 선택해주세요.',wiz_no_brand_err:'임플란트 브랜드를 선택해주세요.',wiz_brand_all_hint:'선택한 모든 치아에 적용',wiz_size_for_tooth:'사이즈 (예: Ø4.0 / L10)',wiz_shade_label:'치아 색상 (VITA)',wiz_stl_main_label:'STL / 3D 파일',wiz_stl_main_hint:'드래그하거나 탭하여 선택 · 최대 10개',wiz_confirm_title:'주문 확인',wiz_delivery_label:'납품 정보',wiz_teeth_selected:'개 치아 선택',wiz_start_over:'새 주문 시작',wiz_size_table_title:'치아별 사이즈',
    used_post_toggle:'📸 중고 물품 등록',used_close_form:'✕ 닫기',settings_my_orders:'📦 나의 주문',settings_no_orders:'주문 내역이 없습니다.',
    admin_panel_title:'관리자 패널',admin_total_members:'총 회원수',admin_pending_orders:'대기중 주문',admin_today_signups:'오늘 신규가입',
    admin_tab_orders:'주문관리',admin_tab_users:'회원관리',admin_tab_custom:'커스텀주문',
    admin_order_date:'날짜',admin_order_customer:'고객명',admin_order_total:'총액',admin_order_status:'상태',admin_change_status:'상태 변경',
    admin_user_approve:'✅ 승인',admin_user_reject:'❌ 거절',admin_user_block:'🔒 차단',admin_user_unblock:'✅ 차단해제',
    admin_user_pending_badge:'승인대기',admin_user_active_badge:'활성',admin_user_blocked_badge:'차단됨',
    admin_custom_change_stage:'단계 변경',admin_pending_users_title:'⏳ 승인 대기 회원',admin_all_users_title:'👥 전체 회원',
    admin_no_pending_users:'승인 대기 회원이 없습니다.',admin_loading:'로딩 중...',admin_load_fail:'로드 실패',admin_no_users:'회원이 없습니다.',admin_error:'오류가 발생했습니다.',
  },
  zh: {
    nav_home:'主页',nav_shop:'商城',nav_custom:'CNC Custom Abut',nav_used:'二手市场',nav_forum:'临床讨论',nav_events:'活动',nav_factory:'工厂',nav_settings:'设置',
    pt_home:'主页',pt_shop:'商城',pt_custom:'定制基台',pt_used:'二手市场',pt_forum:'临床讨论',pt_events:'活动',pt_factory:'工厂',pt_settings:'设置',
    login_subtitle:'医生登录',login_ph:'昵称',login_password_ph:'密码',login_btn:'登录',login_cancel:'取消',login_error:'请输入昵称和密码。',login_verifying:'验证中...',login_not_found:'昵称不存在或密码错误。',login_network_error:'网络错误，请重试。',login_register_link:'申请使用 →',
    reg_title:'申请使用',reg_subtitle:'填写信息后，管理员将在24小时内审核并联系您。',reg_license_ph:'执照号码（必填）',reg_name_ph:'医生姓名（必填）',reg_clinic_ph:'诊所名称（必填）',reg_contact_ph:'电话或 Line ID（必填）',reg_password_ph:'密码（必填）',reg_password_confirm_ph:'确认密码（必填）',reg_submit:'提交申请',reg_submitting:'提交中...',reg_success:'申请已提交！\n审核通过后将在24小时内与您联系。',reg_error:'请填写所有必填项。',reg_pwd_mismatch:'两次密码不一致。',reg_duplicate:'该昵称已被注册。',reg_network_error:'网络错误，请重试。',
    session_title:'会话即将过期',session_desc1:'登录将在',session_desc2:'后过期。',session_q:'是否现在延长？',session_extend:'延长30分钟',session_later:'稍后',session_expired:'会话已过期，请重新登录。',
    side_remain:'剩余时间：',side_login_btn:'医生登录',side_logged_label:'已登录',side_logout:'退出登录',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'数字种植体零件',home_title2:'订购系统',home_desc:'将优质BIOTEM种植体配件直接提供给泰国各地牙科诊所。',home_goto_shop:'前往商城',home_line_add:'添加LINE好友',
    home_vision_label:'我们的愿景',home_vision:'重新定义东南亚种植精准标准',home_stat1:'已认证',home_stat2:'原产地',home_stat3:'覆盖范围',home_biotem_short:'种植专家 · 韩国',home_bioplant_short:'制造中心 · 曼谷',home_mission_label:'使命',home_mission:'将韩国制造的优质牙科种植配件以快速可靠的服务输送至泰国及东南亚各地诊所。',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    home_about:'关于我们',home_biotem_desc:'韩国牙科种植体制造商，专注于尖端数字化工作流解决方案。',home_bioplant_desc:'曼谷高端牙科配件制造中心，服务东南亚各地诊所。',home_categories:'产品类别',home_contact:'联系方式与地址',home_address:'泰国曼谷',home_hours:'周一至周五 09:00–18:00',home_line_label:'Line 官方账号',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'优质牙科种植体配件',hero_bioplant_desc:'韩国ISO认证制造，快速配送至您的诊所',hero_bioplant_cta:'立即购买',
    hero_cnc_tag:'CNC定制基台',hero_cnc_title:'精密定制解决方案',hero_cnc_desc:'从扫描体到最终修复，按您规格制造',hero_cnc_cta:'定制订购',
    sec_categories:'产品类别',sec_see_more:'查看全部 ›',cat_scan_body_desc:'口内 & 模型型',cat_q_base_desc:'氧化锦基台 H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'铣切兼容 · N & R',cat_multi_unit_desc:'All-on-X · MUA · 扫描体',cat_3d_analog_desc:'GeoMedi 石膏 & 3D模型',
    sec_forum_preview:'临床讨论',sec_forum_more:'查看全部 ›',home_forum_empty:'暂无帖子，快来发帖吧！',
    sec_events_preview:'近期活动',sec_events_more:'查看全部 ›',home_events_empty:'暂无近期活动',
    sec_webzine:'网络杂志',sec_webzine_sub:'临床案例 & 产品更新',sec_webzine_coming:'即将推出，敬请期待',
    nav_webzine:'杂志',wz_cat_all:'全部',wz_cat_implant:'种植案例',wz_cat_prosthetic:'修复案例',wz_cat_review:'产品评测',wz_cat_news:'行业新闻',wz_cat_education:'教育内容',
    wz_empty:'暂无文章。',wz_write_btn:'撰写文章',wz_form_title:'新文章',wz_title_ph:'文章标题',wz_thumb_ph:'点击上传封面图',wz_body_ph:'撰写文章内容（支持Markdown）',wz_submit_btn:'发布',wz_fill_alert:'请填写标题和正文。',wz_delete_confirm:'确定要删除这篇文章吗？',
    shop_hint:'请选择类别进行订购',shop_select:'选择 ›',shop_each:'件',
    order_add_cart:'加入购物车',order_qty_error:'请输入至少1件数量。',
    cart_title:'购物车',cart_total:'合计',cart_checkout:'结账',cart_close:'关闭',cart_empty:'购物车为空！',
    shop_specs:'规格及数量',shop_in_stock:'有货',shop_out_of_stock:'缺货',shop_my_orders:'我的订单',shop_product_count:'款产品',cart_bar_tap:'点击查看购物车',cart_bar_items:'件',cart_added:'已加入购物车!',
    addr_title:'配送信息',addr_clinic_ph:'诊所名称',addr_phone_ph:'电话号码',addr_addr_ph:'详细地址',addr_qr_btn:'生成二维码',addr_back:'← 返回',addr_fill_error:'请填写所有配送信息。',
    qr_label:'扫码支付',qr_summary_title:'订单摘要',qr_total:'合计',qr_complete:'支付完成',
    used_contact_title:'联系卖家',used_contact_close:'关闭',
    custom_tab_new:'新订单',custom_tab_list:'我的订单',custom_form_title:'定制基台订单',custom_delivery_title:'配送信息',custom_clinic_ph:'诊所/技工所名称',custom_addr_ph:'配送地址',custom_phone_ph:'联系电话',custom_line_ph:'Line ID（接收通知）',custom_submit:'提交订单',custom_submit_note:'订单提交后将通过Line发送确认消息',custom_empty:'暂无订单记录',
    case_label:'病例 #',case_remove:'✕ 删除',case_patient_ph:'患者ID（可匿名，如：P001）',case_tooth_hint:'选择牙齿 · 点击切换',upper_jaw:'上颌 (Upper Jaw)',lower_jaw:'下颌 (Lower Jaw)',jaw_border:'牙弓分界',selected_teeth:'已选牙齿 —',sel_count_suffix:'颗',brand_ph:'选择种植体品牌',size_ph:'尺寸（如：Ø4.0 / L10）',color_ph:'牙色（VITA）',case_add:'+ 添加病例',stl_label:'上传STL文件（最多10个）',stl_hint:'可同时选择多个.stl文件',memo_ph:'特殊要求（选填）',anon_patient:'匿名',case_deadline_label:'交货期限',
    err_fill_delivery:'请填写诊所名称、地址和联系电话。',err_select_tooth:'病例#%：请至少选择1颗牙齿。',err_fill_tooth:'病例#% 牙齿#%：请填写种植体品牌和尺寸。',err_add_case:'请至少添加1个病例。',
    order_success_msg:'✅ 订单已提交！\n订单号：%\n病例：%个 / 牙齿：%颗',order_success_line:'\n确认消息已通过Line发送。',
    status_label:'进度',case_detail:'病例详情',teeth_count:'颗牙',cases_unit:'个',teeth_total_prefix:'共',patient_label:'患者：',no_tooth_info:'（无牙齿信息）',case_nr:'病例 #',
    used_sell_title:'出售二手零件',used_name_ph:'零件名称',used_code_ph:'产品编码',used_price_ph:'价格（泰铢）',cond_new:'近全新',cond_good:'良好',cond_fair:'一般',used_desc_ph:'状况描述...',used_contact_ph:'联系方式（Line ID / 电话）',used_post_btn:'发布出售',used_list_title:'可购二手零件',used_contact_btn:'联系',used_delete_btn:'删除',used_empty:'暂无二手零件',used_fill_error:'请填写零件名称、价格和联系方式。',
    forum_new_post:'发布新帖',forum_title_ph:'标题',forum_body_ph:'写下您的内容...',forum_post_btn:'发布',
    settings_lang:'语言设置',settings_account:'账户',settings_license:'执照号：',settings_save_btn:'保存语言',settings_saved_msg:'语言已保存！',settings_pending:'请选择语言后点击保存。',
    pe_title:'✏️ 编辑我的信息',pe_subtitle:'可修改项目',pe_email:'电子邮件',pe_phone:'电话号码',pe_address:'地址',pe_clinic:'诊所名称',pe_save:'保存',pe_cancel:'取消',pe_email_ph:'电子邮件地址',pe_phone_ph:'电话号码',pe_address_ph:'地址',pe_clinic_ph:'诊所名称',
    profile_title:'👤 我的信息',profile_edit_btn:'编辑',profile_login_msg:'请登录后查看。',profile_saved_msg:'✅ 已保存！',profile_no_change:'(不可更改)',prof_nickname:'昵称',prof_doctor:'医生姓名',login_required:'需要登录。',
    factory_subtitle:'曼谷高端种植体制造中心',
    tooth_11:'中切牙',tooth_12:'侧切牙',tooth_13:'尖牙',tooth_14:'第一前磨牙',tooth_15:'第二前磨牙',tooth_16:'第一磨牙',tooth_17:'第二磨牙',
    upper:'上颌',lower:'下颌',
    stage_received:'已接收订单',stage_stl:'STL审核',stage_design:'设计中',stage_cnc:'CNC生产',stage_qc:'质量检验',stage_shipping:'配送中',stage_done:'已交付',stage_submitted:'待确认',stage_confirmed:'已确认',stage_design_ready:'设计审核',stage_design_revision:'设计修改中',stage_approved:'已批准',stage_milling:'CNC加工中',stage_shipped:'已发货',
    line_deadline:'期限',line_memo:'备注',line_total_cases:'共 %个病例 / %颗牙',
    reg_privacy_agree_prefix:'我已阅读并同意',reg_privacy_link:'隐私政策',reg_privacy_agree_suffix:'（泰国PDPA）。',reg_privacy_error:'请阅读并同意隐私政策后继续。',
    privacy_title:'隐私政策',privacy_close:'关闭',
    used_photo_add:'添加照片',shop_items:'件',
    forum_cat_implant:'🦷 种植',forum_cat_prosthetic:'💎 修复',forum_cat_conservative:'🪥 牙体牙髓',forum_cat_orthodontics:'🦷 正畸',forum_cat_oral_surgery:'✂️ 口腔外科',forum_cat_periodontics:'🌿 牙周',forum_cat_pediatric:'👶 儿童口腔',forum_cat_radiology:'📷 口腔影像',forum_cat_oral_medicine:'💊 口腔内科',forum_cat_preventive:'🛡 预防',forum_cat_general:'🏥 综合诊疗',forum_photo_add:'📷 添加照片（最多5张）',forum_empty:'暂无帖子。',
    forum_write_btn:'✍️ 发帖',forum_close_form:'✕ 关闭',forum_cat_label:'分类',
    forum_region_label:'地区',forum_province_label:'府',
    forum_region_all:'🌏 全部',forum_region_north:'🏔 北部',forum_region_northeast:'🌾 东北部',forum_region_east:'🌊 东部',forum_region_south:'🏝 南部',forum_region_central:'🏙 中部',
    forum_comment_title:'💬 评论',forum_comment_ph:'写评论...',forum_comment_submit:'提交',forum_no_comments:'暂无评论。',forum_writing_as:'以...发布',
    custom_tab_list:'进行中',custom_tab_done:'已完成',
    install_ios:'📱 <b>iPhone / Safari 安装方法</b><br><br>① 点击底部分享按钮 <b>□↑</b><br>② 选择 <b>"添加到主屏幕"</b><br>③ 点击 <b>"添加"</b>',
    install_android:'💻 <b>PC / Android 安装方法</b><br><br>① 点击浏览器地址栏右侧的<br>&nbsp;&nbsp;&nbsp;<b>安装图标 ⊕</b><br>② 点击 <b>"安装"</b><br><br>※ 若无图标，打开浏览器菜单<br>&nbsp;&nbsp;&nbsp;→ "安装为应用"',
    install_ok:'确定',
    design_waiting:'⏳ 等待设计文件上传...',shipped_msg:'🚚 您的订单已发货。收到后请按下方按钮。',receive_btn:'📦 确认收货',
    edit_order_btn:'✏️ 编辑',delete_order_btn:'🗑 删除',review_history_label:'审核历史（%次）',
    done_orders_empty:'暂无已完成订单。',done_status_label:'已完成',done_cases_teeth_fmt:'%个病例 · %颗牙',
    reg_nick_ph:'昵称（必填）— 用于所有活动',reg_email_ph:'电子邮件地址（必填）',
    compose_title:'✉️ 发送消息',compose_to_ph:'收件人（昵称）',compose_subj_ph:'主题',compose_body_ph:'写下您的内容...',compose_send:'发送',
    ship_carrier_custom_opt:'手动输入',ship_carrier_ph:'快递公司名称',ship_tracking_label:'快递单号',ship_tracking_ph:'输入快递单号',ship_process_btn:'🚚 处理发货 → 发送LINE',
    leader_badge:'区域负责人',leader_assign:'指定',leader_remove:'撤销负责人',leader_select_region:'选择区域...',
    forum_pinned:'已置顶',forum_pin:'置顶',forum_unpin:'取消置顶',forum_delete:'删除',forum_delete_confirm:'确定要删除此帖子吗？',event_delete_confirm:'确定要删除此活动吗？',
    admin_new_event_title:'添加新活动',admin_event_name_ph:'活动名称',admin_event_loc_ph:'地点',admin_event_add_btn:'+ 添加',admin_event_fill_alert:'请填写所有项目。',
    meetup_create_btn:'创建聚会',meetup_badge:'聚会',event_badge:'活动',meetup_form_title:'创建新聚会',meetup_title_ph:'聚会标题',meetup_loc_ph:'地点',meetup_desc_ph:'描述（可选）',meetup_submit_btn:'创建聚会',meetup_fill_alert:'请填写标题、日期和地点。',meetup_created_by:'创建者',
    rsvp_title:'参加确认',rsvp_attend:'✅ 参加',rsvp_not_attend:'❌ 不参加',rsvp_attendees:'人参加',rsvp_attendee_list:'参加者名单',rsvp_no_attendees:'暂无参加者。',rsvp_login_required:'请登录后确认参加。',rsvp_error:'参加确认失败，请重试。',
    admin_orders_new:'新订单',admin_orders_active:'进行中',admin_orders_done:'已完成',admin_orders_empty:'暂无订单。',
    shipped_status:'已发货',carrier_label:'快递公司',tracking_label:'快递单',received_status:'已收货',teeth_colon_label:'牙齿:',
    wiz_step1:'患者与牙位',wiz_step2:'品牌',wiz_step3:'色号与备注',wiz_step4:'STL文件',wiz_step5:'确认提交',wiz_next:'下一步 →',wiz_prev:'← 上一步',wiz_patient_label:'患者ID',wiz_no_tooth_err:'请至少选择1颗牙位。',wiz_no_brand_err:'请选择种植体品牌。',wiz_brand_all_hint:'适用于所有已选牙位',wiz_size_for_tooth:'尺寸（例：Ø4.0 / L10）',wiz_shade_label:'牙齿色号（VITA）',wiz_stl_main_label:'STL / 3D文件',wiz_stl_main_hint:'拖拽或点击选择 · 最多10个文件',wiz_confirm_title:'订单确认',wiz_delivery_label:'配送信息',wiz_teeth_selected:'颗牙位已选',wiz_start_over:'新建订单',wiz_size_table_title:'各牙位尺寸',
    used_post_toggle:'📸 发布二手物品',used_close_form:'✕ 关闭',settings_my_orders:'📦 我的订单',settings_no_orders:'暂无订单记录',
    admin_panel_title:'管理员面板',admin_total_members:'总会员数',admin_pending_orders:'待处理订单',admin_today_signups:'今日新注册',
    admin_tab_orders:'订单管理',admin_tab_users:'会员管理',admin_tab_custom:'定制订单',
    admin_order_date:'日期',admin_order_customer:'客户名',admin_order_total:'总额',admin_order_status:'状态',admin_change_status:'更改状态',
    admin_user_approve:'✅ 批准',admin_user_reject:'❌ 拒绝',admin_user_block:'🔒 封禁',admin_user_unblock:'✅ 解封',
    admin_user_pending_badge:'待审核',admin_user_active_badge:'活跃',admin_user_blocked_badge:'已封禁',
    admin_custom_change_stage:'更改阶段',admin_pending_users_title:'⏳ 待审核会员',admin_all_users_title:'👥 全部会员',
    admin_no_pending_users:'没有待审核的会员。',admin_loading:'加载中...',admin_load_fail:'加载失败',admin_no_users:'没有会员。',admin_error:'发生错误。',
  },
  th: {
    nav_home:'หน้าแรก',nav_shop:'ร้านค้า',nav_custom:'อะบัทเมนท์ CNC',nav_used:'ตลาดมือสอง',nav_forum:'ห้องสนทนา',nav_events:'กิจกรรม',nav_factory:'โรงงาน',nav_settings:'ตั้งค่า',
    pt_home:'หน้าแรก',pt_shop:'ร้านค้า',pt_custom:'อะบัทเมนท์สั่งทำพิเศษ',pt_used:'ตลาดมือสอง',pt_forum:'ห้องสนทนาคลินิก',pt_events:'กิจกรรม',pt_factory:'โรงงาน',pt_settings:'ตั้งค่า',
    login_subtitle:'เข้าสู่ระบบทันตแพทย์',login_ph:'ชื่อเล่น',login_password_ph:'รหัสผ่าน',login_btn:'เข้าสู่ระบบ',login_cancel:'ยกเลิก',login_error:'กรุณาใส่ชื่อเล่นและรหัสผ่าน',login_verifying:'กำลังตรวจสอบ...',login_not_found:'ไม่พบชื่อเล่น หรือรหัสผ่านไม่ถูกต้อง',login_network_error:'เกิดข้อผิดพลาดเครือข่าย กรุณาลองใหม่อีกครั้ง',login_register_link:'ขอสิทธิ์เข้าใช้งาน →',
    reg_title:'ขอสิทธิ์เข้าใช้งาน',reg_subtitle:'กรอกข้อมูลแล้วผู้ดูแลจะตรวจสอบและติดต่อกลับภายใน 24 ชั่วโมง',reg_license_ph:'หมายเลขใบอนุญาต (จำเป็น)',reg_name_ph:'ชื่อทันตแพทย์ (จำเป็น)',reg_clinic_ph:'ชื่อคลินิก (จำเป็น)',reg_contact_ph:'โทรศัพท์ หรือ Line ID (จำเป็น)',reg_password_ph:'รหัสผ่าน (จำเป็น)',reg_password_confirm_ph:'ยืนยันรหัสผ่าน (จำเป็น)',reg_submit:'ส่งคำขอ',reg_submitting:'กำลังส่ง...',reg_success:'ส่งคำขอเรียบร้อย!\nเราจะติดต่อกลับภายใน 24 ชั่วโมงหลังการอนุมัติ',reg_error:'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน',reg_pwd_mismatch:'รหัสผ่านไม่ตรงกัน',reg_duplicate:'ชื่อเล่นนี้ถูกลงทะเบียนแล้ว',reg_network_error:'เกิดข้อผิดพลาดเครือข่าย กรุณาลองใหม่อีกครั้ง',
    session_title:'เซสชันใกล้หมดอายุ',session_desc1:'การเข้าสู่ระบบจะหมดอายุใน',session_desc2:'',session_q:'ต้องการต่ออายุเซสชันหรือไม่?',session_extend:'ต่ออายุ 30 นาที',session_later:'ภายหลัง',session_expired:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
    side_remain:'เวลาที่เหลือ:',side_login_btn:'เข้าสู่ระบบทันตแพทย์',side_logged_label:'เข้าสู่ระบบแล้ว',side_logout:'ออกจากระบบ',
    home_subtitle:'ผู้เชี่ยวชาญรากฟันเทียม · ประเทศไทย',home_title1:'ชิ้นส่วนรากฟันเทียมดิจิทัล',home_title2:'ระบบสั่งซื้อ',home_desc:'จัดหาชิ้นส่วนรากฟันเทียม BIOTEM คุณภาพสูงโดยตรงให้กับคลินิกทันตกรรมทั่วประเทศไทย',home_goto_shop:'ไปที่ร้านค้า',home_line_add:'เพิ่มเพื่อน LINE',
    home_vision_label:'วิสัยทัศน์',home_vision:'พลิกโฉมความแม่นยำของรากฟันเทียมในภูมิภาคอาเซียน',home_stat1:'มาตรฐานรับรอง',home_stat2:'แหล่งผลิต',home_stat3:'พื้นที่ให้บริการ',home_biotem_short:'เชี่ยวชาญรากฟันเทียม · เกาหลี',home_bioplant_short:'ศูนย์การผลิต · กรุงเทพฯ',home_mission_label:'พันธกิจ',home_mission:'จัดหาชิ้นส่วนรากฟันเทียมระดับพรีเมียมจากเกาหลี ด้วยบริการที่รวดเร็วและเชื่อถือได้ให้กับคลินิกทั่วประเทศไทยและอาเซียน',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    home_about:'เกี่ยวกับเรา',home_biotem_desc:'ผู้ผลิตรากฟันเทียมชั้นนำจากเกาหลี เชี่ยวชาญด้านดิจิทัล workflow สำหรับงานทันตกรรมประดิษฐ์',home_bioplant_desc:'ศูนย์ผลิตชิ้นส่วนรากฟันเทียมระดับพรีเมียมในกรุงเทพฯ ให้บริการคลินิกทั่วภูมิภาคอาเซียน',home_categories:'หมวดหมู่สินค้า',home_contact:'ติดต่อและที่อยู่',home_address:'กรุงเทพมหานคร ประเทศไทย',home_hours:'จันทร์–ศุกร์ 09:00–18:00',home_line_label:'Line Official',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'ชิ้นส่วนรากฟันเทียมคุณภาพสูง',hero_bioplant_desc:'ผลิตมาตรฐาน ISO จากเกาหลี ส่งตรงถึงคลินิกของคุณ',hero_bioplant_cta:'ช้อปเลย',
    hero_cnc_tag:'อะบัทเมนท์สั่งทำ CNC',hero_cnc_title:'งานแม่นยำ ตามสเปกของคุณ',hero_cnc_desc:'ตั้งแต่สแกนบอดี้จนถึงการบูรณะฟัน ผลิตตามความต้องการ',hero_cnc_cta:'สั่งทำพิเศษ',
    sec_categories:'หมวดหมู่สินค้า',sec_see_more:'ดูทั้งหมด ›',cat_scan_body_desc:'แบบ Intra-Oral และแบบสแกนโมเดล',cat_q_base_desc:'อะบัทเมนท์เซอร์โคเนีย H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'รองรับมิลลิ่ง · ประเภท N และ R',cat_multi_unit_desc:'All-on-X · MUA · สแกนบอดี้',cat_3d_analog_desc:'GeoMedi สโตน & โมเดล 3D',
    sec_forum_preview:'สนทนาคลินิก',sec_forum_more:'ดูทั้งหมด ›',home_forum_empty:'ยังไม่มีโพสต์ เริ่มสนทนาได้เลย!',
    sec_events_preview:'กิจกรรมที่กำลังจะมา',sec_events_more:'ดูทั้งหมด ›',home_events_empty:'ไม่มีกิจกรรมที่กำลังจะมา',
    sec_webzine:'วารสารออนไลน์',sec_webzine_sub:'Case ทางคลินิก & อัปเดตสินค้า',sec_webzine_coming:'เร็ว ๆ นี้ — โปรดติดตาม',
    nav_webzine:'วารสาร',wz_cat_all:'ทั้งหมด',wz_cat_implant:'เคสรากฟันเทียม',wz_cat_prosthetic:'เคสครอบฟัน',wz_cat_review:'รีวิวสินค้า',wz_cat_news:'ข่าวอุตสาหกรรม',wz_cat_education:'เนื้อหาการศึกษา',
    wz_empty:'ยังไม่มีบทความ',wz_write_btn:'เขียนบทความ',wz_form_title:'บทความใหม่',wz_title_ph:'ชื่อบทความ',wz_thumb_ph:'คลิกเพื่ออัปโหลดรูปปก',wz_body_ph:'เขียนเนื้อหาบทความ (รองรับ Markdown)',wz_submit_btn:'เผยแพร่',wz_fill_alert:'กรุณากรอกชื่อเรื่องและเนื้อหา',wz_delete_confirm:'ลบบทความนี้หรือไม่?',
    shop_hint:'เลือกหมวดหมู่เพื่อสั่งซื้อ',shop_select:'เลือก ›',shop_each:'ชิ้น',
    order_add_cart:'เพิ่มในรถเข็น',order_qty_error:'กรุณาระบุจำนวนอย่างน้อย 1 ชิ้น',
    cart_title:'รถเข็น',cart_total:'ยอดรวม',cart_checkout:'ชำระเงิน',cart_close:'ปิด',cart_empty:'รถเข็นว่างเปล่า!',
    shop_specs:'ข้อมูลจำเพาะ & จำนวน',shop_in_stock:'มีสินค้า',shop_out_of_stock:'สินค้าหมด',shop_my_orders:'คำสั่งซื้อของฉัน',shop_product_count:'ผลิตภัณฑ์',cart_bar_tap:'แตะเพื่อดูตะกร้า',cart_bar_items:'รายการ',cart_added:'เพิ่มในตะกร้าแล้ว!',
    addr_title:'ข้อมูลจัดส่ง',addr_clinic_ph:'ชื่อคลินิก',addr_phone_ph:'หมายเลขโทรศัพท์',addr_addr_ph:'ที่อยู่',addr_qr_btn:'สร้าง QR Code',addr_back:'← กลับ',addr_fill_error:'กรุณากรอกข้อมูลจัดส่งให้ครบถ้วน',
    qr_label:'สแกนเพื่อชำระเงิน',qr_summary_title:'สรุปคำสั่งซื้อ',qr_total:'ยอดรวม',qr_complete:'ชำระเงินเรียบร้อย',
    used_contact_title:'ติดต่อผู้ขาย',used_contact_close:'ปิด',
    custom_tab_new:'สั่งทำใหม่',custom_tab_list:'คำสั่งซื้อของฉัน',custom_form_title:'สั่งทำอะบัทเมนท์พิเศษ',custom_delivery_title:'ข้อมูลจัดส่ง',custom_clinic_ph:'ชื่อคลินิก / ห้องแล็บ',custom_addr_ph:'ที่อยู่จัดส่ง',custom_phone_ph:'เบอร์ติดต่อ',custom_line_ph:'Line ID (สำหรับรับการแจ้งเตือน)',custom_submit:'ส่งคำสั่งซื้อ',custom_submit_note:'เมื่อได้รับคำสั่งซื้อจะส่งข้อความยืนยันทาง Line',custom_empty:'ยังไม่มีคำสั่งซื้อ',
    case_label:'เคส #',case_remove:'✕ ลบ',case_patient_ph:'รหัสผู้ป่วย (ไม่ระบุชื่อได้ เช่น P001)',case_tooth_hint:'เลือกตำแหน่งฟัน · แตะเพื่อเลือก/ยกเลิก',upper_jaw:'ขากรรไกรบน',lower_jaw:'ขากรรไกรล่าง',jaw_border:'แนวขอบฟัน',selected_teeth:'ฟันที่เลือก —',sel_count_suffix:' ซี่',brand_ph:'เลือกยี่ห้อรากฟันเทียม',size_ph:'ขนาด (เช่น Ø4.0 / L10)',color_ph:'เฉดสีฟัน (VITA)',case_add:'+ เพิ่มเคส',stl_label:'อัปโหลดไฟล์ STL (สูงสุด 10 ไฟล์)',stl_hint:'ลากวางหรือเลือกหลายไฟล์ .stl พร้อมกัน',memo_ph:'คำขอพิเศษ (ไม่บังคับ)',anon_patient:'ไม่ระบุชื่อ',case_deadline_label:'กำหนดส่งงาน',
    err_fill_delivery:'กรุณากรอกชื่อคลินิก ที่อยู่ และเบอร์ติดต่อ',err_select_tooth:'เคส #%: กรุณาเลือกฟันอย่างน้อย 1 ซี่',err_fill_tooth:'เคส #% ฟัน #%: กรุณาระบุยี่ห้อและขนาดรากฟันเทียม',err_add_case:'กรุณาเพิ่มอย่างน้อย 1 เคส',
    order_success_msg:'✅ ส่งคำสั่งซื้อเรียบร้อย!\nหมายเลขคำสั่งซื้อ: %\nเคส: % / ฟัน: % ซี่',order_success_line:'\nส่งข้อความยืนยันทาง Line แล้ว',
    status_label:'สถานะ',case_detail:'รายละเอียดเคส',teeth_count:' ซี่ฟัน',cases_unit:' เคส',teeth_total_prefix:'รวม ',patient_label:'ผู้ป่วย: ',no_tooth_info:'(ไม่มีข้อมูลฟัน)',case_nr:'เคส #',
    used_sell_title:'ขายอะไหล่มือสอง',used_name_ph:'ชื่อชิ้นส่วน',used_code_ph:'รหัสสินค้า',used_price_ph:'ราคา (บาท)',cond_new:'เหมือนใหม่',cond_good:'ดี',cond_fair:'พอใช้',used_desc_ph:'รายละเอียดสภาพ...',used_contact_ph:'ช่องทางติดต่อ (Line ID / โทรศัพท์)',used_post_btn:'ลงประกาศขาย',used_list_title:'อะไหล่มือสองที่มีจำหน่าย',used_contact_btn:'ติดต่อ',used_delete_btn:'ลบ',used_empty:'ยังไม่มีอะไหล่มือสอง',used_fill_error:'กรุณากรอกชื่อชิ้นส่วน ราคา และช่องทางติดต่อ',
    forum_new_post:'โพสต์ใหม่',forum_title_ph:'หัวข้อ',forum_body_ph:'เขียนข้อความ...',forum_post_btn:'โพสต์',
    settings_lang:'ภาษา',settings_account:'บัญชี',settings_license:'ใบอนุญาต:',settings_save_btn:'บันทึกภาษา',settings_saved_msg:'บันทึกภาษาแล้ว!',settings_pending:'เลือกภาษาแล้วกด บันทึก',
    pe_title:'✏️ แก้ไขข้อมูลของฉัน',pe_subtitle:'รายการที่แก้ไขได้',pe_email:'อีเมล',pe_phone:'หมายเลขโทรศัพท์',pe_address:'ที่อยู่',pe_clinic:'ชื่อคลินิก',pe_save:'บันทึก',pe_cancel:'ยกเลิก',pe_email_ph:'ที่อยู่อีเมล',pe_phone_ph:'หมายเลขโทรศัพท์',pe_address_ph:'ที่อยู่',pe_clinic_ph:'ชื่อคลินิก',
    profile_title:'👤 ข้อมูลของฉัน',profile_edit_btn:'แก้ไข',profile_login_msg:'กรุณาเข้าสู่ระบบเพื่อดูข้อมูล',profile_saved_msg:'✅ บันทึกแล้ว!',profile_no_change:'(เปลี่ยนไม่ได้)',prof_nickname:'ชื่อเล่น',prof_doctor:'ชื่อแพทย์',login_required:'กรุณาเข้าสู่ระบบ',
    factory_subtitle:'ศูนย์ผลิตชิ้นส่วนรากฟันเทียมระดับพรีเมียมในกรุงเทพฯ',
    tooth_11:'ฟันตัดกลาง',tooth_12:'ฟันตัดข้าง',tooth_13:'ฟันเขี้ยว',tooth_14:'ฟันกรามน้อยซี่ที่ 1',tooth_15:'ฟันกรามน้อยซี่ที่ 2',tooth_16:'ฟันกรามซี่ที่ 1',tooth_17:'ฟันกรามซี่ที่ 2',
    upper:'ขากรรไกรบน',lower:'ขากรรไกรล่าง',
    stage_received:'รับคำสั่งซื้อแล้ว',stage_stl:'ตรวจสอบไฟล์ STL',stage_design:'กำลังออกแบบ',stage_cnc:'กำลังผลิต CNC',stage_qc:'ตรวจสอบคุณภาพ',stage_shipping:'กำลังจัดส่ง',stage_done:'ส่งมอบแล้ว',stage_submitted:'รอการยืนยัน',stage_confirmed:'ยืนยันแล้ว',stage_design_ready:'รอตรวจแบบ',stage_design_revision:'กำลังแก้ไขแบบ',stage_approved:'อนุมัติแบบแล้ว',stage_milling:'กำลัง CNC มิลลิ่ง',stage_shipped:'ส่งพัสดุแล้ว',
    line_deadline:'กำหนดส่ง',line_memo:'หมายเหตุ',line_total_cases:'รวม % เคส / % ซี่',
    reg_privacy_agree_prefix:'ฉันได้อ่านและยอมรับ',reg_privacy_link:'นโยบายความเป็นส่วนตัว',reg_privacy_agree_suffix:'(PDPA ไทย)',reg_privacy_error:'กรุณาอ่านและยอมรับนโยบายความเป็นส่วนตัวเพื่อดำเนินการต่อ',
    privacy_title:'นโยบายความเป็นส่วนตัว',privacy_close:'ปิด',
    used_photo_add:'เพิ่มรูปภาพ',shop_items:'ชิ้น',
    forum_cat_implant:'🦷 รากฟันเทียม',forum_cat_prosthetic:'💎 ทันตกรรมประดิษฐ์',forum_cat_conservative:'🪥 ทันตกรรมหัตถการ',forum_cat_orthodontics:'🦷 ทันตกรรมจัดฟัน',forum_cat_oral_surgery:'✂️ ศัลยกรรมช่องปาก',forum_cat_periodontics:'🌿 เวชศาสตร์ปริทันต์',forum_cat_pediatric:'👶 ทันตกรรมเด็ก',forum_cat_radiology:'📷 รังสีวิทยาช่องปาก',forum_cat_oral_medicine:'💊 เวชศาสตร์ช่องปาก',forum_cat_preventive:'🛡 ทันตกรรมป้องกัน',forum_cat_general:'🏥 ทั่วไป',forum_photo_add:'📷 เพิ่มรูป (สูงสุด 5 รูป)',forum_empty:'ยังไม่มีโพสต์',
    forum_write_btn:'✍️ เขียนโพสต์',forum_close_form:'✕ ปิด',forum_cat_label:'หมวดหมู่',
    forum_region_label:'ภาค',forum_province_label:'จังหวัด',
    forum_region_all:'🌏 ทั้งหมด',forum_region_north:'🏔 ภาคเหนือ',forum_region_northeast:'🌾 ภาคอีสาน',forum_region_east:'🌊 ภาคตะวันออก',forum_region_south:'🏝 ภาคใต้',forum_region_central:'🏙 ภาคกลาง',
    forum_comment_title:'💬 ความคิดเห็น',forum_comment_ph:'เขียนความคิดเห็น...',forum_comment_submit:'ส่ง',forum_no_comments:'ยังไม่มีความคิดเห็น',forum_writing_as:'เขียนในชื่อ',
    custom_tab_list:'กำลังดำเนินการ',custom_tab_done:'เสร็จสิ้น',
    install_ios:'📱 <b>วิธีติดตั้ง iPhone / Safari</b><br><br>① แตะปุ่มแชร์ <b>□↑</b> ด้านล่าง<br>② เลือก <b>"เพิ่มในหน้าจอหลัก"</b><br>③ แตะ <b>"เพิ่ม"</b>',
    install_android:'💻 <b>วิธีติดตั้ง PC / Android</b><br><br>① คลิกไอคอนติดตั้ง <b>⊕</b><br>&nbsp;&nbsp;&nbsp;ทางขวาของแถบที่อยู่เบราว์เซอร์<br>② คลิก <b>"ติดตั้ง"</b><br><br>※ ถ้าไม่มีไอคอน ให้เปิดเมนูเบราว์เซอร์<br>&nbsp;&nbsp;&nbsp;→ "ติดตั้งเป็นแอป"',
    install_ok:'ตกลง',
    design_waiting:'⏳ รอการอัปโหลดไฟล์ดีไซน์...',shipped_msg:'🚚 คำสั่งซื้อของคุณถูกจัดส่งแล้ว กรุณากดปุ่มด้านล่างเมื่อได้รับสินค้า',receive_btn:'📦 ยืนยันการรับสินค้า',
    edit_order_btn:'✏️ แก้ไข',delete_order_btn:'🗑 ลบ',review_history_label:'ประวัติการตรวจสอบ (% ครั้ง)',
    done_orders_empty:'ยังไม่มีคำสั่งซื้อที่เสร็จสิ้น',done_status_label:'เสร็จสิ้น',done_cases_teeth_fmt:'% เคส · % ซี่ฟัน',
    reg_nick_ph:'ชื่อเล่น (จำเป็น) — ใช้ในทุกกิจกรรม',reg_email_ph:'ที่อยู่อีเมล (จำเป็น)',
    compose_title:'✉️ ส่งข้อความ',compose_to_ph:'ผู้รับ (ชื่อเล่น)',compose_subj_ph:'หัวข้อ',compose_body_ph:'เขียนข้อความ...',compose_send:'ส่ง',
    ship_carrier_custom_opt:'ป้อนเอง',ship_carrier_ph:'ชื่อบริษัทขนส่ง',ship_tracking_label:'หมายเลขพัสดุ',ship_tracking_ph:'ป้อนหมายเลขพัสดุ',ship_process_btn:'🚚 ดำเนินการจัดส่ง → ส่ง LINE',
    leader_badge:'ผู้นำภูมิภาค',leader_assign:'แต่งตั้ง',leader_remove:'ถอดถอนผู้นำ',leader_select_region:'เลือกภูมิภาค...',
    forum_pinned:'ปักหมุด',forum_pin:'ปักหมุด',forum_unpin:'เลิกปักหมุด',forum_delete:'ลบ',forum_delete_confirm:'คุณแน่ใจหรือไม่ว่าต้องการลบโพสต์นี้?',event_delete_confirm:'คุณแน่ใจหรือไม่ว่าต้องการลบกิจกรรมนี้?',
    admin_new_event_title:'เพิ่มกิจกรรมใหม่',admin_event_name_ph:'ชื่อกิจกรรม',admin_event_loc_ph:'สถานที่',admin_event_add_btn:'+ เพิ่ม',admin_event_fill_alert:'กรุณากรอกข้อมูลให้ครบทุกช่อง',
    meetup_create_btn:'สร้างนัดพบ',meetup_badge:'นัดพบ',event_badge:'กิจกรรม',meetup_form_title:'สร้างนัดพบใหม่',meetup_title_ph:'ชื่อนัดพบ',meetup_loc_ph:'สถานที่',meetup_desc_ph:'รายละเอียด (ไม่บังคับ)',meetup_submit_btn:'สร้างนัดพบ',meetup_fill_alert:'กรุณากรอกชื่อ วันที่ และสถานที่',meetup_created_by:'สร้างโดย',
    rsvp_title:'ตอบรับ',rsvp_attend:'✅ เข้าร่วม',rsvp_not_attend:'❌ ไม่เข้าร่วม',rsvp_attendees:'คนเข้าร่วม',rsvp_attendee_list:'รายชื่อผู้เข้าร่วม',rsvp_no_attendees:'ยังไม่มีผู้เข้าร่วม',rsvp_login_required:'กรุณาเข้าสู่ระบบเพื่อตอบรับ',rsvp_error:'ตอบรับล้มเหลว กรุณาลองอีกครั้ง',
    admin_orders_new:'คำสั่งซื้อใหม่',admin_orders_active:'กำลังดำเนินการ',admin_orders_done:'เสร็จสิ้น',admin_orders_empty:'ไม่มีคำสั่งซื้อ',
    shipped_status:'จัดส่งแล้ว',carrier_label:'บริษัทขนส่ง',tracking_label:'เลขพัสดุ',received_status:'รับสินค้าแล้ว',teeth_colon_label:'ฟัน:',
    wiz_step1:'ผู้ป่วย & ตำแหน่งฟัน',wiz_step2:'ยี่ห้อรากฟันเทียม',wiz_step3:'เฉดสีและหมายเหตุ',wiz_step4:'ไฟล์ STL',wiz_step5:'ยืนยัน & ส่งคำสั่ง',wiz_next:'ถัดไป →',wiz_prev:'← ย้อนกลับ',wiz_patient_label:'รหัสผู้ป่วย',wiz_no_tooth_err:'กรุณาเลือกตำแหน่งฟันอย่างน้อย 1 ซี่',wiz_no_brand_err:'กรุณาเลือกยี่ห้อรากฟันเทียม',wiz_brand_all_hint:'ใช้กับฟันทุกซี่ที่เลือก',wiz_size_for_tooth:'ขนาด (เช่น Ø4.0 / L10)',wiz_shade_label:'เฉดสีฟัน (VITA)',wiz_stl_main_label:'ไฟล์ STL / 3D',wiz_stl_main_hint:'ลากวางหรือแตะเพื่อเลือก · สูงสุด 10 ไฟล์',wiz_confirm_title:'สรุปรายการสั่งทำ',wiz_delivery_label:'ข้อมูลการจัดส่ง',wiz_teeth_selected:'ซี่ที่เลือก',wiz_start_over:'เริ่มคำสั่งใหม่',wiz_size_table_title:'ขนาดแยกตามฟัน',
    used_post_toggle:'📸 ลงประกาศขาย',used_close_form:'✕ ปิด',settings_my_orders:'📦 คำสั่งซื้อของฉัน',settings_no_orders:'ยังไม่มีคำสั่งซื้อ',
    shop_hint:'เลือกหมวดหมู่เพื่อสั่งซื้อ',shop_specs:'รายละเอียดสินค้า & จำนวน',shop_in_stock:'มีสินค้าพร้อมส่ง',shop_out_of_stock:'สินค้าหมด',shop_my_orders:'คำสั่งซื้อของฉัน',
    prof_nickname:'ชื่อเล่น',prof_doctor:'ชื่อทันตแพทย์',
    admin_panel_title:'แผงผู้ดูแลระบบ',admin_total_members:'สมาชิกทั้งหมด',admin_pending_orders:'คำสั่งซื้อรอดำเนินการ',admin_today_signups:'สมาชิกใหม่วันนี้',
    admin_tab_orders:'จัดการคำสั่งซื้อ',admin_tab_users:'จัดการสมาชิก',admin_tab_custom:'คำสั่งทำพิเศษ',
    admin_order_date:'วันที่',admin_order_customer:'ชื่อลูกค้า',admin_order_total:'ยอดรวม',admin_order_status:'สถานะ',admin_change_status:'เปลี่ยนสถานะ',
    admin_user_approve:'✅ อนุมัติ',admin_user_reject:'❌ ปฏิเสธ',admin_user_block:'🔒 บล็อก',admin_user_unblock:'✅ ยกเลิกบล็อก',
    admin_user_pending_badge:'รอการอนุมัติ',admin_user_active_badge:'ใช้งานอยู่',admin_user_blocked_badge:'ถูกบล็อก',
    admin_custom_change_stage:'เปลี่ยนขั้นตอน',admin_pending_users_title:'⏳ รอการอนุมัติ',admin_all_users_title:'👥 สมาชิกทั้งหมด',
    admin_no_pending_users:'ไม่มีสมาชิกที่รอการอนุมัติ',admin_loading:'กำลังโหลด...',admin_load_fail:'โหลดไม่สำเร็จ',admin_no_users:'ไม่มีสมาชิก',admin_error:'เกิดข้อผิดพลาด',
  },
  vi: {
    nav_home:'TRANG CHỦ',nav_shop:'CỬA HÀNG',nav_custom:'CNC Custom Abut',nav_used:'THỊ TRƯỜNG CŨ',nav_forum:'THẢO LUẬN',nav_events:'SỰ KIỆN',nav_factory:'NHÀ MÁY',nav_settings:'CÀI ĐẶT',
    pt_home:'Trang chủ',pt_shop:'Cửa hàng',pt_custom:'Custom Abutment',pt_used:'Thị trường cũ',pt_forum:'Thảo luận lâm sàng',pt_events:'Sự kiện',pt_factory:'Nhà máy',pt_settings:'Cài đặt',
    login_subtitle:'ĐĂNG NHẬP BÁC SĨ',login_ph:'Tên đăng nhập',login_password_ph:'Mật khẩu',login_btn:'ĐĂNG NHẬP',login_cancel:'Hủy',login_error:'Vui lòng nhập tên đăng nhập và mật khẩu.',login_verifying:'Đang xác thực...',login_not_found:'Không tìm thấy tên đăng nhập hoặc mật khẩu sai.',login_network_error:'Lỗi mạng. Vui lòng thử lại.',login_register_link:'Yêu cầu truy cập →',
    reg_title:'Yêu cầu truy cập',reg_subtitle:'Điền thông tin. Quản trị viên sẽ phê duyệt trong 24 giờ.',reg_license_ph:'Số giấy phép (bắt buộc)',reg_name_ph:'Tên bác sĩ (bắt buộc)',reg_clinic_ph:'Tên phòng khám (bắt buộc)',reg_contact_ph:'Điện thoại hoặc Line ID (bắt buộc)',reg_password_ph:'Mật khẩu (bắt buộc)',reg_password_confirm_ph:'Xác nhận mật khẩu (bắt buộc)',reg_submit:'Gửi yêu cầu',reg_submitting:'Đang gửi...',reg_success:'Đã gửi yêu cầu!\nChúng tôi sẽ liên hệ trong 24 giờ sau khi phê duyệt.',reg_error:'Vui lòng điền tất cả các trường bắt buộc.',reg_pwd_mismatch:'Mật khẩu không khớp.',reg_duplicate:'Tên đăng nhập này đã được đăng ký.',reg_network_error:'Lỗi mạng. Vui lòng thử lại.',
    session_title:'Phiên sắp hết hạn',session_desc1:'Đăng nhập sẽ hết hạn sau',session_desc2:'',session_q:'Bạn có muốn gia hạn không?',session_extend:'Gia hạn 30 phút',session_later:'Sau',session_expired:'Phiên đã hết hạn. Vui lòng đăng nhập lại.',
    side_remain:'Còn lại:',side_login_btn:'Đăng nhập bác sĩ',side_logged_label:'Đã đăng nhập',side_logout:'Đăng xuất',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'Linh kiện Implant kỹ thuật số',home_title2:'Hệ thống đặt hàng',home_desc:'Cung cấp linh kiện BIOTEM Implant cao cấp trực tiếp đến các phòng khám nha khoa trên toàn Thái Lan.',home_goto_shop:'Đến cửa hàng',home_line_add:'Thêm bạn LINE',
    home_vision_label:'Tầm nhìn',home_vision:'Định nghĩa lại độ chính xác của implant tại Đông Nam Á',home_stat1:'Được chứng nhận',home_stat2:'Xuất xứ',home_stat3:'Phạm vi',home_biotem_short:'Chuyên gia Implant · Hàn Quốc',home_bioplant_short:'Sản xuất · Bangkok',home_mission_label:'Sứ mệnh',home_mission:'Cung cấp linh kiện implant nha khoa cao cấp sản xuất tại Hàn Quốc với dịch vụ nhanh chóng, đáng tin cậy đến các phòng khám trên khắp Thái Lan và Đông Nam Á.',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    home_about:'Về chúng tôi',home_biotem_desc:'Nhà sản xuất implant nha khoa Hàn Quốc. Chuyên gia Implant với giải pháp quy trình kỹ thuật số tiên tiến.',home_bioplant_desc:'Trung tâm sản xuất fixture nha khoa cao cấp tại Bangkok. Cung cấp cho các phòng khám khắp Đông Nam Á.',home_categories:'Danh mục sản phẩm',home_contact:'Liên hệ & Địa chỉ',home_address:'Bangkok, Thái Lan',home_hours:'T2–T6 09:00–18:00',home_line_label:'Line Chính thức',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'Linh kiện Implant cao cấp',hero_bioplant_desc:'Sản xuất chuẩn ISO Hàn Quốc, giao hàng nhanh đến phòng khám',hero_bioplant_cta:'Mua ngay',
    hero_cnc_tag:'CNC Custom Abutment',hero_cnc_title:'Giải pháp đặt làm chính xác',hero_cnc_desc:'Sản xuất theo thông số của bạn — từ scan body đến phục hình',hero_cnc_cta:'Đặt hàng',
    sec_categories:'Danh mục sản phẩm',sec_see_more:'Xem tất cả ›',cat_scan_body_desc:'Loại Intra-Oral & Model',cat_q_base_desc:'Abutment Zirconia H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'Tương thích milling · N & R',cat_multi_unit_desc:'All-on-X · MUA · Scan Body',cat_3d_analog_desc:'GeoMedi Stone & 3D Model',
    sec_forum_preview:'Thảo luận lâm sàng',sec_forum_more:'Xem tất cả ›',home_forum_empty:'Chưa có bài đăng. Hãy bắt đầu!',
    sec_events_preview:'Sự kiện sắp tới',sec_events_more:'Xem tất cả ›',home_events_empty:'Không có sự kiện sắp tới',
    sec_webzine:'Webzine',sec_webzine_sub:'Case lâm sàng & cập nhật sản phẩm',sec_webzine_coming:'Sắp ra mắt — Đón chờ nhé',
    nav_webzine:'WEBZINE',wz_cat_all:'Tất cả',wz_cat_implant:'Ca cấy ghép',wz_cat_prosthetic:'Ca phục hình',wz_cat_review:'Đánh giá SP',wz_cat_news:'Tin ngành',wz_cat_education:'Giáo dục',
    wz_empty:'Chưa có bài viết nào.',wz_write_btn:'Viết bài',wz_form_title:'Bài viết mới',wz_title_ph:'Tiêu đề bài viết',wz_thumb_ph:'Nhấn để tải ảnh bìa',wz_body_ph:'Viết nội dung bài viết (hỗ trợ Markdown)',wz_submit_btn:'Đăng bài',wz_fill_alert:'Vui lòng điền tiêu đề và nội dung.',wz_delete_confirm:'Xóa bài viết này?',
    shop_hint:'Chọn danh mục để đặt hàng',shop_select:'CHỌN ›',shop_each:'cái',
    order_add_cart:'Thêm vào giỏ',order_qty_error:'Vui lòng nhập ít nhất 1 số lượng.',
    cart_title:'Giỏ hàng',cart_total:'TỔNG CỘNG',cart_checkout:'THANH TOÁN',cart_close:'Đóng',cart_empty:'Giỏ hàng trống!',
    shop_specs:'Thông số & Số lượng',shop_in_stock:'Còn hàng',shop_out_of_stock:'Hết hàng',shop_my_orders:'Đơn hàng của tôi',shop_product_count:'sản phẩm',cart_bar_tap:'Nhấn để xem giỏ',cart_bar_items:'mục',cart_added:'Đã thêm vào giỏ!',
    addr_title:'Thông tin giao hàng',addr_clinic_ph:'Tên phòng khám',addr_phone_ph:'Số điện thoại',addr_addr_ph:'Địa chỉ đầy đủ',addr_qr_btn:'TẠO QR',addr_back:'← Quay lại',addr_fill_error:'Vui lòng điền đầy đủ thông tin giao hàng.',
    qr_label:'Quét để thanh toán',qr_summary_title:'Tóm tắt đơn hàng',qr_total:'TỔNG',qr_complete:'THANH TOÁN HOÀN TẤT',
    used_contact_title:'Liên hệ người bán',used_contact_close:'Đóng',
    custom_tab_new:'Đơn mới',custom_tab_list:'Đơn của tôi',custom_form_title:'Đặt Custom Abutment',custom_delivery_title:'Thông tin giao hàng',custom_clinic_ph:'Tên phòng khám / Phòng lab',custom_addr_ph:'Địa chỉ giao hàng',custom_phone_ph:'Số điện thoại',custom_line_ph:'Line ID (để nhận thông báo)',custom_submit:'Gửi đơn hàng',custom_submit_note:'Xác nhận đơn hàng sẽ được gửi qua Line',custom_empty:'Chưa có đơn hàng',
    case_label:'Ca #',case_remove:'✕ Xóa',case_patient_ph:'ID bệnh nhân (ẩn danh được, vd: P001)',case_tooth_hint:'Chọn răng · Nhấn để bật/tắt',upper_jaw:'Hàm trên (Upper Jaw)',lower_jaw:'Hàm dưới (Lower Jaw)',jaw_border:'Ranh giới hàm',selected_teeth:'Răng đã chọn —',sel_count_suffix:' chiếc',brand_ph:'Chọn thương hiệu implant',size_ph:'Kích thước (vd: Ø4.0 / L10)',color_ph:'Màu răng (VITA)',case_add:'+ Thêm ca',stl_label:'Tải file STL (tối đa 10 file)',stl_hint:'Có thể chọn nhiều file .stl cùng lúc',memo_ph:'Yêu cầu đặc biệt (tùy chọn)',anon_patient:'Ẩn danh',case_deadline_label:'Hạn giao hàng',
    err_fill_delivery:'Vui lòng nhập tên phòng khám, địa chỉ và số điện thoại.',err_select_tooth:'Ca #%: Vui lòng chọn ít nhất 1 răng.',err_fill_tooth:'Ca #% Răng #%: Vui lòng nhập thương hiệu và kích thước implant.',err_add_case:'Vui lòng thêm ít nhất 1 ca.',
    order_success_msg:'✅ Đã gửi đơn hàng!\nSố đơn: %\nCa: % / Răng: % chiếc',order_success_line:'\nXác nhận đã gửi qua Line.',
    status_label:'Tiến độ',case_detail:'Chi tiết ca',teeth_count:' chiếc',cases_unit:' ca',teeth_total_prefix:'Tổng ',patient_label:'Bệnh nhân: ',no_tooth_info:'(không có thông tin răng)',case_nr:'Ca #',
    used_sell_title:'Bán linh kiện cũ',used_name_ph:'Tên linh kiện',used_code_ph:'Mã sản phẩm',used_price_ph:'Giá (THB)',cond_new:'Như mới',cond_good:'Tốt',cond_fair:'Bình thường',used_desc_ph:'Mô tả tình trạng...',used_contact_ph:'Liên hệ (Line ID / Điện thoại)',used_post_btn:'ĐĂNG BÁN',used_list_title:'Linh kiện cũ có sẵn',used_contact_btn:'Liên hệ',used_delete_btn:'Xóa',used_empty:'Chưa có linh kiện cũ nào',used_fill_error:'Vui lòng nhập tên linh kiện, giá và liên hệ.',
    forum_new_post:'Bài đăng mới',forum_title_ph:'Tiêu đề',forum_body_ph:'Viết nội dung...',forum_post_btn:'ĐĂNG',
    settings_lang:'Ngôn ngữ',settings_account:'Tài khoản',settings_license:'Giấy phép:',settings_save_btn:'Lưu ngôn ngữ',settings_saved_msg:'Đã lưu ngôn ngữ!',settings_pending:'Chọn ngôn ngữ rồi nhấn Lưu.',
    pe_title:'✏️ Chỉnh sửa thông tin',pe_subtitle:'Các trường có thể chỉnh sửa',pe_email:'Email',pe_phone:'Số điện thoại',pe_address:'Địa chỉ',pe_clinic:'Tên phòng khám',pe_save:'Lưu',pe_cancel:'Hủy',pe_email_ph:'Địa chỉ email',pe_phone_ph:'Số điện thoại',pe_address_ph:'Địa chỉ',pe_clinic_ph:'Tên phòng khám',
    profile_title:'👤 Thông tin của tôi',profile_edit_btn:'Chỉnh sửa',profile_login_msg:'Vui lòng đăng nhập để xem.',profile_saved_msg:'✅ Đã lưu!',profile_no_change:'(không thể thay đổi)',prof_nickname:'Tên đăng nhập',prof_doctor:'Tên bác sĩ',login_required:'Cần đăng nhập.',
    factory_subtitle:'Trung tâm sản xuất fixture cao cấp tại Bangkok',
    tooth_11:'Răng cửa giữa',tooth_12:'Răng cửa bên',tooth_13:'Răng nanh',tooth_14:'Răng tiền hàm 1',tooth_15:'Răng tiền hàm 2',tooth_16:'Răng hàm 1',tooth_17:'Răng hàm 2',
    upper:'Hàm trên',lower:'Hàm dưới',
    stage_received:'Đã nhận đơn',stage_stl:'Xem xét STL',stage_design:'Đang thiết kế',stage_cnc:'Sản xuất CNC',stage_qc:'Kiểm tra chất lượng',stage_shipping:'Đang giao hàng',stage_done:'Đã giao',stage_submitted:'Chờ xác nhận',stage_confirmed:'Đã xác nhận',stage_design_ready:'Duyệt thiết kế',stage_design_revision:'Đang chỉnh sửa',stage_approved:'Đã phê duyệt',stage_milling:'Đang CNC',stage_shipped:'Đã gửi hàng',
    line_deadline:'Hạn chót',line_memo:'Ghi chú',line_total_cases:'Tổng % ca / % chiếc',
    reg_privacy_agree_prefix:'Tôi đã đọc và đồng ý với',reg_privacy_link:'Chính sách bảo mật',reg_privacy_agree_suffix:'(PDPA Thái Lan).',reg_privacy_error:'Vui lòng đọc và đồng ý với Chính sách bảo mật để tiếp tục.',
    privacy_title:'Chính sách bảo mật',privacy_close:'Đóng',
    used_photo_add:'Thêm ảnh',shop_items:'sản phẩm',
    forum_cat_implant:'🦷 Implant',forum_cat_prosthetic:'💎 Phục hình',forum_cat_conservative:'🪥 Bảo tồn',forum_cat_orthodontics:'🦷 Chỉnh nha',forum_cat_oral_surgery:'✂️ Phẫu thuật hàm mặt',forum_cat_periodontics:'🌿 Nha chu',forum_cat_pediatric:'👶 Nha khoa trẻ em',forum_cat_radiology:'📷 X-quang',forum_cat_oral_medicine:'💊 Nội khoa miệng',forum_cat_preventive:'🛡 Phòng ngừa',forum_cat_general:'🏥 Tổng hợp',forum_photo_add:'📷 Thêm ảnh (tối đa 5)',forum_empty:'Chưa có bài đăng.',
    forum_write_btn:'✍️ Viết bài',forum_close_form:'✕ Đóng',forum_cat_label:'Danh mục',
    forum_region_label:'Khu vực',forum_province_label:'Tỉnh',
    forum_region_all:'🌏 Tất cả',forum_region_north:'🏔 Miền Bắc',forum_region_northeast:'🌾 Đông Bắc',forum_region_east:'🌊 Miền Đông',forum_region_south:'🏝 Miền Nam',forum_region_central:'🏙 Miền Trung',
    forum_comment_title:'💬 Bình luận',forum_comment_ph:'Viết bình luận...',forum_comment_submit:'Gửi',forum_no_comments:'Chưa có bình luận.',forum_writing_as:'Đăng với tên',
    custom_tab_list:'Đang xử lý',custom_tab_done:'Hoàn thành',
    install_ios:'📱 <b>Cài đặt iPhone / Safari</b><br><br>① Nhấn nút Chia sẻ <b>□↑</b> ở dưới<br>② Chọn <b>"Thêm vào màn hình chính"</b><br>③ Nhấn <b>"Thêm"</b>',
    install_android:'💻 <b>Cài đặt PC / Android</b><br><br>① Nhấn <b>biểu tượng cài đặt ⊕</b><br>&nbsp;&nbsp;&nbsp;bên phải thanh địa chỉ trình duyệt<br>② Nhấn <b>"Cài đặt"</b><br><br>※ Nếu không có biểu tượng, mở menu trình duyệt<br>&nbsp;&nbsp;&nbsp;→ "Cài đặt dưới dạng ứng dụng"',
    install_ok:'OK',
    design_waiting:'⏳ Đang chờ tải lên file thiết kế...',shipped_msg:'🚚 Đơn hàng đã được giao. Nhấn nút bên dưới khi nhận được.',receive_btn:'📦 Xác nhận đã nhận',
    edit_order_btn:'✏️ Chỉnh sửa',delete_order_btn:'🗑 Xóa',review_history_label:'Lịch sử xét duyệt (% lần)',
    done_orders_empty:'Chưa có đơn hàng hoàn thành.',done_status_label:'Hoàn thành',done_cases_teeth_fmt:'% ca · % chiếc',
    reg_nick_ph:'Tên đăng nhập (bắt buộc) — dùng cho mọi hoạt động',reg_email_ph:'Địa chỉ email (bắt buộc)',
    compose_title:'✉️ Gửi tin nhắn',compose_to_ph:'Người nhận (tên đăng nhập)',compose_subj_ph:'Tiêu đề',compose_body_ph:'Viết nội dung...',compose_send:'Gửi',
    ship_carrier_custom_opt:'Nhập thủ công',ship_carrier_ph:'Tên công ty vận chuyển',ship_tracking_label:'Mã vận đơn',ship_tracking_ph:'Nhập mã vận đơn',ship_process_btn:'🚚 Xử lý giao hàng → Gửi LINE',
    leader_badge:'Trưởng khu vực',leader_assign:'Chỉ định',leader_remove:'Gỡ trưởng',leader_select_region:'Chọn khu vực...',
    forum_pinned:'Đã ghim',forum_pin:'Ghim',forum_unpin:'Bỏ ghim',forum_delete:'Xóa',forum_delete_confirm:'Bạn có chắc chắn muốn xóa bài viết này?',event_delete_confirm:'Bạn có chắc chắn muốn xóa sự kiện này?',
    admin_new_event_title:'Thêm sự kiện mới',admin_event_name_ph:'Tên sự kiện',admin_event_loc_ph:'Địa điểm',admin_event_add_btn:'+ Thêm',admin_event_fill_alert:'Vui lòng điền tất cả các trường.',
    meetup_create_btn:'Tạo buổi gặp',meetup_badge:'Gặp mặt',event_badge:'Sự kiện',meetup_form_title:'Tạo buổi gặp mới',meetup_title_ph:'Tên buổi gặp',meetup_loc_ph:'Địa điểm',meetup_desc_ph:'Mô tả (tùy chọn)',meetup_submit_btn:'Tạo buổi gặp',meetup_fill_alert:'Vui lòng điền tên, ngày và địa điểm.',meetup_created_by:'Tạo bởi',
    rsvp_title:'Xác nhận tham gia',rsvp_attend:'✅ Tham gia',rsvp_not_attend:'❌ Không tham gia',rsvp_attendees:'người tham gia',rsvp_attendee_list:'Danh sách người tham gia',rsvp_no_attendees:'Chưa có người tham gia.',rsvp_login_required:'Vui lòng đăng nhập để xác nhận.',rsvp_error:'Xác nhận thất bại. Vui lòng thử lại.',
    admin_orders_new:'Đơn mới',admin_orders_active:'Đang xử lý',admin_orders_done:'Hoàn thành',admin_orders_empty:'Không có đơn hàng.',
    shipped_status:'Đã giao',carrier_label:'Đơn vị vận chuyển',tracking_label:'Mã vận đơn',received_status:'Đã nhận',teeth_colon_label:'Răng:',
    wiz_step1:'Bệnh nhân & Răng',wiz_step2:'Thương hiệu',wiz_step3:'Màu & Ghi chú',wiz_step4:'STL',wiz_step5:'Xác nhận',wiz_next:'Tiếp →',wiz_prev:'← Quay lại',wiz_patient_label:'ID bệnh nhân',wiz_no_tooth_err:'Vui lòng chọn ít nhất 1 răng.',wiz_no_brand_err:'Vui lòng chọn thương hiệu implant.',wiz_brand_all_hint:'Áp dụng cho tất cả răng đã chọn',wiz_size_for_tooth:'Kích thước (vd: Ø4.0 / L10)',wiz_shade_label:'Màu răng (VITA)',wiz_stl_main_label:'File STL / 3D',wiz_stl_main_hint:'Kéo thả hoặc nhấn để chọn · Tối đa 10 file',wiz_confirm_title:'Xác nhận đơn hàng',wiz_delivery_label:'Thông tin giao hàng',wiz_teeth_selected:'răng đã chọn',wiz_start_over:'Tạo đơn mới',wiz_size_table_title:'Kích thước theo răng',
    used_post_toggle:'📸 Đăng bán',used_close_form:'✕ Đóng',settings_my_orders:'📦 Đơn hàng của tôi',settings_no_orders:'Chưa có đơn hàng',
    admin_panel_title:'Bảng quản trị',admin_total_members:'Tổng thành viên',admin_pending_orders:'Đơn hàng chờ xử lý',admin_today_signups:'Đăng ký hôm nay',
    admin_tab_orders:'Quản lý đơn hàng',admin_tab_users:'Quản lý thành viên',admin_tab_custom:'Đơn tùy chỉnh',
    admin_order_date:'Ngày',admin_order_customer:'Tên khách hàng',admin_order_total:'Tổng tiền',admin_order_status:'Trạng thái',admin_change_status:'Thay đổi trạng thái',
    admin_user_approve:'✅ Phê duyệt',admin_user_reject:'❌ Từ chối',admin_user_block:'🔒 Chặn',admin_user_unblock:'✅ Bỏ chặn',
    admin_user_pending_badge:'Đang chờ',admin_user_active_badge:'Đang hoạt động',admin_user_blocked_badge:'Đã chặn',
    admin_custom_change_stage:'Thay đổi giai đoạn',admin_pending_users_title:'⏳ Chờ phê duyệt',admin_all_users_title:'👥 Tất cả thành viên',
    admin_no_pending_users:'Không có thành viên chờ phê duyệt.',admin_loading:'Đang tải...',admin_load_fail:'Tải thất bại',admin_no_users:'Không có thành viên.',admin_error:'Đã xảy ra lỗi.',
  },
  es: {
    nav_home:'INICIO',nav_shop:'TIENDA',nav_custom:'CNC Custom Abut',nav_used:'MERCADO USADO',nav_forum:'DISCUSIÓN',nav_events:'EVENTOS',nav_factory:'FÁBRICA',nav_settings:'AJUSTES',
    pt_home:'Inicio',pt_shop:'Tienda',pt_custom:'Custom Abutment',pt_used:'Mercado Usado',pt_forum:'Discusión Clínica',pt_events:'Eventos',pt_factory:'Fábrica',pt_settings:'Ajustes',
    login_subtitle:'ACCESO MÉDICO',login_ph:'Usuario',login_password_ph:'Contraseña',login_btn:'ACCEDER',login_cancel:'Cancelar',login_error:'Por favor, introduce tu usuario y contraseña.',login_verifying:'Verificando...',login_not_found:'Usuario no encontrado o contraseña incorrecta.',login_network_error:'Error de red. Inténtalo de nuevo.',login_register_link:'Solicitar acceso →',
    reg_title:'Solicitar acceso',reg_subtitle:'Rellena tus datos. El administrador aprobará en 24 horas.',reg_license_ph:'Número de licencia (obligatorio)',reg_name_ph:'Nombre del médico (obligatorio)',reg_clinic_ph:'Nombre de la clínica (obligatorio)',reg_contact_ph:'Teléfono o Line ID (obligatorio)',reg_password_ph:'Contraseña (obligatorio)',reg_password_confirm_ph:'Confirmar contraseña (obligatorio)',reg_submit:'Enviar solicitud',reg_submitting:'Enviando...',reg_success:'¡Solicitud enviada!\nNos pondremos en contacto en 24 horas tras la aprobación.',reg_error:'Por favor, completa todos los campos obligatorios.',reg_pwd_mismatch:'Las contraseñas no coinciden.',reg_duplicate:'Este usuario ya está registrado.',reg_network_error:'Error de red. Inténtalo de nuevo.',
    session_title:'Sesión por expirar',session_desc1:'La sesión expira en',session_desc2:'',session_q:'¿Deseas extenderla?',session_extend:'Extender 30 min',session_later:'Después',session_expired:'La sesión ha expirado. Por favor, inicia sesión de nuevo.',
    side_remain:'Tiempo restante:',side_login_btn:'Acceso médico',side_logged_label:'Conectado',side_logout:'Cerrar sesión',
    home_subtitle:'Expert of Implant · Thailand',home_title1:'Componentes de Implante Digital',home_title2:'Sistema de Pedidos',home_desc:'Suministramos componentes de implante BIOTEM de alta calidad directamente a clínicas dentales en toda Tailandia.',home_goto_shop:'Ir a la tienda',home_line_add:'Agregar amigo LINE',
    home_vision_label:'Nuestra visión',home_vision:'Redefiniendo la precisión del implante en el Sudeste Asiático',home_stat1:'Certificado',home_stat2:'Origen',home_stat3:'Cobertura',home_biotem_short:'Experto en Implantes · Corea',home_bioplant_short:'Fabricación · Bangkok',home_mission_label:'Misión',home_mission:'Suministrar componentes de implantes dentales premium fabricados en Corea con servicio rápido y confiable a clínicas de Tailandia y el Sudeste Asiático.',home_footer:'© 2026 Dentalk · BIOTEM × BIOPLANT',
    home_about:'Sobre nosotros',home_biotem_desc:'Fabricante coreano de implantes dentales. Experto en Implantes con soluciones de flujo de trabajo digital de vanguardia.',home_bioplant_desc:'Centro de fabricación de fixtures dentales premium en Bangkok. Suministro a clínicas de todo el Sudeste Asiático.',home_categories:'Categorías de productos',home_contact:'Contacto y dirección',home_address:'Bangkok, Tailandia',home_hours:'Lun–Vie 09:00–18:00',home_line_label:'Line Oficial',
    hero_bioplant_tag:'BIOPLANT Thailand',hero_bioplant_title:'Componentes de Implante Premium',hero_bioplant_desc:'Fabricación coreana certificada ISO, entrega rápida a tu clínica',hero_bioplant_cta:'Comprar ahora',
    hero_cnc_tag:'CNC Custom Abutment',hero_cnc_title:'Soluciones de precisión personalizadas',hero_cnc_desc:'Fabricado según tus especificaciones, del scan body a la restauración',hero_cnc_cta:'Pedir personalizado',
    sec_categories:'Categorías de productos',sec_see_more:'Ver todo ›',cat_scan_body_desc:'Tipos Intra-Oral y Modelo',cat_q_base_desc:'Abutment de Zirconia H=7mm',cat_ready_made_desc:'Ø3.0 · Ø4.5 · Ø5.5 · Ø6.5',cat_ti_base_desc:'CAD/CAM · Ti+Zr',cat_pre_milled_desc:'Compatible milling · N & R',cat_multi_unit_desc:'All-on-X · MUA · Scan Body',cat_3d_analog_desc:'GeoMedi Stone & 3D Model',
    sec_forum_preview:'Discusión clínica',sec_forum_more:'Ver todo ›',home_forum_empty:'Aún no hay publicaciones. ¡Empieza!',
    sec_events_preview:'Próximos eventos',sec_events_more:'Ver todo ›',home_events_empty:'No hay próximos eventos',
    sec_webzine:'Webzine',sec_webzine_sub:'Casos clínicos & actualizaciones de productos',sec_webzine_coming:'Próximamente — Manténete al tanto',
    nav_webzine:'REVISTA',wz_cat_all:'Todos',wz_cat_implant:'Casos de implante',wz_cat_prosthetic:'Casos de prótesis',wz_cat_review:'Reseñas',wz_cat_news:'Noticias',wz_cat_education:'Educación',
    wz_empty:'Aún no hay artículos.',wz_write_btn:'Escribir artículo',wz_form_title:'Nuevo artículo',wz_title_ph:'Título del artículo',wz_thumb_ph:'Haz clic para subir miniatura',wz_body_ph:'Escribe el contenido (Markdown)',wz_submit_btn:'Publicar',wz_fill_alert:'Por favor completa título y contenido.',wz_delete_confirm:'¿Eliminar este artículo?',
    shop_hint:'Selecciona una categoría para pedir',shop_select:'SELECCIONAR ›',shop_each:'ud.',
    order_add_cart:'Añadir al carrito',order_qty_error:'Por favor, introduce al menos 1 unidad.',
    cart_title:'Carrito',cart_total:'TOTAL',cart_checkout:'PAGAR',cart_close:'Cerrar',cart_empty:'¡El carrito está vacío!',
    shop_specs:'Especificaciones & Cant.',shop_in_stock:'En stock',shop_out_of_stock:'Agotado',shop_my_orders:'Mis pedidos',shop_product_count:'productos',cart_bar_tap:'Toca para ver el carrito',cart_bar_items:'artículos',cart_added:'¡Añadido al carrito!',
    addr_title:'Info de entrega',addr_clinic_ph:'Nombre de la clínica',addr_phone_ph:'Número de teléfono',addr_addr_ph:'Dirección completa',addr_qr_btn:'GENERAR QR',addr_back:'← Volver',addr_fill_error:'Por favor, completa toda la información de entrega.',
    qr_label:'Escanear para pagar',qr_summary_title:'Resumen del pedido',qr_total:'TOTAL',qr_complete:'PAGO COMPLETADO',
    used_contact_title:'Contactar vendedor',used_contact_close:'Cerrar',
    custom_tab_new:'Nuevo pedido',custom_tab_list:'Mis pedidos',custom_form_title:'Pedido Custom Abutment',custom_delivery_title:'Info de entrega',custom_clinic_ph:'Clínica / Laboratorio',custom_addr_ph:'Dirección de entrega',custom_phone_ph:'Teléfono de contacto',custom_line_ph:'Line ID (para notificaciones)',custom_submit:'Enviar pedido',custom_submit_note:'La confirmación se enviará por Line',custom_empty:'Aún no hay pedidos',
    case_label:'Caso #',case_remove:'✕ Eliminar',case_patient_ph:'ID paciente (anónimo válido, ej: P001)',case_tooth_hint:'Seleccionar dientes · Toca para alternar',upper_jaw:'Maxilar superior (Upper Jaw)',lower_jaw:'Maxilar inferior (Lower Jaw)',jaw_border:'Límite del arco',selected_teeth:'Dientes seleccionados —',sel_count_suffix:'',brand_ph:'Seleccionar marca de implante',size_ph:'Talla (ej: Ø4.0 / L10)',color_ph:'Color dental (VITA)',case_add:'+ Añadir caso',stl_label:'Subir archivos STL (máx. 10)',stl_hint:'Puedes seleccionar varios archivos .stl',memo_ph:'Solicitudes especiales (opcional)',anon_patient:'Anónimo',case_deadline_label:'Plazo de entrega',
    err_fill_delivery:'Por favor, introduce nombre de clínica, dirección y teléfono.',err_select_tooth:'Caso #%: Por favor, selecciona al menos 1 diente.',err_fill_tooth:'Caso #% Diente #%: Por favor, introduce marca y talla de implante.',err_add_case:'Por favor, añade al menos 1 caso.',
    order_success_msg:'✅ ¡Pedido enviado!\nNº de pedido: %\nCasos: % / Dientes: %',order_success_line:'\nConfirmación enviada por Line.',
    status_label:'Progreso',case_detail:'Detalles del caso',teeth_count:' dientes',cases_unit:' casos',teeth_total_prefix:'',patient_label:'Paciente: ',no_tooth_info:'(sin datos dentales)',case_nr:'Caso #',
    used_sell_title:'Vender piezas usadas',used_name_ph:'Nombre de la pieza',used_code_ph:'Código de producto',used_price_ph:'Precio (THB)',cond_new:'Como nuevo',cond_good:'Bueno',cond_fair:'Regular',used_desc_ph:'Descripción del estado...',used_contact_ph:'Contacto (Line ID / Teléfono)',used_post_btn:'PUBLICAR EN VENTA',used_list_title:'Piezas usadas disponibles',used_contact_btn:'Contactar',used_delete_btn:'Eliminar',used_empty:'Aún no hay piezas usadas',used_fill_error:'Por favor, introduce nombre de pieza, precio y contacto.',
    forum_new_post:'Nueva publicación',forum_title_ph:'Título',forum_body_ph:'Escribe tu mensaje...',forum_post_btn:'PUBLICAR',
    settings_lang:'Idioma',settings_account:'Cuenta',settings_license:'Licencia:',settings_save_btn:'Guardar idioma',settings_saved_msg:'¡Idioma guardado!',settings_pending:'Selecciona un idioma y pulsa Guardar.',
    pe_title:'✏️ Editar mi información',pe_subtitle:'Campos editables',pe_email:'Correo electrónico',pe_phone:'Número de teléfono',pe_address:'Dirección',pe_clinic:'Nombre de la clínica',pe_save:'Guardar',pe_cancel:'Cancelar',pe_email_ph:'Dirección de correo',pe_phone_ph:'Número de teléfono',pe_address_ph:'Dirección',pe_clinic_ph:'Nombre de la clínica',
    profile_title:'👤 Mi información',profile_edit_btn:'Editar',profile_login_msg:'Por favor, inicia sesión para ver.',profile_saved_msg:'✅ ¡Guardado!',profile_no_change:'(no se puede cambiar)',prof_nickname:'Usuario',prof_doctor:'Nombre del médico',login_required:'Inicio de sesión requerido.',
    factory_subtitle:'Centro de fabricación premium de fixtures en Bangkok',
    tooth_11:'Incisivo central',tooth_12:'Incisivo lateral',tooth_13:'Canino',tooth_14:'1er premolar',tooth_15:'2do premolar',tooth_16:'1er molar',tooth_17:'2do molar',
    upper:'Superior',lower:'Inferior',
    stage_received:'Pedido recibido',stage_stl:'Revisión STL',stage_design:'Diseñando',stage_cnc:'Producción CNC',stage_qc:'Control de calidad',stage_shipping:'En envío',stage_done:'Entregado',stage_submitted:'Enviado',stage_confirmed:'Confirmado',stage_design_ready:'Revisión de diseño',stage_design_revision:'Revisión en curso',stage_approved:'Diseño aprobado',stage_milling:'Fresado CNC',stage_shipped:'Enviado',
    line_deadline:'Plazo',line_memo:'Nota',line_total_cases:'Total % casos / % dientes',
    reg_privacy_agree_prefix:'He leído y acepto la',reg_privacy_link:'Política de privacidad',reg_privacy_agree_suffix:'(PDPA Tailandia).',reg_privacy_error:'Por favor, lee y acepta la Política de privacidad para continuar.',
    privacy_title:'Política de privacidad',privacy_close:'Cerrar',
    used_photo_add:'Añadir foto',shop_items:'ud.',
    forum_cat_implant:'🦷 Implante',forum_cat_prosthetic:'💎 Prótesis',forum_cat_conservative:'🪥 Conservadora',forum_cat_orthodontics:'🦷 Ortodoncia',forum_cat_oral_surgery:'✂️ Cirugía oral',forum_cat_periodontics:'🌿 Periodoncia',forum_cat_pediatric:'👶 Odontopediatría',forum_cat_radiology:'📷 Radiología',forum_cat_oral_medicine:'💊 Medicina oral',forum_cat_preventive:'🛡 Preventiva',forum_cat_general:'🏥 General',forum_photo_add:'📷 Añadir fotos (máx. 5)',forum_empty:'No hay publicaciones aún.',
    forum_write_btn:'✍️ Escribir',forum_close_form:'✕ Cerrar',forum_cat_label:'Categoría',
    forum_region_label:'Región',forum_province_label:'Provincia',
    forum_region_all:'🌏 Todo',forum_region_north:'🏔 Norte',forum_region_northeast:'🌾 Noreste',forum_region_east:'🌊 Este',forum_region_south:'🏝 Sur',forum_region_central:'🏙 Central',
    forum_comment_title:'💬 Comentarios',forum_comment_ph:'Escribe un comentario...',forum_comment_submit:'Responder',forum_no_comments:'Aún no hay comentarios.',forum_writing_as:'Publicando como',
    custom_tab_list:'En curso',custom_tab_done:'Completado',
    install_ios:'📱 <b>Instalar en iPhone / Safari</b><br><br>① Toca el botón compartir <b>□↑</b> abajo<br>② Selecciona <b>"Añadir a pantalla de inicio"</b><br>③ Toca <b>"Añadir"</b>',
    install_android:'💻 <b>Instalar en PC / Android</b><br><br>① Haz clic en el <b>icono de instalación ⊕</b><br>&nbsp;&nbsp;&nbsp;a la derecha de la barra de direcciones<br>② Haz clic en <b>"Instalar"</b><br><br>※ Si no hay icono, abre el menú del navegador<br>&nbsp;&nbsp;&nbsp;→ "Instalar como aplicación"',
    install_ok:'Aceptar',
    design_waiting:'⏳ Esperando carga del diseño...',shipped_msg:'🚚 Tu pedido ha sido enviado. Pulsa el botón de abajo al recibirlo.',receive_btn:'📦 Confirmar recepción',
    edit_order_btn:'✏️ Editar',delete_order_btn:'🗑 Eliminar',review_history_label:'Historial de revisión (%)',
    done_orders_empty:'No hay pedidos completados.',done_status_label:'Completado',done_cases_teeth_fmt:'% casos · % dientes',
    reg_nick_ph:'Usuario (obligatorio) — usado en todas las actividades',reg_email_ph:'Dirección de correo electrónico (obligatorio)',
    compose_title:'✉️ Enviar mensaje',compose_to_ph:'Destinatario (usuario)',compose_subj_ph:'Asunto',compose_body_ph:'Escribe tu mensaje...',compose_send:'Enviar',
    ship_carrier_custom_opt:'Introducir manualmente',ship_carrier_ph:'Nombre del transportista',ship_tracking_label:'Número de seguimiento',ship_tracking_ph:'Introducir número de seguimiento',ship_process_btn:'🚚 Procesar envío → Enviar LINE',
    leader_badge:'Líder regional',leader_assign:'Asignar',leader_remove:'Quitar líder',leader_select_region:'Seleccionar región...',
    forum_pinned:'Fijado',forum_pin:'Fijar',forum_unpin:'Desfijar',forum_delete:'Eliminar',forum_delete_confirm:'¿Estás seguro de que quieres eliminar esta publicación?',event_delete_confirm:'¿Estás seguro de que quieres eliminar este evento?',
    admin_new_event_title:'Añadir nuevo evento',admin_event_name_ph:'Nombre del evento',admin_event_loc_ph:'Lugar',admin_event_add_btn:'+ Añadir',admin_event_fill_alert:'Por favor, rellena todos los campos.',
    meetup_create_btn:'Crear reunión',meetup_badge:'Reunión',event_badge:'Evento',meetup_form_title:'Crear nueva reunión',meetup_title_ph:'Título de la reunión',meetup_loc_ph:'Lugar',meetup_desc_ph:'Descripción (opcional)',meetup_submit_btn:'Crear reunión',meetup_fill_alert:'Por favor, rellena título, fecha y lugar.',meetup_created_by:'Creado por',
    rsvp_title:'Confirmación',rsvp_attend:'✅ Asistir',rsvp_not_attend:'❌ No asistir',rsvp_attendees:'asistentes',rsvp_attendee_list:'Lista de asistentes',rsvp_no_attendees:'Aún no hay asistentes.',rsvp_login_required:'Inicia sesión para confirmar.',rsvp_error:'Error al confirmar. Inténtalo de nuevo.',
    admin_orders_new:'Nuevos',admin_orders_active:'En curso',admin_orders_done:'Completado',admin_orders_empty:'No hay pedidos.',
    shipped_status:'Enviado',carrier_label:'Transportista',tracking_label:'Seguimiento',received_status:'Recibido',teeth_colon_label:'Dientes:',
    wiz_step1:'Paciente & Dientes',wiz_step2:'Marca',wiz_step3:'Color & Notas',wiz_step4:'STL',wiz_step5:'Confirmar',wiz_next:'Siguiente →',wiz_prev:'← Atrás',wiz_patient_label:'ID paciente',wiz_no_tooth_err:'Por favor selecciona al menos 1 diente.',wiz_no_brand_err:'Por favor selecciona una marca de implante.',wiz_brand_all_hint:'Se aplica a todos los dientes seleccionados',wiz_size_for_tooth:'Talla (ej: Ø4.0 / L10)',wiz_shade_label:'Color dental (VITA)',wiz_stl_main_label:'Archivos STL / 3D',wiz_stl_main_hint:'Arrastra o toca para seleccionar · Máx 10 archivos',wiz_confirm_title:'Resumen del pedido',wiz_delivery_label:'Información de entrega',wiz_teeth_selected:'dientes seleccionados',wiz_start_over:'Nuevo pedido',wiz_size_table_title:'Talla por diente',
    used_post_toggle:'📸 Publicar artículo usado',used_close_form:'✕ Cerrar',settings_my_orders:'📦 Mis pedidos',settings_no_orders:'Aún no hay pedidos',
    admin_panel_title:'Panel de administración',admin_total_members:'Total miembros',admin_pending_orders:'Pedidos pendientes',admin_today_signups:'Nuevos hoy',
    admin_tab_orders:'Gestión de pedidos',admin_tab_users:'Gestión de miembros',admin_tab_custom:'Pedidos personalizados',
    admin_order_date:'Fecha',admin_order_customer:'Cliente',admin_order_total:'Total',admin_order_status:'Estado',admin_change_status:'Cambiar estado',
    admin_user_approve:'✅ Aprobar',admin_user_reject:'❌ Rechazar',admin_user_block:'🔒 Bloquear',admin_user_unblock:'✅ Desbloquear',
    admin_user_pending_badge:'Pendiente',admin_user_active_badge:'Activo',admin_user_blocked_badge:'Bloqueado',
    admin_custom_change_stage:'Cambiar etapa',admin_pending_users_title:'⏳ Pendiente de aprobación',admin_all_users_title:'👥 Todos los miembros',
    admin_no_pending_users:'No hay aprobaciones pendientes.',admin_loading:'Cargando...',admin_load_fail:'Error al cargar',admin_no_users:'No hay miembros.',admin_error:'Se produjo un error.',
  },
};

function t(key) { return (LANG[currentLang] || LANG.en)[key] || key; }
function tf(key) {
  var s = t(key);
  for (var i = 1; i < arguments.length; i++) s = s.replace('%', String(arguments[i]));
  return s;
}
